// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/models"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "header",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "footer",
//	      "type": "anonymousNbt"
//	    }
//	  ]
//	]
type PlayerlistHeader struct {
	packetID int32
	// "anonymousNbt"
	Header models.AnonymousNBT
	// "anonymousNbt"
	Footer models.AnonymousNBT
}

// NewPlayerlistHeader creates a new PlayerlistHeader packet with the correct packet ID.
func NewPlayerlistHeader() *PlayerlistHeader {
	return &PlayerlistHeader{packetID: 115}
}

// PacketID returns the protocol ID for this packet type.
func (p *PlayerlistHeader) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *PlayerlistHeader) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *PlayerlistHeader) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Header,
		&p.Footer)
}

// Scan deserializes a wire-format packet into this struct.
func (p *PlayerlistHeader) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.Header,
		&p.Footer)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *PlayerlistHeader) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Header"] = p.Header
	fields["Footer"] = p.Footer
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *PlayerlistHeader) SetFields(fields map[string]pk.FieldEncoder) {
	fmt.Printf("<no value>\n")
	if val, ok := fields["Header"]; ok {
		p.Header = val.(models.AnonymousNBT)
	}
	if val, ok := fields["Footer"]; ok {
		p.Footer = val.(models.AnonymousNBT)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetHeader returns the Header field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *PlayerlistHeader) GetHeader() models.AnonymousNBT {
	return p.Header
}

// SetHeader sets the Header field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *PlayerlistHeader) SetHeader(val models.AnonymousNBT) {
	p.Header = val
}

// GetFooter returns the Footer field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *PlayerlistHeader) GetFooter() models.AnonymousNBT {
	return p.Footer
}

// SetFooter sets the Footer field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *PlayerlistHeader) SetFooter(val models.AnonymousNBT) {
	p.Footer = val
}

func (t *PlayerlistHeader) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Header.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Header")
	}
	bytesRead, err = t.Footer.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Footer")
	}

	return totalBytes, nil
}

func (t PlayerlistHeader) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[PlayerlistHeader.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Header.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Footer.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
