// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
)

type PacketName struct {
	Value string
}

var PacketNameMappings = map[int64]string{
	0x00: "server_info",
	0x01: "ping",
}

func (m *PacketName) ReadFrom(r io.Reader) (int64, error) {
	var key pk.VarInt
	n, err := key.ReadFrom(r)
	if err != nil {
		return n, errors.Wrap(err, "failed to read PacketName key")
	}

	value, ok := PacketNameMappings[int64(key)]
	if !ok {
		// Use numeric key as fallback for unknown/undocumented values
		m.Value = fmt.Sprintf("unknown_%d", key)
		return n, nil
	}
	m.Value = value
	return n, nil
}

func (m PacketName) WriteTo(w io.Writer) (int64, error) {
	for k, v := range PacketNameMappings {
		if v == m.Value {
			key := pk.VarInt(k)
			return key.WriteTo(w)
		}
	}
	return 0, errors.Errorf("unknown PacketName value: '%s'", m.Value)
}
