// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "itemID",
//	      "type": "varint"
//	    },
//	    {
//	      "name": "cooldownTicks",
//	      "type": "varint"
//	    }
//	  ]
//	]
type SetCooldown struct {
	packetID int32
	// "varint"
	ItemID pk.VarInt
	// "varint"
	CooldownTicks pk.VarInt
}

// NewSetCooldown creates a new SetCooldown packet with the correct packet ID.
func NewSetCooldown() *SetCooldown {
	return &SetCooldown{packetID: 23}
}

// PacketID returns the protocol ID for this packet type.
func (p *SetCooldown) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *SetCooldown) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *SetCooldown) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.ItemID,
		&p.CooldownTicks)
}

// Scan deserializes a wire-format packet into this struct.
func (p *SetCooldown) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.ItemID,
		&p.CooldownTicks)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *SetCooldown) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["ItemID"] = &p.ItemID
	fields["CooldownTicks"] = &p.CooldownTicks
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *SetCooldown) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["ItemID"]; ok {
		p.ItemID = *val.(*pk.VarInt)
	}
	if val, ok := fields["CooldownTicks"]; ok {
		p.CooldownTicks = *val.(*pk.VarInt)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetItemID returns the ItemID field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SetCooldown) GetItemID() pk.VarInt {
	return p.ItemID
}

// SetItemID sets the ItemID field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SetCooldown) SetItemID(val pk.VarInt) {
	p.ItemID = val
}

// GetCooldownTicks returns the CooldownTicks field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SetCooldown) GetCooldownTicks() pk.VarInt {
	return p.CooldownTicks
}

// SetCooldownTicks sets the CooldownTicks field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SetCooldown) SetCooldownTicks(val pk.VarInt) {
	p.CooldownTicks = val
}

func (t *SetCooldown) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.ItemID.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field ItemID")
	}
	bytesRead, err = t.CooldownTicks.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field CooldownTicks")
	}

	return totalBytes, nil
}

func (t SetCooldown) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[SetCooldown.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.ItemID.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.CooldownTicks.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
