// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "x",
//	      "type": "f64"
//	    },
//	    {
//	      "name": "y",
//	      "type": "f64"
//	    },
//	    {
//	      "name": "z",
//	      "type": "f64"
//	    },
//	    {
//	      "name": "yaw",
//	      "type": "f32"
//	    },
//	    {
//	      "name": "pitch",
//	      "type": "f32"
//	    },
//	    {
//	      "name": "flags",
//	      "type": "PositionUpdateRelatives"
//	    },
//	    {
//	      "name": "teleportId",
//	      "type": "varint"
//	    }
//	  ]
//	]
type Position struct {
	packetID int32
	// "f64"
	X pk.Double
	// "f64"
	Y pk.Double
	// "f64"
	Z pk.Double
	// "f32"
	Yaw pk.Float
	// "f32"
	Pitch pk.Float
	// "PositionUpdateRelatives"
	Flags PositionUpdateRelatives
	// "varint"
	TeleportId pk.VarInt
}

// NewPosition creates a new Position packet with the correct packet ID.
func NewPosition() *Position {
	return &Position{packetID: 64}
}

// PacketID returns the protocol ID for this packet type.
func (p *Position) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *Position) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *Position) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.X,
		&p.Y,
		&p.Z,
		&p.Yaw,
		&p.Pitch,
		&p.Flags,
		&p.TeleportId)
}

// Scan deserializes a wire-format packet into this struct.
func (p *Position) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.X,
		&p.Y,
		&p.Z,
		&p.Yaw,
		&p.Pitch,
		&p.Flags,
		&p.TeleportId)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *Position) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["X"] = p.X
	fields["Y"] = p.Y
	fields["Z"] = p.Z
	fields["Yaw"] = p.Yaw
	fields["Pitch"] = p.Pitch
	fields["Flags"] = p.Flags
	fields["TeleportId"] = p.TeleportId
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *Position) SetFields(fields map[string]pk.FieldEncoder) {
	fmt.Printf("<no value>\n")
	if val, ok := fields["X"]; ok {
		p.X = val.(pk.Double)
	}
	if val, ok := fields["Y"]; ok {
		p.Y = val.(pk.Double)
	}
	if val, ok := fields["Z"]; ok {
		p.Z = val.(pk.Double)
	}
	if val, ok := fields["Yaw"]; ok {
		p.Yaw = val.(pk.Float)
	}
	if val, ok := fields["Pitch"]; ok {
		p.Pitch = val.(pk.Float)
	}
	if val, ok := fields["Flags"]; ok {
		p.Flags = val.(PositionUpdateRelatives)
	}
	if val, ok := fields["TeleportId"]; ok {
		p.TeleportId = val.(pk.VarInt)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetX returns the X field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Position) GetX() pk.Double {
	return p.X
}

// SetX sets the X field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Position) SetX(val pk.Double) {
	p.X = val
}

// GetY returns the Y field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Position) GetY() pk.Double {
	return p.Y
}

// SetY sets the Y field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Position) SetY(val pk.Double) {
	p.Y = val
}

// GetZ returns the Z field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Position) GetZ() pk.Double {
	return p.Z
}

// SetZ sets the Z field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Position) SetZ(val pk.Double) {
	p.Z = val
}

// GetYaw returns the Yaw field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Position) GetYaw() pk.Float {
	return p.Yaw
}

// SetYaw sets the Yaw field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Position) SetYaw(val pk.Float) {
	p.Yaw = val
}

// GetPitch returns the Pitch field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Position) GetPitch() pk.Float {
	return p.Pitch
}

// SetPitch sets the Pitch field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Position) SetPitch(val pk.Float) {
	p.Pitch = val
}

// GetFlags returns the Flags field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Position) GetFlags() PositionUpdateRelatives {
	return p.Flags
}

// SetFlags sets the Flags field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Position) SetFlags(val PositionUpdateRelatives) {
	p.Flags = val
}

// GetTeleportId returns the TeleportId field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Position) GetTeleportId() pk.VarInt {
	return p.TeleportId
}

// SetTeleportId sets the TeleportId field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Position) SetTeleportId(val pk.VarInt) {
	p.TeleportId = val
}

func (t *Position) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.X.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field X")
	}
	bytesRead, err = t.Y.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Y")
	}
	bytesRead, err = t.Z.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Z")
	}
	bytesRead, err = t.Yaw.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Yaw")
	}
	bytesRead, err = t.Pitch.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Pitch")
	}
	bytesRead, err = t.Flags.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Flags")
	}
	bytesRead, err = t.TeleportId.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field TeleportId")
	}

	return totalBytes, nil
}

func (t Position) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[Position.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.X.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Y.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Z.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Yaw.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Pitch.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Flags.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.TeleportId.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}

// PositionUpdateRelatives provides named accessors over a bitflag field.
type PositionUpdateRelatives struct {
	pk.UnsignedByte
}

func (bf PositionUpdateRelatives) X() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 0)) != 0
}

func (bf *PositionUpdateRelatives) SetX(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 0)
	} else {
		v &^= (1 << 0)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
func (bf PositionUpdateRelatives) Y() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 1)) != 0
}

func (bf *PositionUpdateRelatives) SetY(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 1)
	} else {
		v &^= (1 << 1)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
func (bf PositionUpdateRelatives) Z() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 2)) != 0
}

func (bf *PositionUpdateRelatives) SetZ(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 2)
	} else {
		v &^= (1 << 2)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
func (bf PositionUpdateRelatives) Yaw() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 3)) != 0
}

func (bf *PositionUpdateRelatives) SetYaw(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 3)
	} else {
		v &^= (1 << 3)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
func (bf PositionUpdateRelatives) Pitch() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 4)) != 0
}

func (bf *PositionUpdateRelatives) SetPitch(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 4)
	} else {
		v &^= (1 << 4)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
