// Generated by gen_protocol (packet). DO NOT EDIT
package v26_1

import (
	"fmt"
	"log"

	"github.com/reallyoldfogie/mc-protocol-go/models"
)

type Packets struct{}

func (p Packets) GetClientboundLoginPacketID(name string) models.ClientboundPacketID {
	log.Printf("GetClientboundLoginPacketID(\"%s\")\n", name)

	switch name {
	case "LoginClientboundDisconnect", "ClientboundLoginLoginDisconnect":
		return LoginClientboundDisconnect // 0 0X00
	case "LoginClientboundEncryptionBegin", "ClientboundLoginHello":
		return LoginClientboundEncryptionBegin // 1 0X01
	case "LoginClientboundSuccess", "ClientboundLoginLoginFinished":
		return LoginClientboundSuccess // 2 0X02
	case "LoginClientboundCompress", "ClientboundLoginLoginCompression":
		return LoginClientboundCompress // 3 0X03
	case "LoginClientboundLoginPluginRequest", "ClientboundLoginCustomQuery":
		return LoginClientboundLoginPluginRequest // 4 0X04
	case "LoginClientboundCommonCookieRequest", "ClientboundLoginCookieRequest":
		return LoginClientboundCommonCookieRequest // 5 0X05
	case "LoginClientboundPacketIDGuard":
		return 6
	default:
		log.Printf("GetClientboundLoginPacketID => unknown packet name: %s\n", name)
		return models.ClientboundPacketID(-1) // unknown packet name
	}
}

func (p Packets) GetServerboundLoginPacketID(name string) models.ServerboundPacketID {
	log.Printf("GetServerboundLoginPacketID(\"%s\")\n", name)

	switch name {
	case "LoginServerboundLoginStart", "ServerboundLoginHello":
		return LoginServerboundLoginStart // 0 0X00
	case "LoginServerboundEncryptionBegin", "ServerboundLoginKey":
		return LoginServerboundEncryptionBegin // 1 0X01
	case "LoginServerboundLoginPluginResponse", "ServerboundLoginCustomQueryAnswer":
		return LoginServerboundLoginPluginResponse // 2 0X02
	case "LoginServerboundLoginAcknowledged", "ServerboundLoginLoginAcknowledged":
		return LoginServerboundLoginAcknowledged // 3 0X03
	case "LoginServerboundCommonCookieResponse", "ServerboundLoginCookieResponse":
		return LoginServerboundCommonCookieResponse // 4 0X04
	case "LoginServerboundPacketIDGuard":
		return 5
	default:
		log.Printf("GetServerboundLoginPacketID => unknown packet name: %s\n", name)
		return models.ServerboundPacketID(-1) // unknown packet name
	}
}

func (p Packets) ClientboundLoginToString(id models.ClientboundPacketID) string {
	switch id {

	case LoginClientboundDisconnect:
		return "LoginClientboundDisconnect" // 0 0X00
	case LoginClientboundEncryptionBegin:
		return "LoginClientboundEncryptionBegin" // 1 0X01
	case LoginClientboundSuccess:
		return "LoginClientboundSuccess" // 2 0X02
	case LoginClientboundCompress:
		return "LoginClientboundCompress" // 3 0X03
	case LoginClientboundLoginPluginRequest:
		return "LoginClientboundLoginPluginRequest" // 4 0X04
	case LoginClientboundCommonCookieRequest:
		return "LoginClientboundCommonCookieRequest" // 5 0X05
	case 6:
		return "LoginClientboundPacketIDGuard"
	default:
		return fmt.Sprintf("Unknown Clientbound Login packet ID: %d", id)
	}
}

func (p Packets) GetClientboundConfigPacketID(name string) models.ClientboundPacketID {
	log.Printf("GetClientboundConfigPacketID(\"%s\")\n", name)

	switch name {
	case "ClientboundConfigCommonCookieRequest", "ClientboundConfigCookieRequest":
		return ClientboundConfigCommonCookieRequest // 0 0X00
	case "ClientboundConfigCustomPayload":
		return ClientboundConfigCustomPayload // 1 0X01
	case "ClientboundConfigDisconnect":
		return ClientboundConfigDisconnect // 2 0X02
	case "ClientboundConfigFinishConfiguration":
		return ClientboundConfigFinishConfiguration // 3 0X03
	case "ClientboundConfigKeepAlive":
		return ClientboundConfigKeepAlive // 4 0X04
	case "ClientboundConfigPing":
		return ClientboundConfigPing // 5 0X05
	case "ClientboundConfigResetChat":
		return ClientboundConfigResetChat // 6 0X06
	case "ClientboundConfigRegistryData":
		return ClientboundConfigRegistryData // 7 0X07
	case "ClientboundConfigCommonRemoveResourcePack", "ClientboundConfigResourcePackPop":
		return ClientboundConfigCommonRemoveResourcePack // 8 0X08
	case "ClientboundConfigCommonAddResourcePack", "ClientboundConfigResourcePackPush":
		return ClientboundConfigCommonAddResourcePack // 9 0X09
	case "ClientboundConfigCommonStoreCookie", "ClientboundConfigStoreCookie":
		return ClientboundConfigCommonStoreCookie // 10 0X0A
	case "ClientboundConfigCommonTransfer", "ClientboundConfigTransfer":
		return ClientboundConfigCommonTransfer // 11 0X0B
	case "ClientboundConfigFeatureFlags", "ClientboundConfigUpdateEnabledFeatures":
		return ClientboundConfigFeatureFlags // 12 0X0C
	case "ClientboundConfigTags", "ClientboundConfigUpdateTags":
		return ClientboundConfigTags // 13 0X0D
	case "ClientboundConfigCommonSelectKnownPacks", "ClientboundConfigSelectKnownPacks":
		return ClientboundConfigCommonSelectKnownPacks // 14 0X0E
	case "ClientboundConfigCommonCustomReportDetails", "ClientboundConfigCustomReportDetails":
		return ClientboundConfigCommonCustomReportDetails // 15 0X0F
	case "ClientboundConfigCommonServerLinks", "ClientboundConfigServerLinks":
		return ClientboundConfigCommonServerLinks // 16 0X10
	case "ClientboundConfigCommonClearDialog", "ClientboundConfigClearDialog":
		return ClientboundConfigCommonClearDialog // 17 0X11
	case "ClientboundConfigShowDialog":
		return ClientboundConfigShowDialog // 18 0X12
	case "ClientboundConfigCodeOfConduct":
		return ClientboundConfigCodeOfConduct // 19 0X13
	case "ClientboundConfigPacketIDGuard":
		return 20
	default:
		log.Printf("GetClientboundConfigPacketID => unknown packet name: %s\n", name)
		return models.ClientboundPacketID(-1) // unknown packet name
	}
}

func (p Packets) ClientboundConfigToString(id models.ClientboundPacketID) string {
	switch id {

	case ClientboundConfigCommonCookieRequest:
		return "ClientboundConfigCommonCookieRequest" // 0 0X00
	case ClientboundConfigCustomPayload:
		return "ClientboundConfigCustomPayload" // 1 0X01
	case ClientboundConfigDisconnect:
		return "ClientboundConfigDisconnect" // 2 0X02
	case ClientboundConfigFinishConfiguration:
		return "ClientboundConfigFinishConfiguration" // 3 0X03
	case ClientboundConfigKeepAlive:
		return "ClientboundConfigKeepAlive" // 4 0X04
	case ClientboundConfigPing:
		return "ClientboundConfigPing" // 5 0X05
	case ClientboundConfigResetChat:
		return "ClientboundConfigResetChat" // 6 0X06
	case ClientboundConfigRegistryData:
		return "ClientboundConfigRegistryData" // 7 0X07
	case ClientboundConfigCommonRemoveResourcePack:
		return "ClientboundConfigCommonRemoveResourcePack" // 8 0X08
	case ClientboundConfigCommonAddResourcePack:
		return "ClientboundConfigCommonAddResourcePack" // 9 0X09
	case ClientboundConfigCommonStoreCookie:
		return "ClientboundConfigCommonStoreCookie" // 10 0X0A
	case ClientboundConfigCommonTransfer:
		return "ClientboundConfigCommonTransfer" // 11 0X0B
	case ClientboundConfigFeatureFlags:
		return "ClientboundConfigFeatureFlags" // 12 0X0C
	case ClientboundConfigTags:
		return "ClientboundConfigTags" // 13 0X0D
	case ClientboundConfigCommonSelectKnownPacks:
		return "ClientboundConfigCommonSelectKnownPacks" // 14 0X0E
	case ClientboundConfigCommonCustomReportDetails:
		return "ClientboundConfigCommonCustomReportDetails" // 15 0X0F
	case ClientboundConfigCommonServerLinks:
		return "ClientboundConfigCommonServerLinks" // 16 0X10
	case ClientboundConfigCommonClearDialog:
		return "ClientboundConfigCommonClearDialog" // 17 0X11
	case ClientboundConfigShowDialog:
		return "ClientboundConfigShowDialog" // 18 0X12
	case ClientboundConfigCodeOfConduct:
		return "ClientboundConfigCodeOfConduct" // 19 0X13
	case 20:
		return "ClientboundConfigPacketIDGuard"
	default:
		return fmt.Sprintf("Unknown Clientbound Configuration packet ID: %d", id)
	}
}

func (p Packets) GetServerboundConfigPacketID(name string) models.ServerboundPacketID {
	log.Printf("GetServerboundConfigPacketID(\"%s\")\n", name)

	switch name {
	case "ServerboundConfigCommonSettings", "ServerboundConfigClientInformation":
		return ServerboundConfigCommonSettings // 0 0X00
	case "ServerboundConfigCommonCookieResponse", "ServerboundConfigCookieResponse":
		return ServerboundConfigCommonCookieResponse // 1 0X01
	case "ServerboundConfigCustomPayload":
		return ServerboundConfigCustomPayload // 2 0X02
	case "ServerboundConfigFinishConfiguration":
		return ServerboundConfigFinishConfiguration // 3 0X03
	case "ServerboundConfigKeepAlive":
		return ServerboundConfigKeepAlive // 4 0X04
	case "ServerboundConfigPong":
		return ServerboundConfigPong // 5 0X05
	case "ServerboundConfigResourcePackReceive", "ServerboundConfigResourcePack":
		return ServerboundConfigResourcePackReceive // 6 0X06
	case "ServerboundConfigCommonSelectKnownPacks", "ServerboundConfigSelectKnownPacks":
		return ServerboundConfigCommonSelectKnownPacks // 7 0X07
	case "ServerboundConfigCommonCustomClickAction", "ServerboundConfigCustomClickAction":
		return ServerboundConfigCommonCustomClickAction // 8 0X08
	case "ServerboundConfigAcceptCodeOfConduct":
		return ServerboundConfigAcceptCodeOfConduct // 9 0X09
	case "ServerboundConfigPacketIDGuard":
		return 10
	default:
		log.Printf("GetServerboundConfigPacketID => unknown packet name: %s\n", name)
		return models.ServerboundPacketID(-1) // unknown packet name
	}
}

func (p Packets) ServerboundConfigToString(id models.ServerboundPacketID) string {
	switch id {

	case ServerboundConfigCommonSettings:
		return "ServerboundConfigCommonSettings" // 0 0X00
	case ServerboundConfigCommonCookieResponse:
		return "ServerboundConfigCommonCookieResponse" // 1 0X01
	case ServerboundConfigCustomPayload:
		return "ServerboundConfigCustomPayload" // 2 0X02
	case ServerboundConfigFinishConfiguration:
		return "ServerboundConfigFinishConfiguration" // 3 0X03
	case ServerboundConfigKeepAlive:
		return "ServerboundConfigKeepAlive" // 4 0X04
	case ServerboundConfigPong:
		return "ServerboundConfigPong" // 5 0X05
	case ServerboundConfigResourcePackReceive:
		return "ServerboundConfigResourcePackReceive" // 6 0X06
	case ServerboundConfigCommonSelectKnownPacks:
		return "ServerboundConfigCommonSelectKnownPacks" // 7 0X07
	case ServerboundConfigCommonCustomClickAction:
		return "ServerboundConfigCommonCustomClickAction" // 8 0X08
	case ServerboundConfigAcceptCodeOfConduct:
		return "ServerboundConfigAcceptCodeOfConduct" // 9 0X09
	case 10:
		return "ServerboundConfigPacketIDGuard"
	default:
		return fmt.Sprintf("Unknown Serverbound Configuration packet ID: %d", id)
	}
}

func (p Packets) GetClientboundPacketID(name string) models.ClientboundPacketID {
	switch name {

	case "Clientboundmodels.Void", "ClientboundBundleDelimiter":
		return ClientboundVoid // 0 0X00
	case "ClientboundSpawnEntity", "ClientboundAddEntity":
		return ClientboundSpawnEntity // 1 0X01
	case "ClientboundAnimation", "ClientboundAnimate":
		return ClientboundAnimation // 2 0X02
	case "ClientboundStatistics", "ClientboundAwardStats":
		return ClientboundStatistics // 3 0X03
	case "ClientboundAcknowledgePlayerDigging", "ClientboundBlockChangedAck":
		return ClientboundAcknowledgePlayerDigging // 4 0X04
	case "ClientboundBlockBreakAnimation", "ClientboundBlockDestruction":
		return ClientboundBlockBreakAnimation // 5 0X05
	case "ClientboundTileEntityData", "ClientboundBlockEntityData":
		return ClientboundTileEntityData // 6 0X06
	case "ClientboundBlockAction", "ClientboundBlockEvent":
		return ClientboundBlockAction // 7 0X07
	case "ClientboundBlockChange", "ClientboundBlockUpdate":
		return ClientboundBlockChange // 8 0X08
	case "ClientboundBossBar", "ClientboundBossEvent":
		return ClientboundBossBar // 9 0X09
	case "ClientboundDifficulty", "ClientboundChangeDifficulty":
		return ClientboundDifficulty // 10 0X0A
	case "ClientboundChunkBatchFinished":
		return ClientboundChunkBatchFinished // 11 0X0B
	case "ClientboundChunkBatchStart":
		return ClientboundChunkBatchStart // 12 0X0C
	case "ClientboundChunkBiomes", "ClientboundChunksBiomes":
		return ClientboundChunkBiomes // 13 0X0D
	case "ClientboundClearTitles":
		return ClientboundClearTitles // 14 0X0E
	case "ClientboundTabComplete", "ClientboundCommandSuggestions":
		return ClientboundTabComplete // 15 0X0F
	case "ClientboundDeclareCommands", "ClientboundCommands":
		return ClientboundDeclareCommands // 16 0X10
	case "ClientboundCloseWindow", "ClientboundContainerClose":
		return ClientboundCloseWindow // 17 0X11
	case "ClientboundWindowItems", "ClientboundContainerSetContent":
		return ClientboundWindowItems // 18 0X12
	case "ClientboundCraftProgressBar", "ClientboundContainerSetData":
		return ClientboundCraftProgressBar // 19 0X13
	case "ClientboundSetSlot", "ClientboundContainerSetSlot":
		return ClientboundSetSlot // 20 0X14
	case "ClientboundCommonCookieRequest", "ClientboundCookieRequest":
		return ClientboundCommonCookieRequest // 21 0X15
	case "ClientboundSetCooldown", "ClientboundCooldown":
		return ClientboundSetCooldown // 22 0X16
	case "ClientboundChatSuggestions", "ClientboundCustomChatCompletions":
		return ClientboundChatSuggestions // 23 0X17
	case "ClientboundCustomPayload":
		return ClientboundCustomPayload // 24 0X18
	case "ClientboundDamageEvent":
		return ClientboundDamageEvent // 25 0X19
	case "ClientboundDebugBlockValue", "ClientboundDebug/blockValue":
		return ClientboundDebugBlockValue // 26 0X1A
	case "ClientboundDebugChunkValue", "ClientboundDebug/chunkValue":
		return ClientboundDebugChunkValue // 27 0X1B
	case "ClientboundDebugEntityValue", "ClientboundDebug/entityValue":
		return ClientboundDebugEntityValue // 28 0X1C
	case "ClientboundDebugEvent", "ClientboundDebug/event":
		return ClientboundDebugEvent // 29 0X1D
	case "ClientboundDebugSample":
		return ClientboundDebugSample // 30 0X1E
	case "ClientboundHideMessage", "ClientboundDeleteChat":
		return ClientboundHideMessage // 31 0X1F
	case "ClientboundKickDisconnect", "ClientboundDisconnect":
		return ClientboundKickDisconnect // 32 0X20
	case "ClientboundProfilelessChat", "ClientboundDisguisedChat":
		return ClientboundProfilelessChat // 33 0X21
	case "ClientboundEntityStatus", "ClientboundEntityEvent":
		return ClientboundEntityStatus // 34 0X22
	case "ClientboundSyncEntityPosition", "ClientboundEntityPositionSync":
		return ClientboundSyncEntityPosition // 35 0X23
	case "ClientboundExplosion", "ClientboundExplode":
		return ClientboundExplosion // 36 0X24
	case "ClientboundUnloadChunk", "ClientboundForgetLevelChunk":
		return ClientboundUnloadChunk // 37 0X25
	case "ClientboundGameStateChange", "ClientboundGameEvent":
		return ClientboundGameStateChange // 38 0X26
	case "ClientboundGameRuleValues":
		return ClientboundGameRuleValues // 39 0X27
	case "ClientboundGameTestHighlightPos":
		return ClientboundGameTestHighlightPos // 40 0X28
	case "ClientboundOpenHorseWindow", "ClientboundMountScreenOpen":
		return ClientboundOpenHorseWindow // 41 0X29
	case "ClientboundHurtAnimation":
		return ClientboundHurtAnimation // 42 0X2A
	case "ClientboundInitializeWorldBorder", "ClientboundInitializeBorder":
		return ClientboundInitializeWorldBorder // 43 0X2B
	case "ClientboundKeepAlive":
		return ClientboundKeepAlive // 44 0X2C
	case "ClientboundMapChunk", "ClientboundLevelChunkWithLight":
		return ClientboundMapChunk // 45 0X2D
	case "ClientboundWorldEvent", "ClientboundLevelEvent":
		return ClientboundWorldEvent // 46 0X2E
	case "ClientboundWorldParticles", "ClientboundLevelParticles":
		return ClientboundWorldParticles // 47 0X2F
	case "ClientboundUpdateLight", "ClientboundLightUpdate":
		return ClientboundUpdateLight // 48 0X30
	case "ClientboundLogin":
		return ClientboundLogin // 49 0X31
	case "ClientboundLowDiskSpaceWarning":
		return ClientboundLowDiskSpaceWarning // 50 0X32
	case "ClientboundMap", "ClientboundMapItemData":
		return ClientboundMap // 51 0X33
	case "ClientboundTradeList", "ClientboundMerchantOffers":
		return ClientboundTradeList // 52 0X34
	case "ClientboundRelEntityMove", "ClientboundMoveEntityPos":
		return ClientboundRelEntityMove // 53 0X35
	case "ClientboundEntityMoveLook", "ClientboundMoveEntityPosRot":
		return ClientboundEntityMoveLook // 54 0X36
	case "ClientboundMoveMinecart", "ClientboundMoveMinecartAlongTrack":
		return ClientboundMoveMinecart // 55 0X37
	case "ClientboundEntityLook", "ClientboundMoveEntityRot":
		return ClientboundEntityLook // 56 0X38
	case "ClientboundVehicleMove", "ClientboundMoveVehicle":
		return ClientboundVehicleMove // 57 0X39
	case "ClientboundOpenBook":
		return ClientboundOpenBook // 58 0X3A
	case "ClientboundOpenWindow", "ClientboundOpenScreen":
		return ClientboundOpenWindow // 59 0X3B
	case "ClientboundOpenSignEntity", "ClientboundOpenSignEditor":
		return ClientboundOpenSignEntity // 60 0X3C
	case "ClientboundPing":
		return ClientboundPing // 61 0X3D
	case "ClientboundPingResponse", "ClientboundPongResponse":
		return ClientboundPingResponse // 62 0X3E
	case "ClientboundCraftRecipeResponse", "ClientboundPlaceGhostRecipe":
		return ClientboundCraftRecipeResponse // 63 0X3F
	case "ClientboundAbilities", "ClientboundPlayerAbilities":
		return ClientboundAbilities // 64 0X40
	case "ClientboundPlayerChat":
		return ClientboundPlayerChat // 65 0X41
	case "ClientboundEndCombatEvent", "ClientboundPlayerCombatEnd":
		return ClientboundEndCombatEvent // 66 0X42
	case "ClientboundEnterCombatEvent", "ClientboundPlayerCombatEnter":
		return ClientboundEnterCombatEvent // 67 0X43
	case "ClientboundDeathCombatEvent", "ClientboundPlayerCombatKill":
		return ClientboundDeathCombatEvent // 68 0X44
	case "ClientboundPlayerRemove", "ClientboundPlayerInfoRemove":
		return ClientboundPlayerRemove // 69 0X45
	case "ClientboundPlayerInfo", "ClientboundPlayerInfoUpdate":
		return ClientboundPlayerInfo // 70 0X46
	case "ClientboundFacePlayer", "ClientboundPlayerLookAt":
		return ClientboundFacePlayer // 71 0X47
	case "ClientboundPosition", "ClientboundPlayerPosition":
		return ClientboundPosition // 72 0X48
	case "ClientboundPlayerRotation":
		return ClientboundPlayerRotation // 73 0X49
	case "ClientboundRecipeBookAdd":
		return ClientboundRecipeBookAdd // 74 0X4A
	case "ClientboundRecipeBookRemove":
		return ClientboundRecipeBookRemove // 75 0X4B
	case "ClientboundRecipeBookSettings":
		return ClientboundRecipeBookSettings // 76 0X4C
	case "ClientboundEntityDestroy", "ClientboundRemoveEntities":
		return ClientboundEntityDestroy // 77 0X4D
	case "ClientboundRemoveEntityEffect", "ClientboundRemoveMobEffect":
		return ClientboundRemoveEntityEffect // 78 0X4E
	case "ClientboundResetScore":
		return ClientboundResetScore // 79 0X4F
	case "ClientboundCommonRemoveResourcePack", "ClientboundResourcePackPop":
		return ClientboundCommonRemoveResourcePack // 80 0X50
	case "ClientboundCommonAddResourcePack", "ClientboundResourcePackPush":
		return ClientboundCommonAddResourcePack // 81 0X51
	case "ClientboundRespawn":
		return ClientboundRespawn // 82 0X52
	case "ClientboundEntityHeadRotation", "ClientboundRotateHead":
		return ClientboundEntityHeadRotation // 83 0X53
	case "ClientboundMultiBlockChange", "ClientboundSectionBlocksUpdate":
		return ClientboundMultiBlockChange // 84 0X54
	case "ClientboundSelectAdvancementTab", "ClientboundSelectAdvancementsTab":
		return ClientboundSelectAdvancementTab // 85 0X55
	case "ClientboundServerData":
		return ClientboundServerData // 86 0X56
	case "ClientboundActionBar", "ClientboundSetActionBarText":
		return ClientboundActionBar // 87 0X57
	case "ClientboundWorldBorderCenter", "ClientboundSetBorderCenter":
		return ClientboundWorldBorderCenter // 88 0X58
	case "ClientboundWorldBorderLerpSize", "ClientboundSetBorderLerpSize":
		return ClientboundWorldBorderLerpSize // 89 0X59
	case "ClientboundWorldBorderSize", "ClientboundSetBorderSize":
		return ClientboundWorldBorderSize // 90 0X5A
	case "ClientboundWorldBorderWarningDelay", "ClientboundSetBorderWarningDelay":
		return ClientboundWorldBorderWarningDelay // 91 0X5B
	case "ClientboundWorldBorderWarningReach", "ClientboundSetBorderWarningDistance":
		return ClientboundWorldBorderWarningReach // 92 0X5C
	case "ClientboundCamera", "ClientboundSetCamera":
		return ClientboundCamera // 93 0X5D
	case "ClientboundUpdateViewPosition", "ClientboundSetChunkCacheCenter":
		return ClientboundUpdateViewPosition // 94 0X5E
	case "ClientboundUpdateViewDistance", "ClientboundSetChunkCacheRadius":
		return ClientboundUpdateViewDistance // 95 0X5F
	case "ClientboundSetCursorItem":
		return ClientboundSetCursorItem // 96 0X60
	case "ClientboundSpawnPosition", "ClientboundSetDefaultSpawnPosition":
		return ClientboundSpawnPosition // 97 0X61
	case "ClientboundScoreboardDisplayObjective", "ClientboundSetDisplayObjective":
		return ClientboundScoreboardDisplayObjective // 98 0X62
	case "ClientboundEntityMetadata", "ClientboundSetEntityData":
		return ClientboundEntityMetadata // 99 0X63
	case "ClientboundAttachEntity", "ClientboundSetEntityLink":
		return ClientboundAttachEntity // 100 0X64
	case "ClientboundEntityVelocity", "ClientboundSetEntityMotion":
		return ClientboundEntityVelocity // 101 0X65
	case "ClientboundEntityEquipment", "ClientboundSetEquipment":
		return ClientboundEntityEquipment // 102 0X66
	case "ClientboundExperience", "ClientboundSetExperience":
		return ClientboundExperience // 103 0X67
	case "ClientboundUpdateHealth", "ClientboundSetHealth":
		return ClientboundUpdateHealth // 104 0X68
	case "ClientboundHeldItemSlot", "ClientboundSetHeldSlot":
		return ClientboundHeldItemSlot // 105 0X69
	case "ClientboundScoreboardObjective", "ClientboundSetObjective":
		return ClientboundScoreboardObjective // 106 0X6A
	case "ClientboundSetPassengers":
		return ClientboundSetPassengers // 107 0X6B
	case "ClientboundSetPlayerInventory":
		return ClientboundSetPlayerInventory // 108 0X6C
	case "ClientboundTeams", "ClientboundSetPlayerTeam":
		return ClientboundTeams // 109 0X6D
	case "ClientboundScoreboardScore", "ClientboundSetScore":
		return ClientboundScoreboardScore // 110 0X6E
	case "ClientboundSimulationDistance", "ClientboundSetSimulationDistance":
		return ClientboundSimulationDistance // 111 0X6F
	case "ClientboundSetTitleSubtitle", "ClientboundSetSubtitleText":
		return ClientboundSetTitleSubtitle // 112 0X70
	case "ClientboundUpdateTime", "ClientboundSetTime":
		return ClientboundUpdateTime // 113 0X71
	case "ClientboundSetTitleText":
		return ClientboundSetTitleText // 114 0X72
	case "ClientboundSetTitleTime", "ClientboundSetTitlesAnimation":
		return ClientboundSetTitleTime // 115 0X73
	case "ClientboundEntitySoundEffect", "ClientboundSoundEntity":
		return ClientboundEntitySoundEffect // 116 0X74
	case "ClientboundSoundEffect", "ClientboundSound":
		return ClientboundSoundEffect // 117 0X75
	case "ClientboundStartConfiguration":
		return ClientboundStartConfiguration // 118 0X76
	case "ClientboundStopSound":
		return ClientboundStopSound // 119 0X77
	case "ClientboundCommonStoreCookie", "ClientboundStoreCookie":
		return ClientboundCommonStoreCookie // 120 0X78
	case "ClientboundSystemChat":
		return ClientboundSystemChat // 121 0X79
	case "ClientboundPlayerlistHeader", "ClientboundTabList":
		return ClientboundPlayerlistHeader // 122 0X7A
	case "ClientboundNbtQueryResponse", "ClientboundTagQuery":
		return ClientboundNbtQueryResponse // 123 0X7B
	case "ClientboundCollect", "ClientboundTakeItemEntity":
		return ClientboundCollect // 124 0X7C
	case "ClientboundEntityTeleport", "ClientboundTeleportEntity":
		return ClientboundEntityTeleport // 125 0X7D
	case "ClientboundTestInstanceBlockStatus":
		return ClientboundTestInstanceBlockStatus // 126 0X7E
	case "ClientboundSetTickingState", "ClientboundTickingState":
		return ClientboundSetTickingState // 127 0X7F
	case "ClientboundStepTick", "ClientboundTickingStep":
		return ClientboundStepTick // 128 0X80
	case "ClientboundCommonTransfer", "ClientboundTransfer":
		return ClientboundCommonTransfer // 129 0X81
	case "ClientboundAdvancements", "ClientboundUpdateAdvancements":
		return ClientboundAdvancements // 130 0X82
	case "ClientboundEntityUpdateAttributes", "ClientboundUpdateAttributes":
		return ClientboundEntityUpdateAttributes // 131 0X83
	case "ClientboundEntityEffect", "ClientboundUpdateMobEffect":
		return ClientboundEntityEffect // 132 0X84
	case "ClientboundDeclareRecipes", "ClientboundUpdateRecipes":
		return ClientboundDeclareRecipes // 133 0X85
	case "ClientboundTags", "ClientboundUpdateTags":
		return ClientboundTags // 134 0X86
	case "ClientboundSetProjectilePower", "ClientboundProjectilePower":
		return ClientboundSetProjectilePower // 135 0X87
	case "ClientboundCommonCustomReportDetails", "ClientboundCustomReportDetails":
		return ClientboundCommonCustomReportDetails // 136 0X88
	case "ClientboundCommonServerLinks", "ClientboundServerLinks":
		return ClientboundCommonServerLinks // 137 0X89
	case "ClientboundTrackedWaypoint", "ClientboundWaypoint":
		return ClientboundTrackedWaypoint // 138 0X8A
	case "ClientboundCommonClearDialog", "ClientboundClearDialog":
		return ClientboundCommonClearDialog // 139 0X8B
	case "ClientboundShowDialog":
		return ClientboundShowDialog // 140 0X8C
	case "ClientboundPacketIDGuard":
		return 141
	default:
		log.Printf("GetClientboundPacketID => unknown packet name: %s\n", name)
		return models.ClientboundPacketID(-1) // unknown packet name
	}
}

func (p Packets) ClientboundToString(id models.ClientboundPacketID) string {
	switch id {

	case ClientboundVoid:
		return "ClientboundVoid" // 0 0X00
	case ClientboundSpawnEntity:
		return "ClientboundSpawnEntity" // 1 0X01
	case ClientboundAnimation:
		return "ClientboundAnimation" // 2 0X02
	case ClientboundStatistics:
		return "ClientboundStatistics" // 3 0X03
	case ClientboundAcknowledgePlayerDigging:
		return "ClientboundAcknowledgePlayerDigging" // 4 0X04
	case ClientboundBlockBreakAnimation:
		return "ClientboundBlockBreakAnimation" // 5 0X05
	case ClientboundTileEntityData:
		return "ClientboundTileEntityData" // 6 0X06
	case ClientboundBlockAction:
		return "ClientboundBlockAction" // 7 0X07
	case ClientboundBlockChange:
		return "ClientboundBlockChange" // 8 0X08
	case ClientboundBossBar:
		return "ClientboundBossBar" // 9 0X09
	case ClientboundDifficulty:
		return "ClientboundDifficulty" // 10 0X0A
	case ClientboundChunkBatchFinished:
		return "ClientboundChunkBatchFinished" // 11 0X0B
	case ClientboundChunkBatchStart:
		return "ClientboundChunkBatchStart" // 12 0X0C
	case ClientboundChunkBiomes:
		return "ClientboundChunkBiomes" // 13 0X0D
	case ClientboundClearTitles:
		return "ClientboundClearTitles" // 14 0X0E
	case ClientboundTabComplete:
		return "ClientboundTabComplete" // 15 0X0F
	case ClientboundDeclareCommands:
		return "ClientboundDeclareCommands" // 16 0X10
	case ClientboundCloseWindow:
		return "ClientboundCloseWindow" // 17 0X11
	case ClientboundWindowItems:
		return "ClientboundWindowItems" // 18 0X12
	case ClientboundCraftProgressBar:
		return "ClientboundCraftProgressBar" // 19 0X13
	case ClientboundSetSlot:
		return "ClientboundSetSlot" // 20 0X14
	case ClientboundCommonCookieRequest:
		return "ClientboundCommonCookieRequest" // 21 0X15
	case ClientboundSetCooldown:
		return "ClientboundSetCooldown" // 22 0X16
	case ClientboundChatSuggestions:
		return "ClientboundChatSuggestions" // 23 0X17
	case ClientboundCustomPayload:
		return "ClientboundCustomPayload" // 24 0X18
	case ClientboundDamageEvent:
		return "ClientboundDamageEvent" // 25 0X19
	case ClientboundDebugBlockValue:
		return "ClientboundDebugBlockValue" // 26 0X1A
	case ClientboundDebugChunkValue:
		return "ClientboundDebugChunkValue" // 27 0X1B
	case ClientboundDebugEntityValue:
		return "ClientboundDebugEntityValue" // 28 0X1C
	case ClientboundDebugEvent:
		return "ClientboundDebugEvent" // 29 0X1D
	case ClientboundDebugSample:
		return "ClientboundDebugSample" // 30 0X1E
	case ClientboundHideMessage:
		return "ClientboundHideMessage" // 31 0X1F
	case ClientboundKickDisconnect:
		return "ClientboundKickDisconnect" // 32 0X20
	case ClientboundProfilelessChat:
		return "ClientboundProfilelessChat" // 33 0X21
	case ClientboundEntityStatus:
		return "ClientboundEntityStatus" // 34 0X22
	case ClientboundSyncEntityPosition:
		return "ClientboundSyncEntityPosition" // 35 0X23
	case ClientboundExplosion:
		return "ClientboundExplosion" // 36 0X24
	case ClientboundUnloadChunk:
		return "ClientboundUnloadChunk" // 37 0X25
	case ClientboundGameStateChange:
		return "ClientboundGameStateChange" // 38 0X26
	case ClientboundGameRuleValues:
		return "ClientboundGameRuleValues" // 39 0X27
	case ClientboundGameTestHighlightPos:
		return "ClientboundGameTestHighlightPos" // 40 0X28
	case ClientboundOpenHorseWindow:
		return "ClientboundOpenHorseWindow" // 41 0X29
	case ClientboundHurtAnimation:
		return "ClientboundHurtAnimation" // 42 0X2A
	case ClientboundInitializeWorldBorder:
		return "ClientboundInitializeWorldBorder" // 43 0X2B
	case ClientboundKeepAlive:
		return "ClientboundKeepAlive" // 44 0X2C
	case ClientboundMapChunk:
		return "ClientboundMapChunk" // 45 0X2D
	case ClientboundWorldEvent:
		return "ClientboundWorldEvent" // 46 0X2E
	case ClientboundWorldParticles:
		return "ClientboundWorldParticles" // 47 0X2F
	case ClientboundUpdateLight:
		return "ClientboundUpdateLight" // 48 0X30
	case ClientboundLogin:
		return "ClientboundLogin" // 49 0X31
	case ClientboundLowDiskSpaceWarning:
		return "ClientboundLowDiskSpaceWarning" // 50 0X32
	case ClientboundMap:
		return "ClientboundMap" // 51 0X33
	case ClientboundTradeList:
		return "ClientboundTradeList" // 52 0X34
	case ClientboundRelEntityMove:
		return "ClientboundRelEntityMove" // 53 0X35
	case ClientboundEntityMoveLook:
		return "ClientboundEntityMoveLook" // 54 0X36
	case ClientboundMoveMinecart:
		return "ClientboundMoveMinecart" // 55 0X37
	case ClientboundEntityLook:
		return "ClientboundEntityLook" // 56 0X38
	case ClientboundVehicleMove:
		return "ClientboundVehicleMove" // 57 0X39
	case ClientboundOpenBook:
		return "ClientboundOpenBook" // 58 0X3A
	case ClientboundOpenWindow:
		return "ClientboundOpenWindow" // 59 0X3B
	case ClientboundOpenSignEntity:
		return "ClientboundOpenSignEntity" // 60 0X3C
	case ClientboundPing:
		return "ClientboundPing" // 61 0X3D
	case ClientboundPingResponse:
		return "ClientboundPingResponse" // 62 0X3E
	case ClientboundCraftRecipeResponse:
		return "ClientboundCraftRecipeResponse" // 63 0X3F
	case ClientboundAbilities:
		return "ClientboundAbilities" // 64 0X40
	case ClientboundPlayerChat:
		return "ClientboundPlayerChat" // 65 0X41
	case ClientboundEndCombatEvent:
		return "ClientboundEndCombatEvent" // 66 0X42
	case ClientboundEnterCombatEvent:
		return "ClientboundEnterCombatEvent" // 67 0X43
	case ClientboundDeathCombatEvent:
		return "ClientboundDeathCombatEvent" // 68 0X44
	case ClientboundPlayerRemove:
		return "ClientboundPlayerRemove" // 69 0X45
	case ClientboundPlayerInfo:
		return "ClientboundPlayerInfo" // 70 0X46
	case ClientboundFacePlayer:
		return "ClientboundFacePlayer" // 71 0X47
	case ClientboundPosition:
		return "ClientboundPosition" // 72 0X48
	case ClientboundPlayerRotation:
		return "ClientboundPlayerRotation" // 73 0X49
	case ClientboundRecipeBookAdd:
		return "ClientboundRecipeBookAdd" // 74 0X4A
	case ClientboundRecipeBookRemove:
		return "ClientboundRecipeBookRemove" // 75 0X4B
	case ClientboundRecipeBookSettings:
		return "ClientboundRecipeBookSettings" // 76 0X4C
	case ClientboundEntityDestroy:
		return "ClientboundEntityDestroy" // 77 0X4D
	case ClientboundRemoveEntityEffect:
		return "ClientboundRemoveEntityEffect" // 78 0X4E
	case ClientboundResetScore:
		return "ClientboundResetScore" // 79 0X4F
	case ClientboundCommonRemoveResourcePack:
		return "ClientboundCommonRemoveResourcePack" // 80 0X50
	case ClientboundCommonAddResourcePack:
		return "ClientboundCommonAddResourcePack" // 81 0X51
	case ClientboundRespawn:
		return "ClientboundRespawn" // 82 0X52
	case ClientboundEntityHeadRotation:
		return "ClientboundEntityHeadRotation" // 83 0X53
	case ClientboundMultiBlockChange:
		return "ClientboundMultiBlockChange" // 84 0X54
	case ClientboundSelectAdvancementTab:
		return "ClientboundSelectAdvancementTab" // 85 0X55
	case ClientboundServerData:
		return "ClientboundServerData" // 86 0X56
	case ClientboundActionBar:
		return "ClientboundActionBar" // 87 0X57
	case ClientboundWorldBorderCenter:
		return "ClientboundWorldBorderCenter" // 88 0X58
	case ClientboundWorldBorderLerpSize:
		return "ClientboundWorldBorderLerpSize" // 89 0X59
	case ClientboundWorldBorderSize:
		return "ClientboundWorldBorderSize" // 90 0X5A
	case ClientboundWorldBorderWarningDelay:
		return "ClientboundWorldBorderWarningDelay" // 91 0X5B
	case ClientboundWorldBorderWarningReach:
		return "ClientboundWorldBorderWarningReach" // 92 0X5C
	case ClientboundCamera:
		return "ClientboundCamera" // 93 0X5D
	case ClientboundUpdateViewPosition:
		return "ClientboundUpdateViewPosition" // 94 0X5E
	case ClientboundUpdateViewDistance:
		return "ClientboundUpdateViewDistance" // 95 0X5F
	case ClientboundSetCursorItem:
		return "ClientboundSetCursorItem" // 96 0X60
	case ClientboundSpawnPosition:
		return "ClientboundSpawnPosition" // 97 0X61
	case ClientboundScoreboardDisplayObjective:
		return "ClientboundScoreboardDisplayObjective" // 98 0X62
	case ClientboundEntityMetadata:
		return "ClientboundEntityMetadata" // 99 0X63
	case ClientboundAttachEntity:
		return "ClientboundAttachEntity" // 100 0X64
	case ClientboundEntityVelocity:
		return "ClientboundEntityVelocity" // 101 0X65
	case ClientboundEntityEquipment:
		return "ClientboundEntityEquipment" // 102 0X66
	case ClientboundExperience:
		return "ClientboundExperience" // 103 0X67
	case ClientboundUpdateHealth:
		return "ClientboundUpdateHealth" // 104 0X68
	case ClientboundHeldItemSlot:
		return "ClientboundHeldItemSlot" // 105 0X69
	case ClientboundScoreboardObjective:
		return "ClientboundScoreboardObjective" // 106 0X6A
	case ClientboundSetPassengers:
		return "ClientboundSetPassengers" // 107 0X6B
	case ClientboundSetPlayerInventory:
		return "ClientboundSetPlayerInventory" // 108 0X6C
	case ClientboundTeams:
		return "ClientboundTeams" // 109 0X6D
	case ClientboundScoreboardScore:
		return "ClientboundScoreboardScore" // 110 0X6E
	case ClientboundSimulationDistance:
		return "ClientboundSimulationDistance" // 111 0X6F
	case ClientboundSetTitleSubtitle:
		return "ClientboundSetTitleSubtitle" // 112 0X70
	case ClientboundUpdateTime:
		return "ClientboundUpdateTime" // 113 0X71
	case ClientboundSetTitleText:
		return "ClientboundSetTitleText" // 114 0X72
	case ClientboundSetTitleTime:
		return "ClientboundSetTitleTime" // 115 0X73
	case ClientboundEntitySoundEffect:
		return "ClientboundEntitySoundEffect" // 116 0X74
	case ClientboundSoundEffect:
		return "ClientboundSoundEffect" // 117 0X75
	case ClientboundStartConfiguration:
		return "ClientboundStartConfiguration" // 118 0X76
	case ClientboundStopSound:
		return "ClientboundStopSound" // 119 0X77
	case ClientboundCommonStoreCookie:
		return "ClientboundCommonStoreCookie" // 120 0X78
	case ClientboundSystemChat:
		return "ClientboundSystemChat" // 121 0X79
	case ClientboundPlayerlistHeader:
		return "ClientboundPlayerlistHeader" // 122 0X7A
	case ClientboundNbtQueryResponse:
		return "ClientboundNbtQueryResponse" // 123 0X7B
	case ClientboundCollect:
		return "ClientboundCollect" // 124 0X7C
	case ClientboundEntityTeleport:
		return "ClientboundEntityTeleport" // 125 0X7D
	case ClientboundTestInstanceBlockStatus:
		return "ClientboundTestInstanceBlockStatus" // 126 0X7E
	case ClientboundSetTickingState:
		return "ClientboundSetTickingState" // 127 0X7F
	case ClientboundStepTick:
		return "ClientboundStepTick" // 128 0X80
	case ClientboundCommonTransfer:
		return "ClientboundCommonTransfer" // 129 0X81
	case ClientboundAdvancements:
		return "ClientboundAdvancements" // 130 0X82
	case ClientboundEntityUpdateAttributes:
		return "ClientboundEntityUpdateAttributes" // 131 0X83
	case ClientboundEntityEffect:
		return "ClientboundEntityEffect" // 132 0X84
	case ClientboundDeclareRecipes:
		return "ClientboundDeclareRecipes" // 133 0X85
	case ClientboundTags:
		return "ClientboundTags" // 134 0X86
	case ClientboundSetProjectilePower:
		return "ClientboundSetProjectilePower" // 135 0X87
	case ClientboundCommonCustomReportDetails:
		return "ClientboundCommonCustomReportDetails" // 136 0X88
	case ClientboundCommonServerLinks:
		return "ClientboundCommonServerLinks" // 137 0X89
	case ClientboundTrackedWaypoint:
		return "ClientboundTrackedWaypoint" // 138 0X8A
	case ClientboundCommonClearDialog:
		return "ClientboundCommonClearDialog" // 139 0X8B
	case ClientboundShowDialog:
		return "ClientboundShowDialog" // 140 0X8C
	case 141:
		return "ClientboundPacketIDGuard"
	default:
		return fmt.Sprintf("Unknown Clientbound packet ID: %d", id)
	}
}

func (p Packets) GetServerboundPacketID(name string) models.ServerboundPacketID {
	switch name {

	case "ServerboundTeleportConfirm", "ServerboundAcceptTeleportation":
		return ServerboundTeleportConfirm // 0 0X00
	case "ServerboundAttack":
		return ServerboundAttack // 1 0X01
	case "ServerboundQueryBlockNbt", "ServerboundBlockEntityTagQuery":
		return ServerboundQueryBlockNbt // 2 0X02
	case "ServerboundSelectBundleItem", "ServerboundBundleItemSelected":
		return ServerboundSelectBundleItem // 3 0X03
	case "ServerboundSetDifficulty", "ServerboundChangeDifficulty":
		return ServerboundSetDifficulty // 4 0X04
	case "ServerboundChangeGamemode", "ServerboundChangeGameMode":
		return ServerboundChangeGamemode // 5 0X05
	case "ServerboundMessageAcknowledgement", "ServerboundChatAck":
		return ServerboundMessageAcknowledgement // 6 0X06
	case "ServerboundChatCommand":
		return ServerboundChatCommand // 7 0X07
	case "ServerboundChatCommandSigned":
		return ServerboundChatCommandSigned // 8 0X08
	case "ServerboundChatMessage", "ServerboundChat":
		return ServerboundChatMessage // 9 0X09
	case "ServerboundChatSessionUpdate":
		return ServerboundChatSessionUpdate // 10 0X0A
	case "ServerboundChunkBatchReceived":
		return ServerboundChunkBatchReceived // 11 0X0B
	case "ServerboundClientCommand":
		return ServerboundClientCommand // 12 0X0C
	case "ServerboundTickEnd", "ServerboundClientTickEnd":
		return ServerboundTickEnd // 13 0X0D
	case "ServerboundCommonSettings", "ServerboundClientInformation":
		return ServerboundCommonSettings // 14 0X0E
	case "ServerboundTabComplete", "ServerboundCommandSuggestion":
		return ServerboundTabComplete // 15 0X0F
	case "ServerboundConfigurationAcknowledged":
		return ServerboundConfigurationAcknowledged // 16 0X10
	case "ServerboundEnchantItem", "ServerboundContainerButtonClick":
		return ServerboundEnchantItem // 17 0X11
	case "ServerboundWindowClick", "ServerboundContainerClick":
		return ServerboundWindowClick // 18 0X12
	case "ServerboundCloseWindow", "ServerboundContainerClose":
		return ServerboundCloseWindow // 19 0X13
	case "ServerboundSetSlotState", "ServerboundContainerSlotStateChanged":
		return ServerboundSetSlotState // 20 0X14
	case "ServerboundCommonCookieResponse", "ServerboundCookieResponse":
		return ServerboundCommonCookieResponse // 21 0X15
	case "ServerboundCustomPayload":
		return ServerboundCustomPayload // 22 0X16
	case "ServerboundDebugSubscriptionRequest":
		return ServerboundDebugSubscriptionRequest // 23 0X17
	case "ServerboundEditBook":
		return ServerboundEditBook // 24 0X18
	case "ServerboundQueryEntityNbt", "ServerboundEntityTagQuery":
		return ServerboundQueryEntityNbt // 25 0X19
	case "ServerboundUseEntity", "ServerboundInteract":
		return ServerboundUseEntity // 26 0X1A
	case "ServerboundGenerateStructure", "ServerboundJigsawGenerate":
		return ServerboundGenerateStructure // 27 0X1B
	case "ServerboundKeepAlive":
		return ServerboundKeepAlive // 28 0X1C
	case "ServerboundLockDifficulty":
		return ServerboundLockDifficulty // 29 0X1D
	case "ServerboundPosition", "ServerboundMovePlayerPos":
		return ServerboundPosition // 30 0X1E
	case "ServerboundPositionLook", "ServerboundMovePlayerPosRot":
		return ServerboundPositionLook // 31 0X1F
	case "ServerboundLook", "ServerboundMovePlayerRot":
		return ServerboundLook // 32 0X20
	case "ServerboundFlying", "ServerboundMovePlayerStatusOnly":
		return ServerboundFlying // 33 0X21
	case "ServerboundVehicleMove", "ServerboundMoveVehicle":
		return ServerboundVehicleMove // 34 0X22
	case "ServerboundSteerBoat", "ServerboundPaddleBoat":
		return ServerboundSteerBoat // 35 0X23
	case "ServerboundPickItemFromBlock":
		return ServerboundPickItemFromBlock // 36 0X24
	case "ServerboundPickItemFromEntity":
		return ServerboundPickItemFromEntity // 37 0X25
	case "ServerboundPingRequest":
		return ServerboundPingRequest // 38 0X26
	case "ServerboundCraftRecipeRequest", "ServerboundPlaceRecipe":
		return ServerboundCraftRecipeRequest // 39 0X27
	case "ServerboundAbilities", "ServerboundPlayerAbilities":
		return ServerboundAbilities // 40 0X28
	case "ServerboundBlockDig", "ServerboundPlayerAction":
		return ServerboundBlockDig // 41 0X29
	case "ServerboundEntityAction", "ServerboundPlayerCommand":
		return ServerboundEntityAction // 42 0X2A
	case "ServerboundPlayerInput":
		return ServerboundPlayerInput // 43 0X2B
	case "ServerboundPlayerLoaded":
		return ServerboundPlayerLoaded // 44 0X2C
	case "ServerboundPong":
		return ServerboundPong // 45 0X2D
	case "ServerboundRecipeBook", "ServerboundRecipeBookChangeSettings":
		return ServerboundRecipeBook // 46 0X2E
	case "ServerboundDisplayedRecipe", "ServerboundRecipeBookSeenRecipe":
		return ServerboundDisplayedRecipe // 47 0X2F
	case "ServerboundNameItem", "ServerboundRenameItem":
		return ServerboundNameItem // 48 0X30
	case "ServerboundResourcePackReceive", "ServerboundResourcePack":
		return ServerboundResourcePackReceive // 49 0X31
	case "ServerboundAdvancementTab", "ServerboundSeenAdvancements":
		return ServerboundAdvancementTab // 50 0X32
	case "ServerboundSelectTrade":
		return ServerboundSelectTrade // 51 0X33
	case "ServerboundSetBeaconEffect", "ServerboundSetBeacon":
		return ServerboundSetBeaconEffect // 52 0X34
	case "ServerboundHeldItemSlot", "ServerboundSetCarriedItem":
		return ServerboundHeldItemSlot // 53 0X35
	case "ServerboundUpdateCommandBlock", "ServerboundSetCommandBlock":
		return ServerboundUpdateCommandBlock // 54 0X36
	case "ServerboundUpdateCommandBlockMinecart", "ServerboundSetCommandMinecart":
		return ServerboundUpdateCommandBlockMinecart // 55 0X37
	case "ServerboundSetCreativeSlot", "ServerboundSetCreativeModeSlot":
		return ServerboundSetCreativeSlot // 56 0X38
	case "ServerboundSetGameRule":
		return ServerboundSetGameRule // 57 0X39
	case "ServerboundUpdateJigsawBlock", "ServerboundSetJigsawBlock":
		return ServerboundUpdateJigsawBlock // 58 0X3A
	case "ServerboundUpdateStructureBlock", "ServerboundSetStructureBlock":
		return ServerboundUpdateStructureBlock // 59 0X3B
	case "ServerboundSetTestBlock":
		return ServerboundSetTestBlock // 60 0X3C
	case "ServerboundUpdateSign", "ServerboundSignUpdate":
		return ServerboundUpdateSign // 61 0X3D
	case "ServerboundSpectateEntity":
		return ServerboundSpectateEntity // 62 0X3E
	case "ServerboundArmAnimation", "ServerboundSwing":
		return ServerboundArmAnimation // 63 0X3F
	case "ServerboundSpectate", "ServerboundTeleportToEntity":
		return ServerboundSpectate // 64 0X40
	case "ServerboundTestInstanceBlockAction":
		return ServerboundTestInstanceBlockAction // 65 0X41
	case "ServerboundBlockPlace", "ServerboundUseItemOn":
		return ServerboundBlockPlace // 66 0X42
	case "ServerboundUseItem":
		return ServerboundUseItem // 67 0X43
	case "ServerboundCommonCustomClickAction", "ServerboundCustomClickAction":
		return ServerboundCommonCustomClickAction // 68 0X44
	case "ServerboundPacketIDGuard":
		return 69
	default:
		log.Printf("GetServerboundPacketID => unknown packet name: %s\n", name)
		return models.ServerboundPacketID(-1) // unknown packet name
	}
}

func (p Packets) ServerboundToString(id models.ServerboundPacketID) string {
	switch id {

	case ServerboundTeleportConfirm:
		return "ServerboundTeleportConfirm" // 0 0X00
	case ServerboundAttack:
		return "ServerboundAttack" // 1 0X01
	case ServerboundQueryBlockNbt:
		return "ServerboundQueryBlockNbt" // 2 0X02
	case ServerboundSelectBundleItem:
		return "ServerboundSelectBundleItem" // 3 0X03
	case ServerboundSetDifficulty:
		return "ServerboundSetDifficulty" // 4 0X04
	case ServerboundChangeGamemode:
		return "ServerboundChangeGamemode" // 5 0X05
	case ServerboundMessageAcknowledgement:
		return "ServerboundMessageAcknowledgement" // 6 0X06
	case ServerboundChatCommand:
		return "ServerboundChatCommand" // 7 0X07
	case ServerboundChatCommandSigned:
		return "ServerboundChatCommandSigned" // 8 0X08
	case ServerboundChatMessage:
		return "ServerboundChatMessage" // 9 0X09
	case ServerboundChatSessionUpdate:
		return "ServerboundChatSessionUpdate" // 10 0X0A
	case ServerboundChunkBatchReceived:
		return "ServerboundChunkBatchReceived" // 11 0X0B
	case ServerboundClientCommand:
		return "ServerboundClientCommand" // 12 0X0C
	case ServerboundTickEnd:
		return "ServerboundTickEnd" // 13 0X0D
	case ServerboundCommonSettings:
		return "ServerboundCommonSettings" // 14 0X0E
	case ServerboundTabComplete:
		return "ServerboundTabComplete" // 15 0X0F
	case ServerboundConfigurationAcknowledged:
		return "ServerboundConfigurationAcknowledged" // 16 0X10
	case ServerboundEnchantItem:
		return "ServerboundEnchantItem" // 17 0X11
	case ServerboundWindowClick:
		return "ServerboundWindowClick" // 18 0X12
	case ServerboundCloseWindow:
		return "ServerboundCloseWindow" // 19 0X13
	case ServerboundSetSlotState:
		return "ServerboundSetSlotState" // 20 0X14
	case ServerboundCommonCookieResponse:
		return "ServerboundCommonCookieResponse" // 21 0X15
	case ServerboundCustomPayload:
		return "ServerboundCustomPayload" // 22 0X16
	case ServerboundDebugSubscriptionRequest:
		return "ServerboundDebugSubscriptionRequest" // 23 0X17
	case ServerboundEditBook:
		return "ServerboundEditBook" // 24 0X18
	case ServerboundQueryEntityNbt:
		return "ServerboundQueryEntityNbt" // 25 0X19
	case ServerboundUseEntity:
		return "ServerboundUseEntity" // 26 0X1A
	case ServerboundGenerateStructure:
		return "ServerboundGenerateStructure" // 27 0X1B
	case ServerboundKeepAlive:
		return "ServerboundKeepAlive" // 28 0X1C
	case ServerboundLockDifficulty:
		return "ServerboundLockDifficulty" // 29 0X1D
	case ServerboundPosition:
		return "ServerboundPosition" // 30 0X1E
	case ServerboundPositionLook:
		return "ServerboundPositionLook" // 31 0X1F
	case ServerboundLook:
		return "ServerboundLook" // 32 0X20
	case ServerboundFlying:
		return "ServerboundFlying" // 33 0X21
	case ServerboundVehicleMove:
		return "ServerboundVehicleMove" // 34 0X22
	case ServerboundSteerBoat:
		return "ServerboundSteerBoat" // 35 0X23
	case ServerboundPickItemFromBlock:
		return "ServerboundPickItemFromBlock" // 36 0X24
	case ServerboundPickItemFromEntity:
		return "ServerboundPickItemFromEntity" // 37 0X25
	case ServerboundPingRequest:
		return "ServerboundPingRequest" // 38 0X26
	case ServerboundCraftRecipeRequest:
		return "ServerboundCraftRecipeRequest" // 39 0X27
	case ServerboundAbilities:
		return "ServerboundAbilities" // 40 0X28
	case ServerboundBlockDig:
		return "ServerboundBlockDig" // 41 0X29
	case ServerboundEntityAction:
		return "ServerboundEntityAction" // 42 0X2A
	case ServerboundPlayerInput:
		return "ServerboundPlayerInput" // 43 0X2B
	case ServerboundPlayerLoaded:
		return "ServerboundPlayerLoaded" // 44 0X2C
	case ServerboundPong:
		return "ServerboundPong" // 45 0X2D
	case ServerboundRecipeBook:
		return "ServerboundRecipeBook" // 46 0X2E
	case ServerboundDisplayedRecipe:
		return "ServerboundDisplayedRecipe" // 47 0X2F
	case ServerboundNameItem:
		return "ServerboundNameItem" // 48 0X30
	case ServerboundResourcePackReceive:
		return "ServerboundResourcePackReceive" // 49 0X31
	case ServerboundAdvancementTab:
		return "ServerboundAdvancementTab" // 50 0X32
	case ServerboundSelectTrade:
		return "ServerboundSelectTrade" // 51 0X33
	case ServerboundSetBeaconEffect:
		return "ServerboundSetBeaconEffect" // 52 0X34
	case ServerboundHeldItemSlot:
		return "ServerboundHeldItemSlot" // 53 0X35
	case ServerboundUpdateCommandBlock:
		return "ServerboundUpdateCommandBlock" // 54 0X36
	case ServerboundUpdateCommandBlockMinecart:
		return "ServerboundUpdateCommandBlockMinecart" // 55 0X37
	case ServerboundSetCreativeSlot:
		return "ServerboundSetCreativeSlot" // 56 0X38
	case ServerboundSetGameRule:
		return "ServerboundSetGameRule" // 57 0X39
	case ServerboundUpdateJigsawBlock:
		return "ServerboundUpdateJigsawBlock" // 58 0X3A
	case ServerboundUpdateStructureBlock:
		return "ServerboundUpdateStructureBlock" // 59 0X3B
	case ServerboundSetTestBlock:
		return "ServerboundSetTestBlock" // 60 0X3C
	case ServerboundUpdateSign:
		return "ServerboundUpdateSign" // 61 0X3D
	case ServerboundSpectateEntity:
		return "ServerboundSpectateEntity" // 62 0X3E
	case ServerboundArmAnimation:
		return "ServerboundArmAnimation" // 63 0X3F
	case ServerboundSpectate:
		return "ServerboundSpectate" // 64 0X40
	case ServerboundTestInstanceBlockAction:
		return "ServerboundTestInstanceBlockAction" // 65 0X41
	case ServerboundBlockPlace:
		return "ServerboundBlockPlace" // 66 0X42
	case ServerboundUseItem:
		return "ServerboundUseItem" // 67 0X43
	case ServerboundCommonCustomClickAction:
		return "ServerboundCommonCustomClickAction" // 68 0X44
	case 69:
		return "ServerboundPacketIDGuard"
	default:
		return fmt.Sprintf("Unknown Serverbound packet ID: %d", id)
	}
}

func NewPackets() Packets {
	return Packets{}
}

// Login ClientBound
const (
	LoginClientboundDisconnect          models.ClientboundPacketID = 0 // 0 0X00
	LoginClientboundEncryptionBegin     models.ClientboundPacketID = 1 // 1 0X01
	LoginClientboundSuccess             models.ClientboundPacketID = 2 // 2 0X02
	LoginClientboundCompress            models.ClientboundPacketID = 3 // 3 0X03
	LoginClientboundLoginPluginRequest  models.ClientboundPacketID = 4 // 4 0X04
	LoginClientboundCommonCookieRequest models.ClientboundPacketID = 5 // 5 0X05
	LoginClientboundPacketIDGuard       models.ClientboundPacketID = 6
)

// Login Serverbound
const (
	LoginServerboundLoginStart           models.ServerboundPacketID = 0 // 0 0X00
	LoginServerboundEncryptionBegin      models.ServerboundPacketID = 1 // 1 0X01
	LoginServerboundLoginPluginResponse  models.ServerboundPacketID = 2 // 2 0X02
	LoginServerboundLoginAcknowledged    models.ServerboundPacketID = 3 // 3 0X03
	LoginServerboundCommonCookieResponse models.ServerboundPacketID = 4 // 4 0X04
	LoginServerboundPacketIDGuard        models.ServerboundPacketID = 5
)

// Status Clientbound
const (
	ClientboundStatusServerInfo    models.ClientboundPacketID = 0 // 0 0X00
	ClientboundStatusPing          models.ClientboundPacketID = 1 // 1 0X01
	ClientboundStatusPacketIDGuard models.ClientboundPacketID = 2
)

// Configuration Clientbound
const (
	ClientboundConfigCommonCookieRequest       models.ClientboundPacketID = 0  // 0 0X00
	ClientboundConfigCustomPayload             models.ClientboundPacketID = 1  // 1 0X01
	ClientboundConfigDisconnect                models.ClientboundPacketID = 2  // 2 0X02
	ClientboundConfigFinishConfiguration       models.ClientboundPacketID = 3  // 3 0X03
	ClientboundConfigKeepAlive                 models.ClientboundPacketID = 4  // 4 0X04
	ClientboundConfigPing                      models.ClientboundPacketID = 5  // 5 0X05
	ClientboundConfigResetChat                 models.ClientboundPacketID = 6  // 6 0X06
	ClientboundConfigRegistryData              models.ClientboundPacketID = 7  // 7 0X07
	ClientboundConfigCommonRemoveResourcePack  models.ClientboundPacketID = 8  // 8 0X08
	ClientboundConfigCommonAddResourcePack     models.ClientboundPacketID = 9  // 9 0X09
	ClientboundConfigCommonStoreCookie         models.ClientboundPacketID = 10 // 10 0X0A
	ClientboundConfigCommonTransfer            models.ClientboundPacketID = 11 // 11 0X0B
	ClientboundConfigFeatureFlags              models.ClientboundPacketID = 12 // 12 0X0C
	ClientboundConfigTags                      models.ClientboundPacketID = 13 // 13 0X0D
	ClientboundConfigCommonSelectKnownPacks    models.ClientboundPacketID = 14 // 14 0X0E
	ClientboundConfigCommonCustomReportDetails models.ClientboundPacketID = 15 // 15 0X0F
	ClientboundConfigCommonServerLinks         models.ClientboundPacketID = 16 // 16 0X10
	ClientboundConfigCommonClearDialog         models.ClientboundPacketID = 17 // 17 0X11
	ClientboundConfigShowDialog                models.ClientboundPacketID = 18 // 18 0X12
	ClientboundConfigCodeOfConduct             models.ClientboundPacketID = 19 // 19 0X13
	ClientboundConfigPacketIDGuard             models.ClientboundPacketID = 20
)

// Configuration Serverbound
const (
	ServerboundConfigCommonSettings          models.ServerboundPacketID = 0 // 0 0X00
	ServerboundConfigCommonCookieResponse    models.ServerboundPacketID = 1 // 1 0X01
	ServerboundConfigCustomPayload           models.ServerboundPacketID = 2 // 2 0X02
	ServerboundConfigFinishConfiguration     models.ServerboundPacketID = 3 // 3 0X03
	ServerboundConfigKeepAlive               models.ServerboundPacketID = 4 // 4 0X04
	ServerboundConfigPong                    models.ServerboundPacketID = 5 // 5 0X05
	ServerboundConfigResourcePackReceive     models.ServerboundPacketID = 6 // 6 0X06
	ServerboundConfigCommonSelectKnownPacks  models.ServerboundPacketID = 7 // 7 0X07
	ServerboundConfigCommonCustomClickAction models.ServerboundPacketID = 8 // 8 0X08
	ServerboundConfigAcceptCodeOfConduct     models.ServerboundPacketID = 9 // 9 0X09
	ServerboundConfigPacketIDGuard           models.ServerboundPacketID = 10
)

// Game Play Clientbound
const (
	ClientboundVoid                       models.ClientboundPacketID = 0   // 0 0X00
	ClientboundSpawnEntity                models.ClientboundPacketID = 1   // 1 0X01
	ClientboundAnimation                  models.ClientboundPacketID = 2   // 2 0X02
	ClientboundStatistics                 models.ClientboundPacketID = 3   // 3 0X03
	ClientboundAcknowledgePlayerDigging   models.ClientboundPacketID = 4   // 4 0X04
	ClientboundBlockBreakAnimation        models.ClientboundPacketID = 5   // 5 0X05
	ClientboundTileEntityData             models.ClientboundPacketID = 6   // 6 0X06
	ClientboundBlockAction                models.ClientboundPacketID = 7   // 7 0X07
	ClientboundBlockChange                models.ClientboundPacketID = 8   // 8 0X08
	ClientboundBossBar                    models.ClientboundPacketID = 9   // 9 0X09
	ClientboundDifficulty                 models.ClientboundPacketID = 10  // 10 0X0A
	ClientboundChunkBatchFinished         models.ClientboundPacketID = 11  // 11 0X0B
	ClientboundChunkBatchStart            models.ClientboundPacketID = 12  // 12 0X0C
	ClientboundChunkBiomes                models.ClientboundPacketID = 13  // 13 0X0D
	ClientboundClearTitles                models.ClientboundPacketID = 14  // 14 0X0E
	ClientboundTabComplete                models.ClientboundPacketID = 15  // 15 0X0F
	ClientboundDeclareCommands            models.ClientboundPacketID = 16  // 16 0X10
	ClientboundCloseWindow                models.ClientboundPacketID = 17  // 17 0X11
	ClientboundWindowItems                models.ClientboundPacketID = 18  // 18 0X12
	ClientboundCraftProgressBar           models.ClientboundPacketID = 19  // 19 0X13
	ClientboundSetSlot                    models.ClientboundPacketID = 20  // 20 0X14
	ClientboundCommonCookieRequest        models.ClientboundPacketID = 21  // 21 0X15
	ClientboundSetCooldown                models.ClientboundPacketID = 22  // 22 0X16
	ClientboundChatSuggestions            models.ClientboundPacketID = 23  // 23 0X17
	ClientboundCustomPayload              models.ClientboundPacketID = 24  // 24 0X18
	ClientboundDamageEvent                models.ClientboundPacketID = 25  // 25 0X19
	ClientboundDebugBlockValue            models.ClientboundPacketID = 26  // 26 0X1A
	ClientboundDebugChunkValue            models.ClientboundPacketID = 27  // 27 0X1B
	ClientboundDebugEntityValue           models.ClientboundPacketID = 28  // 28 0X1C
	ClientboundDebugEvent                 models.ClientboundPacketID = 29  // 29 0X1D
	ClientboundDebugSample                models.ClientboundPacketID = 30  // 30 0X1E
	ClientboundHideMessage                models.ClientboundPacketID = 31  // 31 0X1F
	ClientboundKickDisconnect             models.ClientboundPacketID = 32  // 32 0X20
	ClientboundProfilelessChat            models.ClientboundPacketID = 33  // 33 0X21
	ClientboundEntityStatus               models.ClientboundPacketID = 34  // 34 0X22
	ClientboundSyncEntityPosition         models.ClientboundPacketID = 35  // 35 0X23
	ClientboundExplosion                  models.ClientboundPacketID = 36  // 36 0X24
	ClientboundUnloadChunk                models.ClientboundPacketID = 37  // 37 0X25
	ClientboundGameStateChange            models.ClientboundPacketID = 38  // 38 0X26
	ClientboundGameRuleValues             models.ClientboundPacketID = 39  // 39 0X27
	ClientboundGameTestHighlightPos       models.ClientboundPacketID = 40  // 40 0X28
	ClientboundOpenHorseWindow            models.ClientboundPacketID = 41  // 41 0X29
	ClientboundHurtAnimation              models.ClientboundPacketID = 42  // 42 0X2A
	ClientboundInitializeWorldBorder      models.ClientboundPacketID = 43  // 43 0X2B
	ClientboundKeepAlive                  models.ClientboundPacketID = 44  // 44 0X2C
	ClientboundMapChunk                   models.ClientboundPacketID = 45  // 45 0X2D
	ClientboundWorldEvent                 models.ClientboundPacketID = 46  // 46 0X2E
	ClientboundWorldParticles             models.ClientboundPacketID = 47  // 47 0X2F
	ClientboundUpdateLight                models.ClientboundPacketID = 48  // 48 0X30
	ClientboundLogin                      models.ClientboundPacketID = 49  // 49 0X31
	ClientboundLowDiskSpaceWarning        models.ClientboundPacketID = 50  // 50 0X32
	ClientboundMap                        models.ClientboundPacketID = 51  // 51 0X33
	ClientboundTradeList                  models.ClientboundPacketID = 52  // 52 0X34
	ClientboundRelEntityMove              models.ClientboundPacketID = 53  // 53 0X35
	ClientboundEntityMoveLook             models.ClientboundPacketID = 54  // 54 0X36
	ClientboundMoveMinecart               models.ClientboundPacketID = 55  // 55 0X37
	ClientboundEntityLook                 models.ClientboundPacketID = 56  // 56 0X38
	ClientboundVehicleMove                models.ClientboundPacketID = 57  // 57 0X39
	ClientboundOpenBook                   models.ClientboundPacketID = 58  // 58 0X3A
	ClientboundOpenWindow                 models.ClientboundPacketID = 59  // 59 0X3B
	ClientboundOpenSignEntity             models.ClientboundPacketID = 60  // 60 0X3C
	ClientboundPing                       models.ClientboundPacketID = 61  // 61 0X3D
	ClientboundPingResponse               models.ClientboundPacketID = 62  // 62 0X3E
	ClientboundCraftRecipeResponse        models.ClientboundPacketID = 63  // 63 0X3F
	ClientboundAbilities                  models.ClientboundPacketID = 64  // 64 0X40
	ClientboundPlayerChat                 models.ClientboundPacketID = 65  // 65 0X41
	ClientboundEndCombatEvent             models.ClientboundPacketID = 66  // 66 0X42
	ClientboundEnterCombatEvent           models.ClientboundPacketID = 67  // 67 0X43
	ClientboundDeathCombatEvent           models.ClientboundPacketID = 68  // 68 0X44
	ClientboundPlayerRemove               models.ClientboundPacketID = 69  // 69 0X45
	ClientboundPlayerInfo                 models.ClientboundPacketID = 70  // 70 0X46
	ClientboundFacePlayer                 models.ClientboundPacketID = 71  // 71 0X47
	ClientboundPosition                   models.ClientboundPacketID = 72  // 72 0X48
	ClientboundPlayerRotation             models.ClientboundPacketID = 73  // 73 0X49
	ClientboundRecipeBookAdd              models.ClientboundPacketID = 74  // 74 0X4A
	ClientboundRecipeBookRemove           models.ClientboundPacketID = 75  // 75 0X4B
	ClientboundRecipeBookSettings         models.ClientboundPacketID = 76  // 76 0X4C
	ClientboundEntityDestroy              models.ClientboundPacketID = 77  // 77 0X4D
	ClientboundRemoveEntityEffect         models.ClientboundPacketID = 78  // 78 0X4E
	ClientboundResetScore                 models.ClientboundPacketID = 79  // 79 0X4F
	ClientboundCommonRemoveResourcePack   models.ClientboundPacketID = 80  // 80 0X50
	ClientboundCommonAddResourcePack      models.ClientboundPacketID = 81  // 81 0X51
	ClientboundRespawn                    models.ClientboundPacketID = 82  // 82 0X52
	ClientboundEntityHeadRotation         models.ClientboundPacketID = 83  // 83 0X53
	ClientboundMultiBlockChange           models.ClientboundPacketID = 84  // 84 0X54
	ClientboundSelectAdvancementTab       models.ClientboundPacketID = 85  // 85 0X55
	ClientboundServerData                 models.ClientboundPacketID = 86  // 86 0X56
	ClientboundActionBar                  models.ClientboundPacketID = 87  // 87 0X57
	ClientboundWorldBorderCenter          models.ClientboundPacketID = 88  // 88 0X58
	ClientboundWorldBorderLerpSize        models.ClientboundPacketID = 89  // 89 0X59
	ClientboundWorldBorderSize            models.ClientboundPacketID = 90  // 90 0X5A
	ClientboundWorldBorderWarningDelay    models.ClientboundPacketID = 91  // 91 0X5B
	ClientboundWorldBorderWarningReach    models.ClientboundPacketID = 92  // 92 0X5C
	ClientboundCamera                     models.ClientboundPacketID = 93  // 93 0X5D
	ClientboundUpdateViewPosition         models.ClientboundPacketID = 94  // 94 0X5E
	ClientboundUpdateViewDistance         models.ClientboundPacketID = 95  // 95 0X5F
	ClientboundSetCursorItem              models.ClientboundPacketID = 96  // 96 0X60
	ClientboundSpawnPosition              models.ClientboundPacketID = 97  // 97 0X61
	ClientboundScoreboardDisplayObjective models.ClientboundPacketID = 98  // 98 0X62
	ClientboundEntityMetadata             models.ClientboundPacketID = 99  // 99 0X63
	ClientboundAttachEntity               models.ClientboundPacketID = 100 // 100 0X64
	ClientboundEntityVelocity             models.ClientboundPacketID = 101 // 101 0X65
	ClientboundEntityEquipment            models.ClientboundPacketID = 102 // 102 0X66
	ClientboundExperience                 models.ClientboundPacketID = 103 // 103 0X67
	ClientboundUpdateHealth               models.ClientboundPacketID = 104 // 104 0X68
	ClientboundHeldItemSlot               models.ClientboundPacketID = 105 // 105 0X69
	ClientboundScoreboardObjective        models.ClientboundPacketID = 106 // 106 0X6A
	ClientboundSetPassengers              models.ClientboundPacketID = 107 // 107 0X6B
	ClientboundSetPlayerInventory         models.ClientboundPacketID = 108 // 108 0X6C
	ClientboundTeams                      models.ClientboundPacketID = 109 // 109 0X6D
	ClientboundScoreboardScore            models.ClientboundPacketID = 110 // 110 0X6E
	ClientboundSimulationDistance         models.ClientboundPacketID = 111 // 111 0X6F
	ClientboundSetTitleSubtitle           models.ClientboundPacketID = 112 // 112 0X70
	ClientboundUpdateTime                 models.ClientboundPacketID = 113 // 113 0X71
	ClientboundSetTitleText               models.ClientboundPacketID = 114 // 114 0X72
	ClientboundSetTitleTime               models.ClientboundPacketID = 115 // 115 0X73
	ClientboundEntitySoundEffect          models.ClientboundPacketID = 116 // 116 0X74
	ClientboundSoundEffect                models.ClientboundPacketID = 117 // 117 0X75
	ClientboundStartConfiguration         models.ClientboundPacketID = 118 // 118 0X76
	ClientboundStopSound                  models.ClientboundPacketID = 119 // 119 0X77
	ClientboundCommonStoreCookie          models.ClientboundPacketID = 120 // 120 0X78
	ClientboundSystemChat                 models.ClientboundPacketID = 121 // 121 0X79
	ClientboundPlayerlistHeader           models.ClientboundPacketID = 122 // 122 0X7A
	ClientboundNbtQueryResponse           models.ClientboundPacketID = 123 // 123 0X7B
	ClientboundCollect                    models.ClientboundPacketID = 124 // 124 0X7C
	ClientboundEntityTeleport             models.ClientboundPacketID = 125 // 125 0X7D
	ClientboundTestInstanceBlockStatus    models.ClientboundPacketID = 126 // 126 0X7E
	ClientboundSetTickingState            models.ClientboundPacketID = 127 // 127 0X7F
	ClientboundStepTick                   models.ClientboundPacketID = 128 // 128 0X80
	ClientboundCommonTransfer             models.ClientboundPacketID = 129 // 129 0X81
	ClientboundAdvancements               models.ClientboundPacketID = 130 // 130 0X82
	ClientboundEntityUpdateAttributes     models.ClientboundPacketID = 131 // 131 0X83
	ClientboundEntityEffect               models.ClientboundPacketID = 132 // 132 0X84
	ClientboundDeclareRecipes             models.ClientboundPacketID = 133 // 133 0X85
	ClientboundTags                       models.ClientboundPacketID = 134 // 134 0X86
	ClientboundSetProjectilePower         models.ClientboundPacketID = 135 // 135 0X87
	ClientboundCommonCustomReportDetails  models.ClientboundPacketID = 136 // 136 0X88
	ClientboundCommonServerLinks          models.ClientboundPacketID = 137 // 137 0X89
	ClientboundTrackedWaypoint            models.ClientboundPacketID = 138 // 138 0X8A
	ClientboundCommonClearDialog          models.ClientboundPacketID = 139 // 139 0X8B
	ClientboundShowDialog                 models.ClientboundPacketID = 140 // 140 0X8C
	ClientboundPacketIDGuard              models.ClientboundPacketID = 141
)

// Game Play Serverbound
const (
	ServerboundTeleportConfirm            models.ServerboundPacketID = 0  // 0 0X00
	ServerboundAttack                     models.ServerboundPacketID = 1  // 1 0X01
	ServerboundQueryBlockNbt              models.ServerboundPacketID = 2  // 2 0X02
	ServerboundSelectBundleItem           models.ServerboundPacketID = 3  // 3 0X03
	ServerboundSetDifficulty              models.ServerboundPacketID = 4  // 4 0X04
	ServerboundChangeGamemode             models.ServerboundPacketID = 5  // 5 0X05
	ServerboundMessageAcknowledgement     models.ServerboundPacketID = 6  // 6 0X06
	ServerboundChatCommand                models.ServerboundPacketID = 7  // 7 0X07
	ServerboundChatCommandSigned          models.ServerboundPacketID = 8  // 8 0X08
	ServerboundChatMessage                models.ServerboundPacketID = 9  // 9 0X09
	ServerboundChatSessionUpdate          models.ServerboundPacketID = 10 // 10 0X0A
	ServerboundChunkBatchReceived         models.ServerboundPacketID = 11 // 11 0X0B
	ServerboundClientCommand              models.ServerboundPacketID = 12 // 12 0X0C
	ServerboundTickEnd                    models.ServerboundPacketID = 13 // 13 0X0D
	ServerboundCommonSettings             models.ServerboundPacketID = 14 // 14 0X0E
	ServerboundTabComplete                models.ServerboundPacketID = 15 // 15 0X0F
	ServerboundConfigurationAcknowledged  models.ServerboundPacketID = 16 // 16 0X10
	ServerboundEnchantItem                models.ServerboundPacketID = 17 // 17 0X11
	ServerboundWindowClick                models.ServerboundPacketID = 18 // 18 0X12
	ServerboundCloseWindow                models.ServerboundPacketID = 19 // 19 0X13
	ServerboundSetSlotState               models.ServerboundPacketID = 20 // 20 0X14
	ServerboundCommonCookieResponse       models.ServerboundPacketID = 21 // 21 0X15
	ServerboundCustomPayload              models.ServerboundPacketID = 22 // 22 0X16
	ServerboundDebugSubscriptionRequest   models.ServerboundPacketID = 23 // 23 0X17
	ServerboundEditBook                   models.ServerboundPacketID = 24 // 24 0X18
	ServerboundQueryEntityNbt             models.ServerboundPacketID = 25 // 25 0X19
	ServerboundUseEntity                  models.ServerboundPacketID = 26 // 26 0X1A
	ServerboundGenerateStructure          models.ServerboundPacketID = 27 // 27 0X1B
	ServerboundKeepAlive                  models.ServerboundPacketID = 28 // 28 0X1C
	ServerboundLockDifficulty             models.ServerboundPacketID = 29 // 29 0X1D
	ServerboundPosition                   models.ServerboundPacketID = 30 // 30 0X1E
	ServerboundPositionLook               models.ServerboundPacketID = 31 // 31 0X1F
	ServerboundLook                       models.ServerboundPacketID = 32 // 32 0X20
	ServerboundFlying                     models.ServerboundPacketID = 33 // 33 0X21
	ServerboundVehicleMove                models.ServerboundPacketID = 34 // 34 0X22
	ServerboundSteerBoat                  models.ServerboundPacketID = 35 // 35 0X23
	ServerboundPickItemFromBlock          models.ServerboundPacketID = 36 // 36 0X24
	ServerboundPickItemFromEntity         models.ServerboundPacketID = 37 // 37 0X25
	ServerboundPingRequest                models.ServerboundPacketID = 38 // 38 0X26
	ServerboundCraftRecipeRequest         models.ServerboundPacketID = 39 // 39 0X27
	ServerboundAbilities                  models.ServerboundPacketID = 40 // 40 0X28
	ServerboundBlockDig                   models.ServerboundPacketID = 41 // 41 0X29
	ServerboundEntityAction               models.ServerboundPacketID = 42 // 42 0X2A
	ServerboundPlayerInput                models.ServerboundPacketID = 43 // 43 0X2B
	ServerboundPlayerLoaded               models.ServerboundPacketID = 44 // 44 0X2C
	ServerboundPong                       models.ServerboundPacketID = 45 // 45 0X2D
	ServerboundRecipeBook                 models.ServerboundPacketID = 46 // 46 0X2E
	ServerboundDisplayedRecipe            models.ServerboundPacketID = 47 // 47 0X2F
	ServerboundNameItem                   models.ServerboundPacketID = 48 // 48 0X30
	ServerboundResourcePackReceive        models.ServerboundPacketID = 49 // 49 0X31
	ServerboundAdvancementTab             models.ServerboundPacketID = 50 // 50 0X32
	ServerboundSelectTrade                models.ServerboundPacketID = 51 // 51 0X33
	ServerboundSetBeaconEffect            models.ServerboundPacketID = 52 // 52 0X34
	ServerboundHeldItemSlot               models.ServerboundPacketID = 53 // 53 0X35
	ServerboundUpdateCommandBlock         models.ServerboundPacketID = 54 // 54 0X36
	ServerboundUpdateCommandBlockMinecart models.ServerboundPacketID = 55 // 55 0X37
	ServerboundSetCreativeSlot            models.ServerboundPacketID = 56 // 56 0X38
	ServerboundSetGameRule                models.ServerboundPacketID = 57 // 57 0X39
	ServerboundUpdateJigsawBlock          models.ServerboundPacketID = 58 // 58 0X3A
	ServerboundUpdateStructureBlock       models.ServerboundPacketID = 59 // 59 0X3B
	ServerboundSetTestBlock               models.ServerboundPacketID = 60 // 60 0X3C
	ServerboundUpdateSign                 models.ServerboundPacketID = 61 // 61 0X3D
	ServerboundSpectateEntity             models.ServerboundPacketID = 62 // 62 0X3E
	ServerboundArmAnimation               models.ServerboundPacketID = 63 // 63 0X3F
	ServerboundSpectate                   models.ServerboundPacketID = 64 // 64 0X40
	ServerboundTestInstanceBlockAction    models.ServerboundPacketID = 65 // 65 0X41
	ServerboundBlockPlace                 models.ServerboundPacketID = 66 // 66 0X42
	ServerboundUseItem                    models.ServerboundPacketID = 67 // 67 0X43
	ServerboundCommonCustomClickAction    models.ServerboundPacketID = 68 // 68 0X44
	ServerboundPacketIDGuard              models.ServerboundPacketID = 69
)
