// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "diameter",
//	      "type": "f64"
//	    }
//	  ]
//	]
type WorldBorderSize struct {
	packetID int32
	// "f64"
	Diameter pk.Double
}

// NewWorldBorderSize creates a new WorldBorderSize packet with the correct packet ID.
func NewWorldBorderSize() *WorldBorderSize {
	return &WorldBorderSize{packetID: 84}
}

// PacketID returns the protocol ID for this packet type.
func (p *WorldBorderSize) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *WorldBorderSize) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *WorldBorderSize) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Diameter)
}

// Scan deserializes a wire-format packet into this struct.
func (p *WorldBorderSize) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.Diameter)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *WorldBorderSize) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Diameter"] = &p.Diameter
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *WorldBorderSize) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["Diameter"]; ok {
		p.Diameter = *val.(*pk.Double)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetDiameter returns the Diameter field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *WorldBorderSize) GetDiameter() pk.Double {
	return p.Diameter
}

// SetDiameter sets the Diameter field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *WorldBorderSize) SetDiameter(val pk.Double) {
	p.Diameter = val
}

func (t *WorldBorderSize) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Diameter.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Diameter")
	}

	return totalBytes, nil
}

func (t WorldBorderSize) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[WorldBorderSize.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Diameter.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
