// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "warningBlocks",
//	      "type": "varint"
//	    }
//	  ]
//	]
type WorldBorderWarningReach struct {
	packetID int32
	// "varint"
	WarningBlocks pk.VarInt
}

// NewWorldBorderWarningReach creates a new WorldBorderWarningReach packet with the correct packet ID.
func NewWorldBorderWarningReach() *WorldBorderWarningReach {
	return &WorldBorderWarningReach{packetID: 90}
}

// PacketID returns the protocol ID for this packet type.
func (p *WorldBorderWarningReach) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *WorldBorderWarningReach) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *WorldBorderWarningReach) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.WarningBlocks)
}

// Scan deserializes a wire-format packet into this struct.
func (p *WorldBorderWarningReach) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.WarningBlocks)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *WorldBorderWarningReach) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["WarningBlocks"] = &p.WarningBlocks
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *WorldBorderWarningReach) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["WarningBlocks"]; ok {
		p.WarningBlocks = *val.(*pk.VarInt)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetWarningBlocks returns the WarningBlocks field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *WorldBorderWarningReach) GetWarningBlocks() pk.VarInt {
	return p.WarningBlocks
}

// SetWarningBlocks sets the WarningBlocks field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *WorldBorderWarningReach) SetWarningBlocks(val pk.VarInt) {
	p.WarningBlocks = val
}

func (t *WorldBorderWarningReach) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.WarningBlocks.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field WarningBlocks")
	}

	return totalBytes, nil
}

func (t WorldBorderWarningReach) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[WorldBorderWarningReach.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.WarningBlocks.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
