// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"bytes"
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/models"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "team",
//	      "type": "string"
//	    },
//	    {
//	      "name": "mode",
//	      "type": [
//	        "mapper",
//	        {
//	          "type": "i8",
//	          "mappings": {
//	            "0": "add",
//	            "1": "remove",
//	            "2": "change",
//	            "3": "join",
//	            "4": "leave"
//	          }
//	        }
//	      ]
//	    },
//	    {
//	      "anon": true,
//	      "type": [
//	        "switch",
//	        {
//	          "compareTo": "mode",
//	          "fields": {
//	            "add": [
//	              "container",
//	              [
//	                {
//	                  "name": "name",
//	                  "type": "anonymousNbt"
//	                },
//	                {
//	                  "name": "flags",
//	                  "type": [
//	                    "bitflags",
//	                    {
//	                      "type": "u8",
//	                      "flags": [
//	                        "friendly_fire",
//	                        "see_friendly_invisible"
//	                      ]
//	                    }
//	                  ]
//	                },
//	                {
//	                  "name": "nameTagVisibility",
//	                  "type": [
//	                    "mapper",
//	                    {
//	                      "type": "varint",
//	                      "mappings": {
//	                        "0": "always",
//	                        "1": "never",
//	                        "2": "hide_for_other_teams",
//	                        "3": "hide_for_own_team"
//	                      }
//	                    }
//	                  ]
//	                },
//	                {
//	                  "name": "collisionRule",
//	                  "type": [
//	                    "mapper",
//	                    {
//	                      "type": "varint",
//	                      "mappings": {
//	                        "0": "always",
//	                        "1": "never",
//	                        "2": "push_other_teams",
//	                        "3": "push_own_team"
//	                      }
//	                    }
//	                  ]
//	                },
//	                {
//	                  "name": "formatting",
//	                  "type": "varint"
//	                },
//	                {
//	                  "name": "prefix",
//	                  "type": "anonymousNbt"
//	                },
//	                {
//	                  "name": "suffix",
//	                  "type": "anonymousNbt"
//	                }
//	              ]
//	            ],
//	            "change": [
//	              "container",
//	              [
//	                {
//	                  "name": "name",
//	                  "type": "anonymousNbt"
//	                },
//	                {
//	                  "name": "flags",
//	                  "type": [
//	                    "bitflags",
//	                    {
//	                      "type": "u8",
//	                      "flags": [
//	                        "friendly_fire",
//	                        "see_friendly_invisible"
//	                      ]
//	                    }
//	                  ]
//	                },
//	                {
//	                  "name": "nameTagVisibility",
//	                  "type": [
//	                    "mapper",
//	                    {
//	                      "type": "varint",
//	                      "mappings": {
//	                        "0": "always",
//	                        "1": "never",
//	                        "2": "hide_for_other_teams",
//	                        "3": "hide_for_own_team"
//	                      }
//	                    }
//	                  ]
//	                },
//	                {
//	                  "name": "collisionRule",
//	                  "type": [
//	                    "mapper",
//	                    {
//	                      "type": "varint",
//	                      "mappings": {
//	                        "0": "always",
//	                        "1": "never",
//	                        "2": "push_other_teams",
//	                        "3": "push_own_team"
//	                      }
//	                    }
//	                  ]
//	                },
//	                {
//	                  "name": "formatting",
//	                  "type": "varint"
//	                },
//	                {
//	                  "name": "prefix",
//	                  "type": "anonymousNbt"
//	                },
//	                {
//	                  "name": "suffix",
//	                  "type": "anonymousNbt"
//	                }
//	              ]
//	            ]
//	          },
//	          "default": "void"
//	        }
//	      ]
//	    },
//	    {
//	      "name": "players",
//	      "type": [
//	        "switch",
//	        {
//	          "compareTo": "mode",
//	          "fields": {
//	            "add": [
//	              "array",
//	              {
//	                "countType": "varint",
//	                "type": "string"
//	              }
//	            ],
//	            "join": [
//	              "array",
//	              {
//	                "countType": "varint",
//	                "type": "string"
//	              }
//	            ],
//	            "leave": [
//	              "array",
//	              {
//	                "countType": "varint",
//	                "type": "string"
//	              }
//	            ]
//	          },
//	          "default": "void"
//	        }
//	      ]
//	    }
//	  ]
//	]
type Teams struct {
	packetID int32
	// "string"
	Team pk.String
	// [
	//                 "mapper",
	//                 {
	//                   "type": "i8",
	//                   "mappings": {
	//                     "0": "add",
	//                     "1": "remove",
	//                     "2": "change",
	//                     "3": "join",
	//                     "4": "leave"
	//                   }
	//                 }
	//               ]
	Mode TeamsMode
	// [
	//                 "switch",
	//                 {
	//                   "compareTo": "mode",
	//                   "fields": {
	//                     "add": [
	//                       "container",
	//                       [
	//                         {
	//                           "name": "name",
	//                           "type": "anonymousNbt"
	//                         },
	//                         {
	//                           "name": "flags",
	//                           "type": [
	//                             "bitflags",
	//                             {
	//                               "type": "u8",
	//                               "flags": [
	//                                 "friendly_fire",
	//                                 "see_friendly_invisible"
	//                               ]
	//                             }
	//                           ]
	//                         },
	//                         {
	//                           "name": "nameTagVisibility",
	//                           "type": [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "hide_for_other_teams",
	//                                 "3": "hide_for_own_team"
	//                               }
	//                             }
	//                           ]
	//                         },
	//                         {
	//                           "name": "collisionRule",
	//                           "type": [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "push_other_teams",
	//                                 "3": "push_own_team"
	//                               }
	//                             }
	//                           ]
	//                         },
	//                         {
	//                           "name": "formatting",
	//                           "type": "varint"
	//                         },
	//                         {
	//                           "name": "prefix",
	//                           "type": "anonymousNbt"
	//                         },
	//                         {
	//                           "name": "suffix",
	//                           "type": "anonymousNbt"
	//                         }
	//                       ]
	//                     ],
	//                     "change": [
	//                       "container",
	//                       [
	//                         {
	//                           "name": "name",
	//                           "type": "anonymousNbt"
	//                         },
	//                         {
	//                           "name": "flags",
	//                           "type": [
	//                             "bitflags",
	//                             {
	//                               "type": "u8",
	//                               "flags": [
	//                                 "friendly_fire",
	//                                 "see_friendly_invisible"
	//                               ]
	//                             }
	//                           ]
	//                         },
	//                         {
	//                           "name": "nameTagVisibility",
	//                           "type": [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "hide_for_other_teams",
	//                                 "3": "hide_for_own_team"
	//                               }
	//                             }
	//                           ]
	//                         },
	//                         {
	//                           "name": "collisionRule",
	//                           "type": [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "push_other_teams",
	//                                 "3": "push_own_team"
	//                               }
	//                             }
	//                           ]
	//                         },
	//                         {
	//                           "name": "formatting",
	//                           "type": "varint"
	//                         },
	//                         {
	//                           "name": "prefix",
	//                           "type": "anonymousNbt"
	//                         },
	//                         {
	//                           "name": "suffix",
	//                           "type": "anonymousNbt"
	//                         }
	//                       ]
	//                     ]
	//                   },
	//                   "default": "void"
	//                 }
	//               ]
	UnnamedType0001 pk.Field
	// [
	//                 "switch",
	//                 {
	//                   "compareTo": "mode",
	//                   "fields": {
	//                     "add": [
	//                       "array",
	//                       {
	//                         "countType": "varint",
	//                         "type": "string"
	//                       }
	//                     ],
	//                     "join": [
	//                       "array",
	//                       {
	//                         "countType": "varint",
	//                         "type": "string"
	//                       }
	//                     ],
	//                     "leave": [
	//                       "array",
	//                       {
	//                         "countType": "varint",
	//                         "type": "string"
	//                       }
	//                     ]
	//                   },
	//                   "default": "void"
	//                 }
	//               ]
	Players pk.Field
}

// NewTeams creates a new Teams packet with the correct packet ID.
func NewTeams() *Teams {
	return &Teams{packetID: 107}
}

// PacketID returns the protocol ID for this packet type.
func (p *Teams) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *Teams) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *Teams) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Team,
		&p.Mode,
		p.UnnamedType0001,
		p.Players)
}

// Scan deserializes a wire-format packet into this struct.
func (p *Teams) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	// This packet has switch fields, so we read fields individually
	r := bytes.NewReader(packet.Data)
	var totalBytes int64
	var bytesRead int64
	var err error
	bytesRead, err = p.Team.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return fmt.Errorf("scanning packet field[Team] error: %w", err)
	}
	bytesRead, err = p.Mode.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return fmt.Errorf("scanning packet field[Mode] error: %w", err)
	}
	// Switch field UnnamedType0001 based on mode
	// Convert compareTo value to string for matching
	compareValueUnnamedType0001 := p.Mode.Value

	switch compareValueUnnamedType0001 {
	case "add":
		var val TeamsUnnamedType0001Add
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "scanning packet field[UnnamedType0001] case add")
		}
		p.UnnamedType0001 = &val
	case "change":
		var val TeamsUnnamedType0001Change
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "scanning packet field[UnnamedType0001] case change")
		}
		p.UnnamedType0001 = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "failed to read void switch field UnnamedType0001 default case")
		}
		p.UnnamedType0001 = &__void
	}

	// Switch field Players based on mode
	// Convert compareTo value to string for matching
	compareValuePlayers := p.Mode.Value

	switch compareValuePlayers {
	case "add":
		var val TeamsPlayersAdd
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "scanning packet field[Players] case add")
		}
		p.Players = &val
	case "join":
		var val TeamsPlayersJoin
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "scanning packet field[Players] case join")
		}
		p.Players = &val
	case "leave":
		var val TeamsPlayersLeave
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "scanning packet field[Players] case leave")
		}
		p.Players = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "failed to read void switch field Players default case")
		}
		p.Players = &__void
	}

	_ = totalBytes // Unused in Scan()
	return nil
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *Teams) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Team"] = &p.Team
	fields["Mode"] = &p.Mode
	fields["UnnamedType0001"] = p.UnnamedType0001
	fields["Players"] = p.Players
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *Teams) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["Team"]; ok {
		p.Team = *val.(*pk.String)
	}
	if val, ok := fields["Mode"]; ok {
		p.Mode = *val.(*TeamsMode)
	}
	if val, ok := fields["UnnamedType0001"]; ok {
		p.UnnamedType0001 = val.(pk.Field)
	}
	if val, ok := fields["Players"]; ok {
		p.Players = val.(pk.Field)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetTeam returns the Team field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Teams) GetTeam() pk.String {
	return p.Team
}

// SetTeam sets the Team field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Teams) SetTeam(val pk.String) {
	p.Team = val
}

// GetMode returns the Mode field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Teams) GetMode() TeamsMode {
	return p.Mode
}

// SetMode sets the Mode field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Teams) SetMode(val TeamsMode) {
	p.Mode = val
}

// GetUnnamedType0001 returns the UnnamedType0001 field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Teams) GetUnnamedType0001() pk.Field {
	return p.UnnamedType0001
}

// SetUnnamedType0001 sets the UnnamedType0001 field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Teams) SetUnnamedType0001(val pk.Field) {
	p.UnnamedType0001 = val
}

// GetPlayers returns the Players field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Teams) GetPlayers() pk.Field {
	return p.Players
}

// SetPlayers sets the Players field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Teams) SetPlayers(val pk.Field) {
	p.Players = val
}

func (t *Teams) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Team.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Team")
	}
	bytesRead, err = t.Mode.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Mode")
	}
	// Switch field UnnamedType0001 based on mode
	// Convert compareTo value to string for matching
	compareValueUnnamedType0001 := t.Mode.Value

	switch compareValueUnnamedType0001 {
	case "add":
		var val TeamsUnnamedType0001Add
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read switch field UnnamedType0001 case add")
		}
		t.UnnamedType0001 = &val
	case "change":
		var val TeamsUnnamedType0001Change
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read switch field UnnamedType0001 case change")
		}
		t.UnnamedType0001 = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read void switch field UnnamedType0001 default case")
		}
		t.UnnamedType0001 = &__void
	}

	// Switch field Players based on mode
	// Convert compareTo value to string for matching
	compareValuePlayers := t.Mode.Value

	switch compareValuePlayers {
	case "add":
		var val TeamsPlayersAdd
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read switch field Players case add")
		}
		t.Players = &val
	case "join":
		var val TeamsPlayersJoin
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read switch field Players case join")
		}
		t.Players = &val
	case "leave":
		var val TeamsPlayersLeave
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read switch field Players case leave")
		}
		t.Players = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read void switch field Players default case")
		}
		t.Players = &__void
	}

	return totalBytes, nil
}

func (t Teams) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[Teams.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Team.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Mode.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	// Switch field UnnamedType0001 based on mode
	if t.UnnamedType0001 != nil {
		// Write switch field value if it implements WriteTo
		if writer, ok := t.UnnamedType0001.(interface {
			WriteTo(io.Writer) (int64, error)
		}); ok {
			bytesWritten, err = writer.WriteTo(w)
			totalBytes += bytesWritten
			if err != nil {
				return totalBytes, err
			}
		} else {
			// Not a void case and doesn't implement WriteTo
			return totalBytes, fmt.Errorf("switch field UnnamedType0001 value does not implement WriteTo: %T", t.UnnamedType0001)
		}
	}
	// Switch field Players based on mode
	if t.Players != nil {
		// Write switch field value if it implements WriteTo
		if writer, ok := t.Players.(interface {
			WriteTo(io.Writer) (int64, error)
		}); ok {
			bytesWritten, err = writer.WriteTo(w)
			totalBytes += bytesWritten
			if err != nil {
				return totalBytes, err
			}
		} else {
			// Not a void case and doesn't implement WriteTo
			return totalBytes, fmt.Errorf("switch field Players value does not implement WriteTo: %T", t.Players)
		}
	}
	return totalBytes, nil
}

type TeamsPlayersJoin = models.Array[pk.VarInt, pk.String]

type TeamsPlayersLeave = models.Array[pk.VarInt, pk.String]

// TeamsUnnamedType0001AddFlagsBitflags provides named accessors over a bitflag field.
type TeamsUnnamedType0001AddFlagsBitflags struct {
	pk.UnsignedByte
}

func (bf TeamsUnnamedType0001AddFlagsBitflags) FriendlyFire() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 0)) != 0
}

func (bf *TeamsUnnamedType0001AddFlagsBitflags) SetFriendlyFire(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 0)
	} else {
		v &^= (1 << 0)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
func (bf TeamsUnnamedType0001AddFlagsBitflags) SeeFriendlyInvisible() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 1)) != 0
}

func (bf *TeamsUnnamedType0001AddFlagsBitflags) SetSeeFriendlyInvisible(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 1)
	} else {
		v &^= (1 << 1)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "name",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "flags",
//	      "type": [
//	        "bitflags",
//	        {
//	          "type": "u8",
//	          "flags": [
//	            "friendly_fire",
//	            "see_friendly_invisible"
//	          ]
//	        }
//	      ]
//	    },
//	    {
//	      "name": "nameTagVisibility",
//	      "type": [
//	        "mapper",
//	        {
//	          "type": "varint",
//	          "mappings": {
//	            "0": "always",
//	            "1": "never",
//	            "2": "hide_for_other_teams",
//	            "3": "hide_for_own_team"
//	          }
//	        }
//	      ]
//	    },
//	    {
//	      "name": "collisionRule",
//	      "type": [
//	        "mapper",
//	        {
//	          "type": "varint",
//	          "mappings": {
//	            "0": "always",
//	            "1": "never",
//	            "2": "push_other_teams",
//	            "3": "push_own_team"
//	          }
//	        }
//	      ]
//	    },
//	    {
//	      "name": "formatting",
//	      "type": "varint"
//	    },
//	    {
//	      "name": "prefix",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "suffix",
//	      "type": "anonymousNbt"
//	    }
//	  ]
//	]
type TeamsUnnamedType0001Add struct {
	// "anonymousNbt"
	Name models.AnonymousNBT
	// [
	//                             "bitflags",
	//                             {
	//                               "type": "u8",
	//                               "flags": [
	//                                 "friendly_fire",
	//                                 "see_friendly_invisible"
	//                               ]
	//                             }
	//                           ]
	Flags TeamsUnnamedType0001AddFlagsBitflags
	// [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "hide_for_other_teams",
	//                                 "3": "hide_for_own_team"
	//                               }
	//                             }
	//                           ]
	NameTagVisibility TeamsUnnamedType0001AddNameTagVisibility
	// [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "push_other_teams",
	//                                 "3": "push_own_team"
	//                               }
	//                             }
	//                           ]
	CollisionRule TeamsUnnamedType0001AddCollisionRule
	// "varint"
	Formatting pk.VarInt
	// "anonymousNbt"
	Prefix models.AnonymousNBT
	// "anonymousNbt"
	Suffix models.AnonymousNBT
}

func (t *TeamsUnnamedType0001Add) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Name.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Name")
	}
	bytesRead, err = t.Flags.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Flags")
	}
	bytesRead, err = t.NameTagVisibility.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field NameTagVisibility")
	}
	bytesRead, err = t.CollisionRule.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field CollisionRule")
	}
	bytesRead, err = t.Formatting.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Formatting")
	}
	bytesRead, err = t.Prefix.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Prefix")
	}
	bytesRead, err = t.Suffix.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Suffix")
	}

	return totalBytes, nil
}

func (t TeamsUnnamedType0001Add) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[TeamsUnnamedType0001Add.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Name.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Flags.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.NameTagVisibility.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.CollisionRule.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Formatting.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Prefix.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Suffix.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}

// TeamsUnnamedType0001ChangeFlagsBitflags provides named accessors over a bitflag field.
type TeamsUnnamedType0001ChangeFlagsBitflags struct {
	pk.UnsignedByte
}

func (bf TeamsUnnamedType0001ChangeFlagsBitflags) FriendlyFire() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 0)) != 0
}

func (bf *TeamsUnnamedType0001ChangeFlagsBitflags) SetFriendlyFire(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 0)
	} else {
		v &^= (1 << 0)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
func (bf TeamsUnnamedType0001ChangeFlagsBitflags) SeeFriendlyInvisible() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 1)) != 0
}

func (bf *TeamsUnnamedType0001ChangeFlagsBitflags) SetSeeFriendlyInvisible(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 1)
	} else {
		v &^= (1 << 1)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "name",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "flags",
//	      "type": [
//	        "bitflags",
//	        {
//	          "type": "u8",
//	          "flags": [
//	            "friendly_fire",
//	            "see_friendly_invisible"
//	          ]
//	        }
//	      ]
//	    },
//	    {
//	      "name": "nameTagVisibility",
//	      "type": [
//	        "mapper",
//	        {
//	          "type": "varint",
//	          "mappings": {
//	            "0": "always",
//	            "1": "never",
//	            "2": "hide_for_other_teams",
//	            "3": "hide_for_own_team"
//	          }
//	        }
//	      ]
//	    },
//	    {
//	      "name": "collisionRule",
//	      "type": [
//	        "mapper",
//	        {
//	          "type": "varint",
//	          "mappings": {
//	            "0": "always",
//	            "1": "never",
//	            "2": "push_other_teams",
//	            "3": "push_own_team"
//	          }
//	        }
//	      ]
//	    },
//	    {
//	      "name": "formatting",
//	      "type": "varint"
//	    },
//	    {
//	      "name": "prefix",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "suffix",
//	      "type": "anonymousNbt"
//	    }
//	  ]
//	]
type TeamsUnnamedType0001Change struct {
	// "anonymousNbt"
	Name models.AnonymousNBT
	// [
	//                             "bitflags",
	//                             {
	//                               "type": "u8",
	//                               "flags": [
	//                                 "friendly_fire",
	//                                 "see_friendly_invisible"
	//                               ]
	//                             }
	//                           ]
	Flags TeamsUnnamedType0001ChangeFlagsBitflags
	// [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "hide_for_other_teams",
	//                                 "3": "hide_for_own_team"
	//                               }
	//                             }
	//                           ]
	NameTagVisibility TeamsUnnamedType0001ChangeNameTagVisibility
	// [
	//                             "mapper",
	//                             {
	//                               "type": "varint",
	//                               "mappings": {
	//                                 "0": "always",
	//                                 "1": "never",
	//                                 "2": "push_other_teams",
	//                                 "3": "push_own_team"
	//                               }
	//                             }
	//                           ]
	CollisionRule TeamsUnnamedType0001ChangeCollisionRule
	// "varint"
	Formatting pk.VarInt
	// "anonymousNbt"
	Prefix models.AnonymousNBT
	// "anonymousNbt"
	Suffix models.AnonymousNBT
}

func (t *TeamsUnnamedType0001Change) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Name.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Name")
	}
	bytesRead, err = t.Flags.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Flags")
	}
	bytesRead, err = t.NameTagVisibility.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field NameTagVisibility")
	}
	bytesRead, err = t.CollisionRule.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field CollisionRule")
	}
	bytesRead, err = t.Formatting.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Formatting")
	}
	bytesRead, err = t.Prefix.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Prefix")
	}
	bytesRead, err = t.Suffix.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Suffix")
	}

	return totalBytes, nil
}

func (t TeamsUnnamedType0001Change) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[TeamsUnnamedType0001Change.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Name.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Flags.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.NameTagVisibility.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.CollisionRule.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Formatting.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Prefix.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Suffix.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}

type TeamsPlayersAdd = models.Array[pk.VarInt, pk.String]
