// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "protocolVersion",
//	      "type": "varint"
//	    },
//	    {
//	      "name": "serverHost",
//	      "type": "string"
//	    },
//	    {
//	      "name": "serverPort",
//	      "type": "u16"
//	    },
//	    {
//	      "name": "nextState",
//	      "type": "varint"
//	    }
//	  ]
//	]
type SetProtocol struct {
	packetID int32
	// "varint"
	ProtocolVersion pk.VarInt
	// "string"
	ServerHost pk.String
	// "u16"
	ServerPort pk.UnsignedShort
	// "varint"
	NextState pk.VarInt
}

// NewSetProtocol creates a new SetProtocol packet with the correct packet ID.
func NewSetProtocol() *SetProtocol {
	return &SetProtocol{packetID: 0}
}

// PacketID returns the protocol ID for this packet type.
func (p *SetProtocol) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *SetProtocol) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *SetProtocol) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.ProtocolVersion,
		&p.ServerHost,
		&p.ServerPort,
		&p.NextState)
}

// Scan deserializes a wire-format packet into this struct.
func (p *SetProtocol) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.ProtocolVersion,
		&p.ServerHost,
		&p.ServerPort,
		&p.NextState)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *SetProtocol) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["ProtocolVersion"] = p.ProtocolVersion
	fields["ServerHost"] = p.ServerHost
	fields["ServerPort"] = p.ServerPort
	fields["NextState"] = p.NextState
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *SetProtocol) SetFields(fields map[string]pk.FieldEncoder) {
	fmt.Printf("<no value>\n")
	if val, ok := fields["ProtocolVersion"]; ok {
		p.ProtocolVersion = val.(pk.VarInt)
	}
	if val, ok := fields["ServerHost"]; ok {
		p.ServerHost = val.(pk.String)
	}
	if val, ok := fields["ServerPort"]; ok {
		p.ServerPort = val.(pk.UnsignedShort)
	}
	if val, ok := fields["NextState"]; ok {
		p.NextState = val.(pk.VarInt)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetProtocolVersion returns the ProtocolVersion field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SetProtocol) GetProtocolVersion() pk.VarInt {
	return p.ProtocolVersion
}

// SetProtocolVersion sets the ProtocolVersion field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SetProtocol) SetProtocolVersion(val pk.VarInt) {
	p.ProtocolVersion = val
}

// GetServerHost returns the ServerHost field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SetProtocol) GetServerHost() pk.String {
	return p.ServerHost
}

// SetServerHost sets the ServerHost field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SetProtocol) SetServerHost(val pk.String) {
	p.ServerHost = val
}

// GetServerPort returns the ServerPort field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SetProtocol) GetServerPort() pk.UnsignedShort {
	return p.ServerPort
}

// SetServerPort sets the ServerPort field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SetProtocol) SetServerPort(val pk.UnsignedShort) {
	p.ServerPort = val
}

// GetNextState returns the NextState field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SetProtocol) GetNextState() pk.VarInt {
	return p.NextState
}

// SetNextState sets the NextState field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SetProtocol) SetNextState(val pk.VarInt) {
	p.NextState = val
}

func (t *SetProtocol) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.ProtocolVersion.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field ProtocolVersion")
	}
	bytesRead, err = t.ServerHost.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field ServerHost")
	}
	bytesRead, err = t.ServerPort.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field ServerPort")
	}
	bytesRead, err = t.NextState.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field NextState")
	}

	return totalBytes, nil
}

func (t SetProtocol) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[SetProtocol.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.ProtocolVersion.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.ServerHost.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.ServerPort.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.NextState.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
