// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/models"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "text",
//	      "type": "anonymousNbt"
//	    }
//	  ]
//	]
type SetTitleText struct {
	packetID int32
	// "anonymousNbt"
	Text models.AnonymousNBT
}

// NewSetTitleText creates a new SetTitleText packet with the correct packet ID.
func NewSetTitleText() *SetTitleText {
	return &SetTitleText{packetID: 107}
}

// PacketID returns the protocol ID for this packet type.
func (p *SetTitleText) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *SetTitleText) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *SetTitleText) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Text)
}

// Scan deserializes a wire-format packet into this struct.
func (p *SetTitleText) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.Text)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *SetTitleText) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Text"] = &p.Text
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *SetTitleText) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["Text"]; ok {
		p.Text = *val.(*models.AnonymousNBT)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetText returns the Text field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SetTitleText) GetText() models.AnonymousNBT {
	return p.Text
}

// SetText sets the Text field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SetTitleText) SetText(val models.AnonymousNBT) {
	p.Text = val
}

func (t *SetTitleText) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Text.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Text")
	}

	return totalBytes, nil
}

func (t SetTitleText) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[SetTitleText.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Text.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
