// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "yaw",
//	      "type": "f32"
//	    },
//	    {
//	      "name": "pitch",
//	      "type": "f32"
//	    },
//	    {
//	      "name": "flags",
//	      "type": "MovementFlags"
//	    }
//	  ]
//	]
type Look struct {
	packetID int32
	// "f32"
	Yaw pk.Float
	// "f32"
	Pitch pk.Float
	// "MovementFlags"
	Flags MovementFlags
}

// NewLook creates a new Look packet with the correct packet ID.
func NewLook() *Look {
	return &Look{packetID: 30}
}

// PacketID returns the protocol ID for this packet type.
func (p *Look) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *Look) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *Look) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Yaw,
		&p.Pitch,
		&p.Flags)
}

// Scan deserializes a wire-format packet into this struct.
func (p *Look) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.Yaw,
		&p.Pitch,
		&p.Flags)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *Look) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Yaw"] = &p.Yaw
	fields["Pitch"] = &p.Pitch
	fields["Flags"] = &p.Flags
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *Look) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["Yaw"]; ok {
		p.Yaw = *val.(*pk.Float)
	}
	if val, ok := fields["Pitch"]; ok {
		p.Pitch = *val.(*pk.Float)
	}
	if val, ok := fields["Flags"]; ok {
		p.Flags = *val.(*MovementFlags)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetYaw returns the Yaw field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Look) GetYaw() pk.Float {
	return p.Yaw
}

// SetYaw sets the Yaw field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Look) SetYaw(val pk.Float) {
	p.Yaw = val
}

// GetPitch returns the Pitch field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Look) GetPitch() pk.Float {
	return p.Pitch
}

// SetPitch sets the Pitch field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Look) SetPitch(val pk.Float) {
	p.Pitch = val
}

// GetFlags returns the Flags field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *Look) GetFlags() MovementFlags {
	return p.Flags
}

// SetFlags sets the Flags field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *Look) SetFlags(val MovementFlags) {
	p.Flags = val
}

func (t *Look) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Yaw.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Yaw")
	}
	bytesRead, err = t.Pitch.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Pitch")
	}
	bytesRead, err = t.Flags.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Flags")
	}

	return totalBytes, nil
}

func (t Look) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[Look.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Yaw.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Pitch.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Flags.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
