// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
)

type PacketName struct {
	Value string
}

var PacketNameMappings = map[int64]string{
	0x00: "cookie_request",
	0x01: "custom_payload",
	0x02: "disconnect",
	0x03: "finish_configuration",
	0x04: "keep_alive",
	0x05: "ping",
	0x06: "reset_chat",
	0x07: "registry_data",
	0x08: "remove_resource_pack",
	0x09: "add_resource_pack",
	0x0a: "store_cookie",
	0x0b: "transfer",
	0x0c: "feature_flags",
	0x0d: "tags",
	0x0e: "select_known_packs",
	0x0f: "custom_report_details",
	0x10: "server_links",
	0x11: "clear_dialog",
	0x12: "show_dialog",
}

func (m *PacketName) ReadFrom(r io.Reader) (int64, error) {
	var key pk.VarInt
	n, err := key.ReadFrom(r)
	if err != nil {
		return n, errors.Wrap(err, "failed to read PacketName key")
	}

	value, ok := PacketNameMappings[int64(key)]
	if !ok {
		// Use numeric key as fallback for unknown/undocumented values
		m.Value = fmt.Sprintf("unknown_%d", key)
		return n, nil
	}
	m.Value = value
	return n, nil
}

func (m PacketName) WriteTo(w io.Writer) (int64, error) {
	for k, v := range PacketNameMappings {
		if v == m.Value {
			key := pk.VarInt(k)
			return key.WriteTo(w)
		}
	}
	return 0, errors.Errorf("unknown PacketName value: '%s'", m.Value)
}
