// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/data/1.21.8/basetypes"
	"github.com/reallyoldfogie/mc-protocol-go/models"
	"io"
	"log"
)

// MovementFlags provides named accessors over a bitflag field.
type MovementFlags struct {
	pk.UnsignedByte
}

func (bf MovementFlags) OnGround() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 0)) != 0
}

func (bf *MovementFlags) SetOnGround(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 0)
	} else {
		v &^= (1 << 0)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}
func (bf MovementFlags) HasHorizontalCollision() bool {
	v := uint64(uint8(bf.UnsignedByte))
	return (v & (1 << 1)) != 0
}

func (bf *MovementFlags) SetHasHorizontalCollision(value bool) {
	v := uint8(bf.UnsignedByte)
	if value {
		v |= (1 << 1)
	} else {
		v &^= (1 << 1)
	}
	bf.UnsignedByte = pk.UnsignedByte(v)
}

type TestInstanceBlockActionDataTest models.Option[pk.String]

func (t *TestInstanceBlockActionDataTest) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[pk.String])(t).ReadFrom(r)
}

func (t TestInstanceBlockActionDataTest) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[pk.String])(t).WriteTo(w)
}

type TestInstanceBlockActionDataErrorMessage models.Option[models.AnonymousNBT]

func (t *TestInstanceBlockActionDataErrorMessage) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[models.AnonymousNBT])(t).ReadFrom(r)
}

func (t TestInstanceBlockActionDataErrorMessage) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[models.AnonymousNBT])(t).WriteTo(w)
}

type SetBeaconEffectPrimaryEffect models.Option[pk.VarInt]

func (t *SetBeaconEffectPrimaryEffect) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[pk.VarInt])(t).ReadFrom(r)
}

func (t SetBeaconEffectPrimaryEffect) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[pk.VarInt])(t).WriteTo(w)
}

type SetBeaconEffectSecondaryEffect models.Option[pk.VarInt]

func (t *SetBeaconEffectSecondaryEffect) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[pk.VarInt])(t).ReadFrom(r)
}

func (t SetBeaconEffectSecondaryEffect) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[pk.VarInt])(t).WriteTo(w)
}

type WindowClickChangedSlotsArrayTypeItem models.Option[basetypes.HashedSlot]

func (t *WindowClickChangedSlotsArrayTypeItem) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[basetypes.HashedSlot])(t).ReadFrom(r)
}

func (t WindowClickChangedSlotsArrayTypeItem) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[basetypes.HashedSlot])(t).WriteTo(w)
}

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "location",
//	      "type": "i16"
//	    },
//	    {
//	      "name": "item",
//	      "type": [
//	        "option",
//	        "HashedSlot"
//	      ]
//	    }
//	  ]
//	]
type WindowClickChangedSlotsArrayType struct {
	// "i16"
	Location pk.Short
	// [
	//                           "option",
	//                           "HashedSlot"
	//                         ]
	Item models.Option[basetypes.HashedSlot]
}

func (t *WindowClickChangedSlotsArrayType) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Location.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Location")
	}
	bytesRead, err = t.Item.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Item")
	}

	return totalBytes, nil
}

func (t WindowClickChangedSlotsArrayType) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[WindowClickChangedSlotsArrayType.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Location.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Item.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}

type WindowClickCursorItem models.Option[basetypes.HashedSlot]

func (t *WindowClickCursorItem) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[basetypes.HashedSlot])(t).ReadFrom(r)
}

func (t WindowClickCursorItem) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[basetypes.HashedSlot])(t).WriteTo(w)
}

type EditBookTitle models.Option[pk.String]

func (t *EditBookTitle) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[pk.String])(t).ReadFrom(r)
}

func (t EditBookTitle) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[pk.String])(t).WriteTo(w)
}

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "argumentName",
//	      "type": "string"
//	    },
//	    {
//	      "name": "signature",
//	      "type": [
//	        "buffer",
//	        {
//	          "count": 256
//	        }
//	      ]
//	    }
//	  ]
//	]
type ChatCommandSignedArgumentSignaturesArrayType struct {
	// "string"
	ArgumentName pk.String
	// [
	//                           "buffer",
	//                           {
	//                             "count": 256
	//                           }
	//                         ]
	Signature models.FixedBuffer256
}

func (t *ChatCommandSignedArgumentSignaturesArrayType) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.ArgumentName.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field ArgumentName")
	}
	bytesRead, err = t.Signature.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Signature")
	}

	return totalBytes, nil
}

func (t ChatCommandSignedArgumentSignaturesArrayType) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[ChatCommandSignedArgumentSignaturesArrayType.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.ArgumentName.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Signature.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}

type ChatMessageSignature models.Option[models.FixedBuffer256]

func (t *ChatMessageSignature) ReadFrom(r io.Reader) (int64, error) {
	return (*models.Option[models.FixedBuffer256])(t).ReadFrom(r)
}

func (t ChatMessageSignature) WriteTo(w io.Writer) (int64, error) {
	return (models.Option[models.FixedBuffer256])(t).WriteTo(w)
}
