// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/models"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "message",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "type",
//	      "type": "ChatTypesHolder"
//	    },
//	    {
//	      "name": "name",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "target",
//	      "type": [
//	        "option",
//	        "anonymousNbt"
//	      ]
//	    }
//	  ]
//	]
type ProfilelessChat struct {
	packetID int32
	// "anonymousNbt"
	Message models.AnonymousNBT
	// "ChatTypesHolder"
	Type ChatTypesHolder
	// "anonymousNbt"
	Name models.AnonymousNBT
	// [
	//                 "option",
	//                 "anonymousNbt"
	//               ]
	Target models.Option[models.AnonymousNBT]
}

// NewProfilelessChat creates a new ProfilelessChat packet with the correct packet ID.
func NewProfilelessChat() *ProfilelessChat {
	return &ProfilelessChat{packetID: 30}
}

// PacketID returns the protocol ID for this packet type.
func (p *ProfilelessChat) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *ProfilelessChat) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *ProfilelessChat) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Message,
		&p.Type,
		&p.Name,
		&p.Target)
}

// Scan deserializes a wire-format packet into this struct.
func (p *ProfilelessChat) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.Message,
		&p.Type,
		&p.Name,
		&p.Target)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *ProfilelessChat) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Message"] = &p.Message
	fields["Type"] = &p.Type
	fields["Name"] = &p.Name
	fields["Target"] = &p.Target
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *ProfilelessChat) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["Message"]; ok {
		p.Message = *val.(*models.AnonymousNBT)
	}
	if val, ok := fields["Type"]; ok {
		p.Type = *val.(*ChatTypesHolder)
	}
	if val, ok := fields["Name"]; ok {
		p.Name = *val.(*models.AnonymousNBT)
	}
	if val, ok := fields["Target"]; ok {
		p.Target = *val.(*models.Option[models.AnonymousNBT])
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetMessage returns the Message field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *ProfilelessChat) GetMessage() models.AnonymousNBT {
	return p.Message
}

// SetMessage sets the Message field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *ProfilelessChat) SetMessage(val models.AnonymousNBT) {
	p.Message = val
}

// GetType returns the Type field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *ProfilelessChat) GetType() ChatTypesHolder {
	return p.Type
}

// SetType sets the Type field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *ProfilelessChat) SetType(val ChatTypesHolder) {
	p.Type = val
}

// GetName returns the Name field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *ProfilelessChat) GetName() models.AnonymousNBT {
	return p.Name
}

// SetName sets the Name field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *ProfilelessChat) SetName(val models.AnonymousNBT) {
	p.Name = val
}

// GetTarget returns the Target field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *ProfilelessChat) GetTarget() models.Option[models.AnonymousNBT] {
	return p.Target
}

// SetTarget sets the Target field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *ProfilelessChat) SetTarget(val models.Option[models.AnonymousNBT]) {
	p.Target = val
}

func (t *ProfilelessChat) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Message.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Message")
	}
	bytesRead, err = t.Type.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Type")
	}
	bytesRead, err = t.Name.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Name")
	}
	bytesRead, err = t.Target.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Target")
	}

	return totalBytes, nil
}

func (t ProfilelessChat) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[ProfilelessChat.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Message.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Type.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Name.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Target.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
