// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/data/1.21.4/basetypes"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "entityId",
//	      "type": "varint"
//	    },
//	    {
//	      "name": "location",
//	      "type": "position"
//	    },
//	    {
//	      "name": "destroyStage",
//	      "type": "i8"
//	    }
//	  ]
//	]
type BlockBreakAnimation struct {
	packetID int32
	// "varint"
	EntityId pk.VarInt
	// "position"
	Location basetypes.Position
	// "i8"
	DestroyStage pk.Byte
}

// NewBlockBreakAnimation creates a new BlockBreakAnimation packet with the correct packet ID.
func NewBlockBreakAnimation() *BlockBreakAnimation {
	return &BlockBreakAnimation{packetID: 6}
}

// PacketID returns the protocol ID for this packet type.
func (p *BlockBreakAnimation) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *BlockBreakAnimation) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *BlockBreakAnimation) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.EntityId,
		&p.Location,
		&p.DestroyStage)
}

// Scan deserializes a wire-format packet into this struct.
func (p *BlockBreakAnimation) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.EntityId,
		&p.Location,
		&p.DestroyStage)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *BlockBreakAnimation) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["EntityId"] = &p.EntityId
	fields["Location"] = &p.Location
	fields["DestroyStage"] = &p.DestroyStage
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *BlockBreakAnimation) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["EntityId"]; ok {
		p.EntityId = *val.(*pk.VarInt)
	}
	if val, ok := fields["Location"]; ok {
		p.Location = *val.(*basetypes.Position)
	}
	if val, ok := fields["DestroyStage"]; ok {
		p.DestroyStage = *val.(*pk.Byte)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetEntityId returns the EntityId field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *BlockBreakAnimation) GetEntityId() pk.VarInt {
	return p.EntityId
}

// SetEntityId sets the EntityId field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *BlockBreakAnimation) SetEntityId(val pk.VarInt) {
	p.EntityId = val
}

// GetLocation returns the Location field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *BlockBreakAnimation) GetLocation() basetypes.Position {
	return p.Location
}

// SetLocation sets the Location field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *BlockBreakAnimation) SetLocation(val basetypes.Position) {
	p.Location = val
}

// GetDestroyStage returns the DestroyStage field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *BlockBreakAnimation) GetDestroyStage() pk.Byte {
	return p.DestroyStage
}

// SetDestroyStage sets the DestroyStage field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *BlockBreakAnimation) SetDestroyStage(val pk.Byte) {
	p.DestroyStage = val
}

func (t *BlockBreakAnimation) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.EntityId.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field EntityId")
	}
	bytesRead, err = t.Location.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Location")
	}
	bytesRead, err = t.DestroyStage.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field DestroyStage")
	}

	return totalBytes, nil
}

func (t BlockBreakAnimation) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[BlockBreakAnimation.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.EntityId.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Location.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.DestroyStage.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
