// Generated by gen_protocol (baseTypesHeader). DO NOT EDIT
package basetypes

import (
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/reallyoldfogie/mc-protocol-go/models"
)

type ExactComponentMatcher = models.Array[pk.VarInt, SlotComponent]

type U16 = pk.UnsignedShort

type ContainerID = pk.VarInt

type U32 = models.UInt32

type F32 = pk.Float

type SlotComponentDataPiercingWeaponSound = models.Option[ItemSoundHolder]

type SlotComponentDataPiercingWeaponHitSound = models.Option[ItemSoundHolder]

type SlotComponentDataBlocksAttacksDamageReductionsArrayTypeType = models.Option[IDSet]

type SlotComponentDataBlocksAttacksBypassedBy = models.Option[pk.String]

type SlotComponentDataBlocksAttacksBlockSound = models.Option[ItemSoundHolder]

type SlotComponentDataBlocksAttacksDisableSound = models.Option[ItemSoundHolder]

type SlotComponentDataEquippableModel = models.Option[pk.String]

type SlotComponentDataEquippableCameraOverlay = models.Option[pk.String]

type SlotComponentDataEquippableAllowedEntities = models.Option[IDSet]

type SlotComponentDataLore = models.Array[pk.VarInt, models.AnonymousNBT]

type SlotComponentDataToolRulesArrayTypeSpeed = models.Option[pk.Float]

type SlotComponentDataToolRulesArrayTypeCorrectDropForBlocks = models.Option[pk.Boolean]

type SlotComponentDataLodestoneTrackerGlobalPosition = models.Option[GlobalPos]

type SlotComponentDataWrittenBookContentFilteredTitle = models.Option[pk.String]

type SlotComponentDataUseCooldownCooldownGroup = models.Option[pk.String]

type SlotComponentDataKineticWeaponDismountConditions = models.Option[KineticWeaponCondition]

type SlotComponentDataKineticWeaponKnockbackConditions = models.Option[KineticWeaponCondition]

type SlotComponentDataKineticWeaponDamageConditions = models.Option[KineticWeaponCondition]

type SlotComponentDataKineticWeaponSound = models.Option[ItemSoundHolder]

type SlotComponentDataKineticWeaponHitSound = models.Option[ItemSoundHolder]

type SlotComponentDataPotionContentsPotionId = models.Option[pk.VarInt]

type SlotComponentDataPotionContentsCustomColor = models.Option[pk.Int]

type SlotComponentDataPotionContentsCustomName = models.Option[pk.String]

type Ingredient = models.Array[pk.VarInt, Slot]

type PartialResolvableProfileName = models.Option[pk.String]

type PartialResolvableProfileUuid = models.Option[pk.UUID]

type I16 = pk.Short

type U64 = models.UInt64

type F64 = pk.Double

type PreviousMessages = models.Array[pk.VarInt, PreviousMessagesPreviousMessagesElement]

type DebugSubscriptionEventValueBreezesAttackTarget = models.Option[pk.VarInt]

type DebugSubscriptionEventValueBreezesJumpTarget = models.Option[Position]

type DebugSubscriptionEventValueBeesHivePos = models.Option[Position]

type DebugSubscriptionEventValueBeesFlowerPos = models.Option[Position]

type GameProfilePropertySignature = models.Option[pk.String]

type PlayerSkinPatchBody = models.Option[pk.String]

type PlayerSkinPatchCape = models.Option[pk.String]

type PlayerSkinPatchElytra = models.Option[pk.String]

type I8 = pk.Byte

type I32 = pk.Int

type bool = pk.Boolean

type Optvarint = pk.VarInt

type ByteArray = pk.ByteArray

type DebugSubscriptionUpdateUnnamedType0001DefaultPayloadBeesHivePos = models.Option[Position]

type DebugSubscriptionUpdateUnnamedType0001DefaultPayloadBeesFlowerPos = models.Option[Position]

type DebugSubscriptionUpdateUnnamedType0001DefaultPayloadBreezesAttackTarget = models.Option[pk.VarInt]

type DebugSubscriptionUpdateUnnamedType0001DefaultPayloadBreezesJumpTarget = models.Option[Position]

type Varint = pk.VarInt

type I64 = pk.Long

type ChatSession = models.Option[ChatSessionData]
