// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/data/1.21.4/basetypes"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "windowId",
//	      "type": "ContainerID"
//	    }
//	  ]
//	]
type CloseWindow struct {
	packetID int32
	// "ContainerID"
	WindowId basetypes.ContainerID
}

// NewCloseWindow creates a new CloseWindow packet with the correct packet ID.
func NewCloseWindow() *CloseWindow {
	return &CloseWindow{packetID: 17}
}

// PacketID returns the protocol ID for this packet type.
func (p *CloseWindow) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *CloseWindow) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *CloseWindow) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.WindowId)
}

// Scan deserializes a wire-format packet into this struct.
func (p *CloseWindow) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.WindowId)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *CloseWindow) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["WindowId"] = p.WindowId
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *CloseWindow) SetFields(fields map[string]pk.FieldEncoder) {
	fmt.Printf("<no value>\n")
	if val, ok := fields["WindowId"]; ok {
		p.WindowId = val.(basetypes.ContainerID)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetWindowId returns the WindowId field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *CloseWindow) GetWindowId() basetypes.ContainerID {
	return p.WindowId
}

// SetWindowId sets the WindowId field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *CloseWindow) SetWindowId(val basetypes.ContainerID) {
	p.WindowId = val
}

func (t *CloseWindow) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.WindowId.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field WindowId")
	}

	return totalBytes, nil
}

func (t CloseWindow) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[CloseWindow.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.WindowId.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
