// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "slot",
//	      "type": "varint"
//	    }
//	  ]
//	]
type SelectTrade struct {
	packetID int32
	// "varint"
	Slot pk.VarInt
}

// NewSelectTrade creates a new SelectTrade packet with the correct packet ID.
func NewSelectTrade() *SelectTrade {
	return &SelectTrade{packetID: 49}
}

// PacketID returns the protocol ID for this packet type.
func (p *SelectTrade) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *SelectTrade) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *SelectTrade) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Slot)
}

// Scan deserializes a wire-format packet into this struct.
func (p *SelectTrade) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.Slot)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *SelectTrade) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Slot"] = &p.Slot
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *SelectTrade) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["Slot"]; ok {
		p.Slot = *val.(*pk.VarInt)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetSlot returns the Slot field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SelectTrade) GetSlot() pk.VarInt {
	return p.Slot
}

// SetSlot sets the Slot field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SelectTrade) SetSlot(val pk.VarInt) {
	p.Slot = val
}

func (t *SelectTrade) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Slot.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Slot")
	}

	return totalBytes, nil
}

func (t SelectTrade) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[SelectTrade.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Slot.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
