// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"io"
)

// Protodef: [
//
//	  "container",
//	  []
//	]
type LoginAcknowledged struct {
	packetID int32
}

// NewLoginAcknowledged creates a new LoginAcknowledged packet with the correct packet ID.
func NewLoginAcknowledged() *LoginAcknowledged {
	return &LoginAcknowledged{packetID: 3}
}

// PacketID returns the protocol ID for this packet type.
func (p *LoginAcknowledged) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *LoginAcknowledged) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *LoginAcknowledged) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID)
}

// Scan deserializes a wire-format packet into this struct.
func (p *LoginAcknowledged) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan()
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *LoginAcknowledged) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *LoginAcknowledged) SetFields(fields map[string]pk.FieldEncoder) {
}

// Typed field accessor methods for version-specific type-safe access
func (t *LoginAcknowledged) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	return 0, nil
}

func (t LoginAcknowledged) WriteTo(w io.Writer) (totalBytes int64, err error) {
	return 0, nil
}
