// Generated by gen_protocol (packetMgr) DO NOT EDIT
package v1_21_5

import (
	"fmt"

	"github.com/reallyoldfogie/mc-protocol-go/models"

	basetypes "github.com/reallyoldfogie/mc-protocol-go/data/1.21.5/basetypes"
	config_clientbound "github.com/reallyoldfogie/mc-protocol-go/data/1.21.5/configuration/clientbound"
	config_serverbound "github.com/reallyoldfogie/mc-protocol-go/data/1.21.5/configuration/serverbound"
	login_clientbound "github.com/reallyoldfogie/mc-protocol-go/data/1.21.5/login/clientbound"
	login_serverbound "github.com/reallyoldfogie/mc-protocol-go/data/1.21.5/login/serverbound"
	play_clientbound "github.com/reallyoldfogie/mc-protocol-go/data/1.21.5/play/clientbound"
	play_serverbound "github.com/reallyoldfogie/mc-protocol-go/data/1.21.5/play/serverbound"
)

func (p Packets) Name() string {
	return "1.21.5"
}

func (p Packets) VersionProtocol() uint64 {
	return 770
}

func (p Packets) NewCommonStoreCookie() *basetypes.CommonStoreCookie {
	return basetypes.NewCommonStoreCookie()
}

func (p Packets) NewCommonCookieRequest() *basetypes.CommonCookieRequest {
	return basetypes.NewCommonCookieRequest()
}

func (p Packets) NewCommonCookieResponse() *basetypes.CommonCookieResponse {
	return basetypes.NewCommonCookieResponse()
}

func (p Packets) NewCommonSettings() *basetypes.CommonSettings {
	return basetypes.NewCommonSettings()
}

func (p Packets) NewCommonRemoveResourcePack() *basetypes.CommonRemoveResourcePack {
	return basetypes.NewCommonRemoveResourcePack()
}

func (p Packets) NewCommonCustomReportDetails() *basetypes.CommonCustomReportDetails {
	return basetypes.NewCommonCustomReportDetails()
}

func (p Packets) NewCommonTransfer() *basetypes.CommonTransfer {
	return basetypes.NewCommonTransfer()
}

func (p Packets) NewCommonServerLinks() *basetypes.CommonServerLinks {
	return basetypes.NewCommonServerLinks()
}

func (p Packets) NewCommonAddResourcePack() *basetypes.CommonAddResourcePack {
	return basetypes.NewCommonAddResourcePack()
}

func (p Packets) NewCommonSelectKnownPacks() *basetypes.CommonSelectKnownPacks {
	return basetypes.NewCommonSelectKnownPacks()
}

// Packet factory methods
func (p Packets) GetClientboundLoginPacketByID(id models.ClientboundPacketID) (models.PacketMarshaller, error) {
	switch id {
	case 0:
		return login_clientbound.NewDisconnect(), nil
	case 1:
		return login_clientbound.NewEncryptionBegin(), nil
	case 2:
		return login_clientbound.NewSuccess(), nil
	case 3:
		return login_clientbound.NewCompress(), nil
	case 4:
		return login_clientbound.NewLoginPluginRequest(), nil
	case 5:
		return basetypes.NewCommonCookieRequest(), nil
	default:
		return nil, fmt.Errorf("unknown clientbound login packet ID: %d", id)
	}
}

func (p Packets) GetClientboundConfigPacketByID(id models.ClientboundPacketID) (models.PacketMarshaller, error) {
	switch id {
	case 0:
		return basetypes.NewCommonCookieRequest(), nil
	case 1:
		return config_clientbound.NewCustomPayload(), nil
	case 2:
		return config_clientbound.NewDisconnect(), nil
	case 3:
		return config_clientbound.NewFinishConfiguration(), nil
	case 4:
		return config_clientbound.NewKeepAlive(), nil
	case 5:
		return config_clientbound.NewPing(), nil
	case 6:
		return config_clientbound.NewResetChat(), nil
	case 7:
		return config_clientbound.NewRegistryData(), nil
	case 8:
		return basetypes.NewCommonRemoveResourcePack(), nil
	case 9:
		return basetypes.NewCommonAddResourcePack(), nil
	case 10:
		return basetypes.NewCommonStoreCookie(), nil
	case 11:
		return basetypes.NewCommonTransfer(), nil
	case 12:
		return config_clientbound.NewFeatureFlags(), nil
	case 13:
		return config_clientbound.NewTags(), nil
	case 14:
		return basetypes.NewCommonSelectKnownPacks(), nil
	case 15:
		return basetypes.NewCommonCustomReportDetails(), nil
	case 16:
		return basetypes.NewCommonServerLinks(), nil
	default:
		return nil, fmt.Errorf("unknown clientbound config packet ID: %d", id)
	}
}

func (p Packets) GetClientboundPacketByID(id models.ClientboundPacketID) (models.PacketMarshaller, error) {
	switch id {
	case 1: // Play.Clientbound[{1}] = generator.packetData{Name:"SpawnEntity", ID:1, Hex:"0X01", StructName:"SpawnEntity", ProtoTypeName:"packet_spawn_entity", AltName:"ClientboundAddEntity"}
		return play_clientbound.NewSpawnEntity(), nil
	case 2: // Play.Clientbound[{2}] = generator.packetData{Name:"Animation", ID:2, Hex:"0X02", StructName:"Animation", ProtoTypeName:"packet_animation", AltName:"ClientboundAnimate"}
		return play_clientbound.NewAnimation(), nil
	case 3: // Play.Clientbound[{3}] = generator.packetData{Name:"Statistics", ID:3, Hex:"0X03", StructName:"Statistics", ProtoTypeName:"packet_statistics", AltName:"ClientboundAwardStats"}
		return play_clientbound.NewStatistics(), nil
	case 4: // Play.Clientbound[{4}] = generator.packetData{Name:"AcknowledgePlayerDigging", ID:4, Hex:"0X04", StructName:"AcknowledgePlayerDigging", ProtoTypeName:"packet_acknowledge_player_digging", AltName:"ClientboundBlockChangedAck"}
		return play_clientbound.NewAcknowledgePlayerDigging(), nil
	case 5: // Play.Clientbound[{5}] = generator.packetData{Name:"BlockBreakAnimation", ID:5, Hex:"0X05", StructName:"BlockBreakAnimation", ProtoTypeName:"packet_block_break_animation", AltName:"ClientboundBlockDestruction"}
		return play_clientbound.NewBlockBreakAnimation(), nil
	case 6: // Play.Clientbound[{6}] = generator.packetData{Name:"TileEntityData", ID:6, Hex:"0X06", StructName:"TileEntityData", ProtoTypeName:"packet_tile_entity_data", AltName:"ClientboundBlockEntityData"}
		return play_clientbound.NewTileEntityData(), nil
	case 7: // Play.Clientbound[{7}] = generator.packetData{Name:"BlockAction", ID:7, Hex:"0X07", StructName:"BlockAction", ProtoTypeName:"packet_block_action", AltName:"ClientboundBlockEvent"}
		return play_clientbound.NewBlockAction(), nil
	case 8: // Play.Clientbound[{8}] = generator.packetData{Name:"BlockChange", ID:8, Hex:"0X08", StructName:"BlockChange", ProtoTypeName:"packet_block_change", AltName:"ClientboundBlockUpdate"}
		return play_clientbound.NewBlockChange(), nil
	case 9: // Play.Clientbound[{9}] = generator.packetData{Name:"BossBar", ID:9, Hex:"0X09", StructName:"BossBar", ProtoTypeName:"packet_boss_bar", AltName:"ClientboundBossEvent"}
		return play_clientbound.NewBossBar(), nil
	case 10: // Play.Clientbound[{10}] = generator.packetData{Name:"Difficulty", ID:10, Hex:"0X0A", StructName:"Difficulty", ProtoTypeName:"packet_difficulty", AltName:"ClientboundChangeDifficulty"}
		return play_clientbound.NewDifficulty(), nil
	case 11: // Play.Clientbound[{11}] = generator.packetData{Name:"ChunkBatchFinished", ID:11, Hex:"0X0B", StructName:"ChunkBatchFinished", ProtoTypeName:"packet_chunk_batch_finished", AltName:""}
		return play_clientbound.NewChunkBatchFinished(), nil
	case 12: // Play.Clientbound[{12}] = generator.packetData{Name:"ChunkBatchStart", ID:12, Hex:"0X0C", StructName:"ChunkBatchStart", ProtoTypeName:"packet_chunk_batch_start", AltName:""}
		return play_clientbound.NewChunkBatchStart(), nil
	case 13: // Play.Clientbound[{13}] = generator.packetData{Name:"ChunkBiomes", ID:13, Hex:"0X0D", StructName:"ChunkBiomes", ProtoTypeName:"packet_chunk_biomes", AltName:"ClientboundChunksBiomes"}
		return play_clientbound.NewChunkBiomes(), nil
	case 14: // Play.Clientbound[{14}] = generator.packetData{Name:"ClearTitles", ID:14, Hex:"0X0E", StructName:"ClearTitles", ProtoTypeName:"packet_clear_titles", AltName:""}
		return play_clientbound.NewClearTitles(), nil
	case 15: // Play.Clientbound[{15}] = generator.packetData{Name:"TabComplete", ID:15, Hex:"0X0F", StructName:"", ProtoTypeName:"packet_tab_complete", AltName:"ClientboundCommandSuggestions"}
		return play_clientbound.NewTabComplete(), nil
	case 16: // Play.Clientbound[{16}] = generator.packetData{Name:"DeclareCommands", ID:16, Hex:"0X10", StructName:"DeclareCommands", ProtoTypeName:"packet_declare_commands", AltName:"ClientboundCommands"}
		return play_clientbound.NewDeclareCommands(), nil
	case 17: // Play.Clientbound[{17}] = generator.packetData{Name:"CloseWindow", ID:17, Hex:"0X11", StructName:"", ProtoTypeName:"packet_close_window", AltName:"ClientboundContainerClose"}
		return play_clientbound.NewCloseWindow(), nil
	case 18: // Play.Clientbound[{18}] = generator.packetData{Name:"WindowItems", ID:18, Hex:"0X12", StructName:"WindowItems", ProtoTypeName:"packet_window_items", AltName:"ClientboundContainerSetContent"}
		return play_clientbound.NewWindowItems(), nil
	case 19: // Play.Clientbound[{19}] = generator.packetData{Name:"CraftProgressBar", ID:19, Hex:"0X13", StructName:"CraftProgressBar", ProtoTypeName:"packet_craft_progress_bar", AltName:"ClientboundContainerSetData"}
		return play_clientbound.NewCraftProgressBar(), nil
	case 20: // Play.Clientbound[{20}] = generator.packetData{Name:"SetSlot", ID:20, Hex:"0X14", StructName:"SetSlot", ProtoTypeName:"packet_set_slot", AltName:"ClientboundContainerSetSlot"}
		return play_clientbound.NewSetSlot(), nil
	case 21: // Play.Clientbound[{21}] = generator.packetData{Name:"CommonCookieRequest", ID:21, Hex:"0X15", StructName:"", ProtoTypeName:"packet_common_cookie_request", AltName:"ClientboundCookieRequest"}
		return basetypes.NewCommonCookieRequest(), nil
	case 22: // Play.Clientbound[{22}] = generator.packetData{Name:"SetCooldown", ID:22, Hex:"0X16", StructName:"SetCooldown", ProtoTypeName:"packet_set_cooldown", AltName:"ClientboundCooldown"}
		return play_clientbound.NewSetCooldown(), nil
	case 23: // Play.Clientbound[{23}] = generator.packetData{Name:"ChatSuggestions", ID:23, Hex:"0X17", StructName:"ChatSuggestions", ProtoTypeName:"packet_chat_suggestions", AltName:"ClientboundCustomChatCompletions"}
		return play_clientbound.NewChatSuggestions(), nil
	case 24: // Play.Clientbound[{24}] = generator.packetData{Name:"CustomPayload", ID:24, Hex:"0X18", StructName:"", ProtoTypeName:"packet_custom_payload", AltName:""}
		return play_clientbound.NewCustomPayload(), nil
	case 25: // Play.Clientbound[{25}] = generator.packetData{Name:"DamageEvent", ID:25, Hex:"0X19", StructName:"DamageEvent", ProtoTypeName:"packet_damage_event", AltName:""}
		return play_clientbound.NewDamageEvent(), nil
	case 26: // Play.Clientbound[{26}] = generator.packetData{Name:"DebugSample", ID:26, Hex:"0X1A", StructName:"DebugSample", ProtoTypeName:"packet_debug_sample", AltName:""}
		return play_clientbound.NewDebugSample(), nil
	case 27: // Play.Clientbound[{27}] = generator.packetData{Name:"HideMessage", ID:27, Hex:"0X1B", StructName:"HideMessage", ProtoTypeName:"packet_hide_message", AltName:"ClientboundDeleteChat"}
		return play_clientbound.NewHideMessage(), nil
	case 28: // Play.Clientbound[{28}] = generator.packetData{Name:"KickDisconnect", ID:28, Hex:"0X1C", StructName:"KickDisconnect", ProtoTypeName:"packet_kick_disconnect", AltName:"ClientboundDisconnect"}
		return play_clientbound.NewKickDisconnect(), nil
	case 29: // Play.Clientbound[{29}] = generator.packetData{Name:"ProfilelessChat", ID:29, Hex:"0X1D", StructName:"ProfilelessChat", ProtoTypeName:"packet_profileless_chat", AltName:"ClientboundDisguisedChat"}
		return play_clientbound.NewProfilelessChat(), nil
	case 30: // Play.Clientbound[{30}] = generator.packetData{Name:"EntityStatus", ID:30, Hex:"0X1E", StructName:"EntityStatus", ProtoTypeName:"packet_entity_status", AltName:"ClientboundEntityEvent"}
		return play_clientbound.NewEntityStatus(), nil
	case 31: // Play.Clientbound[{31}] = generator.packetData{Name:"SyncEntityPosition", ID:31, Hex:"0X1F", StructName:"SyncEntityPosition", ProtoTypeName:"packet_sync_entity_position", AltName:"ClientboundEntityPositionSync"}
		return play_clientbound.NewSyncEntityPosition(), nil
	case 32: // Play.Clientbound[{32}] = generator.packetData{Name:"Explosion", ID:32, Hex:"0X20", StructName:"Explosion", ProtoTypeName:"packet_explosion", AltName:"ClientboundExplode"}
		return play_clientbound.NewExplosion(), nil
	case 33: // Play.Clientbound[{33}] = generator.packetData{Name:"UnloadChunk", ID:33, Hex:"0X21", StructName:"UnloadChunk", ProtoTypeName:"packet_unload_chunk", AltName:"ClientboundForgetLevelChunk"}
		return play_clientbound.NewUnloadChunk(), nil
	case 34: // Play.Clientbound[{34}] = generator.packetData{Name:"GameStateChange", ID:34, Hex:"0X22", StructName:"GameStateChange", ProtoTypeName:"packet_game_state_change", AltName:"ClientboundGameEvent"}
		return play_clientbound.NewGameStateChange(), nil
	case 35: // Play.Clientbound[{35}] = generator.packetData{Name:"OpenHorseWindow", ID:35, Hex:"0X23", StructName:"OpenHorseWindow", ProtoTypeName:"packet_open_horse_window", AltName:"ClientboundHorseScreenOpen"}
		return play_clientbound.NewOpenHorseWindow(), nil
	case 36: // Play.Clientbound[{36}] = generator.packetData{Name:"HurtAnimation", ID:36, Hex:"0X24", StructName:"HurtAnimation", ProtoTypeName:"packet_hurt_animation", AltName:""}
		return play_clientbound.NewHurtAnimation(), nil
	case 37: // Play.Clientbound[{37}] = generator.packetData{Name:"InitializeWorldBorder", ID:37, Hex:"0X25", StructName:"InitializeWorldBorder", ProtoTypeName:"packet_initialize_world_border", AltName:"ClientboundInitializeBorder"}
		return play_clientbound.NewInitializeWorldBorder(), nil
	case 38: // Play.Clientbound[{38}] = generator.packetData{Name:"KeepAlive", ID:38, Hex:"0X26", StructName:"", ProtoTypeName:"packet_keep_alive", AltName:""}
		return play_clientbound.NewKeepAlive(), nil
	case 39: // Play.Clientbound[{39}] = generator.packetData{Name:"MapChunk", ID:39, Hex:"0X27", StructName:"MapChunk", ProtoTypeName:"packet_map_chunk", AltName:"ClientboundLevelChunkWithLight"}
		return play_clientbound.NewMapChunk(), nil
	case 40: // Play.Clientbound[{40}] = generator.packetData{Name:"WorldEvent", ID:40, Hex:"0X28", StructName:"WorldEvent", ProtoTypeName:"packet_world_event", AltName:"ClientboundLevelEvent"}
		return play_clientbound.NewWorldEvent(), nil
	case 41: // Play.Clientbound[{41}] = generator.packetData{Name:"WorldParticles", ID:41, Hex:"0X29", StructName:"WorldParticles", ProtoTypeName:"packet_world_particles", AltName:"ClientboundLevelParticles"}
		return play_clientbound.NewWorldParticles(), nil
	case 42: // Play.Clientbound[{42}] = generator.packetData{Name:"UpdateLight", ID:42, Hex:"0X2A", StructName:"UpdateLight", ProtoTypeName:"packet_update_light", AltName:"ClientboundLightUpdate"}
		return play_clientbound.NewUpdateLight(), nil
	case 43: // Play.Clientbound[{43}] = generator.packetData{Name:"Login", ID:43, Hex:"0X2B", StructName:"Login", ProtoTypeName:"packet_login", AltName:""}
		return play_clientbound.NewLogin(), nil
	case 44: // Play.Clientbound[{44}] = generator.packetData{Name:"Map", ID:44, Hex:"0X2C", StructName:"Map", ProtoTypeName:"packet_map", AltName:"ClientboundMapItemData"}
		return play_clientbound.NewMap(), nil
	case 45: // Play.Clientbound[{45}] = generator.packetData{Name:"TradeList", ID:45, Hex:"0X2D", StructName:"TradeList", ProtoTypeName:"packet_trade_list", AltName:"ClientboundMerchantOffers"}
		return play_clientbound.NewTradeList(), nil
	case 46: // Play.Clientbound[{46}] = generator.packetData{Name:"RelEntityMove", ID:46, Hex:"0X2E", StructName:"RelEntityMove", ProtoTypeName:"packet_rel_entity_move", AltName:"ClientboundMoveEntityPos"}
		return play_clientbound.NewRelEntityMove(), nil
	case 47: // Play.Clientbound[{47}] = generator.packetData{Name:"EntityMoveLook", ID:47, Hex:"0X2F", StructName:"EntityMoveLook", ProtoTypeName:"packet_entity_move_look", AltName:"ClientboundMoveEntityPosRot"}
		return play_clientbound.NewEntityMoveLook(), nil
	case 48: // Play.Clientbound[{48}] = generator.packetData{Name:"MoveMinecart", ID:48, Hex:"0X30", StructName:"MoveMinecart", ProtoTypeName:"packet_move_minecart", AltName:"ClientboundMoveMinecartAlongTrack"}
		return play_clientbound.NewMoveMinecart(), nil
	case 49: // Play.Clientbound[{49}] = generator.packetData{Name:"EntityLook", ID:49, Hex:"0X31", StructName:"EntityLook", ProtoTypeName:"packet_entity_look", AltName:"ClientboundMoveEntityRot"}
		return play_clientbound.NewEntityLook(), nil
	case 50: // Play.Clientbound[{50}] = generator.packetData{Name:"VehicleMove", ID:50, Hex:"0X32", StructName:"", ProtoTypeName:"packet_vehicle_move", AltName:"ClientboundMoveVehicle"}
		return play_clientbound.NewVehicleMove(), nil
	case 51: // Play.Clientbound[{51}] = generator.packetData{Name:"OpenBook", ID:51, Hex:"0X33", StructName:"OpenBook", ProtoTypeName:"packet_open_book", AltName:""}
		return play_clientbound.NewOpenBook(), nil
	case 52: // Play.Clientbound[{52}] = generator.packetData{Name:"OpenWindow", ID:52, Hex:"0X34", StructName:"OpenWindow", ProtoTypeName:"packet_open_window", AltName:"ClientboundOpenScreen"}
		return play_clientbound.NewOpenWindow(), nil
	case 53: // Play.Clientbound[{53}] = generator.packetData{Name:"OpenSignEntity", ID:53, Hex:"0X35", StructName:"OpenSignEntity", ProtoTypeName:"packet_open_sign_entity", AltName:"ClientboundOpenSignEditor"}
		return play_clientbound.NewOpenSignEntity(), nil
	case 54: // Play.Clientbound[{54}] = generator.packetData{Name:"Ping", ID:54, Hex:"0X36", StructName:"Ping", ProtoTypeName:"packet_ping", AltName:""}
		return play_clientbound.NewPing(), nil
	case 55: // Play.Clientbound[{55}] = generator.packetData{Name:"PingResponse", ID:55, Hex:"0X37", StructName:"PingResponse", ProtoTypeName:"packet_ping_response", AltName:"ClientboundPongResponse"}
		return play_clientbound.NewPingResponse(), nil
	case 56: // Play.Clientbound[{56}] = generator.packetData{Name:"CraftRecipeResponse", ID:56, Hex:"0X38", StructName:"CraftRecipeResponse", ProtoTypeName:"packet_craft_recipe_response", AltName:"ClientboundPlaceGhostRecipe"}
		return play_clientbound.NewCraftRecipeResponse(), nil
	case 57: // Play.Clientbound[{57}] = generator.packetData{Name:"Abilities", ID:57, Hex:"0X39", StructName:"", ProtoTypeName:"packet_abilities", AltName:"ClientboundPlayerAbilities"}
		return play_clientbound.NewAbilities(), nil
	case 58: // Play.Clientbound[{58}] = generator.packetData{Name:"PlayerChat", ID:58, Hex:"0X3A", StructName:"PlayerChat", ProtoTypeName:"packet_player_chat", AltName:""}
		return play_clientbound.NewPlayerChat(), nil
	case 59: // Play.Clientbound[{59}] = generator.packetData{Name:"EndCombatEvent", ID:59, Hex:"0X3B", StructName:"EndCombatEvent", ProtoTypeName:"packet_end_combat_event", AltName:"ClientboundPlayerCombatEnd"}
		return play_clientbound.NewEndCombatEvent(), nil
	case 60: // Play.Clientbound[{60}] = generator.packetData{Name:"EnterCombatEvent", ID:60, Hex:"0X3C", StructName:"EnterCombatEvent", ProtoTypeName:"packet_enter_combat_event", AltName:"ClientboundPlayerCombatEnter"}
		return play_clientbound.NewEnterCombatEvent(), nil
	case 61: // Play.Clientbound[{61}] = generator.packetData{Name:"DeathCombatEvent", ID:61, Hex:"0X3D", StructName:"DeathCombatEvent", ProtoTypeName:"packet_death_combat_event", AltName:"ClientboundPlayerCombatKill"}
		return play_clientbound.NewDeathCombatEvent(), nil
	case 62: // Play.Clientbound[{62}] = generator.packetData{Name:"PlayerRemove", ID:62, Hex:"0X3E", StructName:"PlayerRemove", ProtoTypeName:"packet_player_remove", AltName:"ClientboundPlayerInfoRemove"}
		return play_clientbound.NewPlayerRemove(), nil
	case 63: // Play.Clientbound[{63}] = generator.packetData{Name:"PlayerInfo", ID:63, Hex:"0X3F", StructName:"PlayerInfo", ProtoTypeName:"packet_player_info", AltName:"ClientboundPlayerInfoUpdate"}
		return play_clientbound.NewPlayerInfo(), nil
	case 64: // Play.Clientbound[{64}] = generator.packetData{Name:"FacePlayer", ID:64, Hex:"0X40", StructName:"FacePlayer", ProtoTypeName:"packet_face_player", AltName:"ClientboundPlayerLookAt"}
		return play_clientbound.NewFacePlayer(), nil
	case 65: // Play.Clientbound[{65}] = generator.packetData{Name:"Position", ID:65, Hex:"0X41", StructName:"", ProtoTypeName:"packet_position", AltName:"ClientboundPlayerPosition"}
		return play_clientbound.NewPosition(), nil
	case 66: // Play.Clientbound[{66}] = generator.packetData{Name:"PlayerRotation", ID:66, Hex:"0X42", StructName:"PlayerRotation", ProtoTypeName:"packet_player_rotation", AltName:""}
		return play_clientbound.NewPlayerRotation(), nil
	case 67: // Play.Clientbound[{67}] = generator.packetData{Name:"RecipeBookAdd", ID:67, Hex:"0X43", StructName:"RecipeBookAdd", ProtoTypeName:"packet_recipe_book_add", AltName:""}
		return play_clientbound.NewRecipeBookAdd(), nil
	case 68: // Play.Clientbound[{68}] = generator.packetData{Name:"RecipeBookRemove", ID:68, Hex:"0X44", StructName:"RecipeBookRemove", ProtoTypeName:"packet_recipe_book_remove", AltName:""}
		return play_clientbound.NewRecipeBookRemove(), nil
	case 69: // Play.Clientbound[{69}] = generator.packetData{Name:"RecipeBookSettings", ID:69, Hex:"0X45", StructName:"RecipeBookSettings", ProtoTypeName:"packet_recipe_book_settings", AltName:""}
		return play_clientbound.NewRecipeBookSettings(), nil
	case 70: // Play.Clientbound[{70}] = generator.packetData{Name:"EntityDestroy", ID:70, Hex:"0X46", StructName:"EntityDestroy", ProtoTypeName:"packet_entity_destroy", AltName:"ClientboundRemoveEntities"}
		return play_clientbound.NewEntityDestroy(), nil
	case 71: // Play.Clientbound[{71}] = generator.packetData{Name:"RemoveEntityEffect", ID:71, Hex:"0X47", StructName:"RemoveEntityEffect", ProtoTypeName:"packet_remove_entity_effect", AltName:"ClientboundRemoveMobEffect"}
		return play_clientbound.NewRemoveEntityEffect(), nil
	case 72: // Play.Clientbound[{72}] = generator.packetData{Name:"ResetScore", ID:72, Hex:"0X48", StructName:"ResetScore", ProtoTypeName:"packet_reset_score", AltName:""}
		return play_clientbound.NewResetScore(), nil
	case 73: // Play.Clientbound[{73}] = generator.packetData{Name:"CommonRemoveResourcePack", ID:73, Hex:"0X49", StructName:"", ProtoTypeName:"packet_common_remove_resource_pack", AltName:"ClientboundResourcePackPop"}
		return basetypes.NewCommonRemoveResourcePack(), nil
	case 74: // Play.Clientbound[{74}] = generator.packetData{Name:"CommonAddResourcePack", ID:74, Hex:"0X4A", StructName:"", ProtoTypeName:"packet_common_add_resource_pack", AltName:"ClientboundResourcePackPush"}
		return basetypes.NewCommonAddResourcePack(), nil
	case 75: // Play.Clientbound[{75}] = generator.packetData{Name:"Respawn", ID:75, Hex:"0X4B", StructName:"Respawn", ProtoTypeName:"packet_respawn", AltName:""}
		return play_clientbound.NewRespawn(), nil
	case 76: // Play.Clientbound[{76}] = generator.packetData{Name:"EntityHeadRotation", ID:76, Hex:"0X4C", StructName:"EntityHeadRotation", ProtoTypeName:"packet_entity_head_rotation", AltName:"ClientboundRotateHead"}
		return play_clientbound.NewEntityHeadRotation(), nil
	case 77: // Play.Clientbound[{77}] = generator.packetData{Name:"MultiBlockChange", ID:77, Hex:"0X4D", StructName:"MultiBlockChange", ProtoTypeName:"packet_multi_block_change", AltName:"ClientboundSectionBlocksUpdate"}
		return play_clientbound.NewMultiBlockChange(), nil
	case 78: // Play.Clientbound[{78}] = generator.packetData{Name:"SelectAdvancementTab", ID:78, Hex:"0X4E", StructName:"SelectAdvancementTab", ProtoTypeName:"packet_select_advancement_tab", AltName:"ClientboundSelectAdvancementsTab"}
		return play_clientbound.NewSelectAdvancementTab(), nil
	case 79: // Play.Clientbound[{79}] = generator.packetData{Name:"ServerData", ID:79, Hex:"0X4F", StructName:"ServerData", ProtoTypeName:"packet_server_data", AltName:""}
		return play_clientbound.NewServerData(), nil
	case 80: // Play.Clientbound[{80}] = generator.packetData{Name:"ActionBar", ID:80, Hex:"0X50", StructName:"ActionBar", ProtoTypeName:"packet_action_bar", AltName:"ClientboundSetActionBarText"}
		return play_clientbound.NewActionBar(), nil
	case 81: // Play.Clientbound[{81}] = generator.packetData{Name:"WorldBorderCenter", ID:81, Hex:"0X51", StructName:"WorldBorderCenter", ProtoTypeName:"packet_world_border_center", AltName:"ClientboundSetBorderCenter"}
		return play_clientbound.NewWorldBorderCenter(), nil
	case 82: // Play.Clientbound[{82}] = generator.packetData{Name:"WorldBorderLerpSize", ID:82, Hex:"0X52", StructName:"WorldBorderLerpSize", ProtoTypeName:"packet_world_border_lerp_size", AltName:"ClientboundSetBorderLerpSize"}
		return play_clientbound.NewWorldBorderLerpSize(), nil
	case 83: // Play.Clientbound[{83}] = generator.packetData{Name:"WorldBorderSize", ID:83, Hex:"0X53", StructName:"WorldBorderSize", ProtoTypeName:"packet_world_border_size", AltName:"ClientboundSetBorderSize"}
		return play_clientbound.NewWorldBorderSize(), nil
	case 84: // Play.Clientbound[{84}] = generator.packetData{Name:"WorldBorderWarningDelay", ID:84, Hex:"0X54", StructName:"WorldBorderWarningDelay", ProtoTypeName:"packet_world_border_warning_delay", AltName:"ClientboundSetBorderWarningDelay"}
		return play_clientbound.NewWorldBorderWarningDelay(), nil
	case 85: // Play.Clientbound[{85}] = generator.packetData{Name:"WorldBorderWarningReach", ID:85, Hex:"0X55", StructName:"WorldBorderWarningReach", ProtoTypeName:"packet_world_border_warning_reach", AltName:"ClientboundSetBorderWarningDistance"}
		return play_clientbound.NewWorldBorderWarningReach(), nil
	case 86: // Play.Clientbound[{86}] = generator.packetData{Name:"Camera", ID:86, Hex:"0X56", StructName:"Camera", ProtoTypeName:"packet_camera", AltName:"ClientboundSetCamera"}
		return play_clientbound.NewCamera(), nil
	case 87: // Play.Clientbound[{87}] = generator.packetData{Name:"UpdateViewPosition", ID:87, Hex:"0X57", StructName:"UpdateViewPosition", ProtoTypeName:"packet_update_view_position", AltName:"ClientboundSetChunkCacheCenter"}
		return play_clientbound.NewUpdateViewPosition(), nil
	case 88: // Play.Clientbound[{88}] = generator.packetData{Name:"UpdateViewDistance", ID:88, Hex:"0X58", StructName:"UpdateViewDistance", ProtoTypeName:"packet_update_view_distance", AltName:"ClientboundSetChunkCacheRadius"}
		return play_clientbound.NewUpdateViewDistance(), nil
	case 89: // Play.Clientbound[{89}] = generator.packetData{Name:"SetCursorItem", ID:89, Hex:"0X59", StructName:"SetCursorItem", ProtoTypeName:"packet_set_cursor_item", AltName:""}
		return play_clientbound.NewSetCursorItem(), nil
	case 90: // Play.Clientbound[{90}] = generator.packetData{Name:"SpawnPosition", ID:90, Hex:"0X5A", StructName:"SpawnPosition", ProtoTypeName:"packet_spawn_position", AltName:"ClientboundSetDefaultSpawnPosition"}
		return play_clientbound.NewSpawnPosition(), nil
	case 91: // Play.Clientbound[{91}] = generator.packetData{Name:"ScoreboardDisplayObjective", ID:91, Hex:"0X5B", StructName:"ScoreboardDisplayObjective", ProtoTypeName:"packet_scoreboard_display_objective", AltName:"ClientboundSetDisplayObjective"}
		return play_clientbound.NewScoreboardDisplayObjective(), nil
	case 92: // Play.Clientbound[{92}] = generator.packetData{Name:"EntityMetadata", ID:92, Hex:"0X5C", StructName:"EntityMetadata", ProtoTypeName:"packet_entity_metadata", AltName:"ClientboundSetEntityData"}
		return play_clientbound.NewEntityMetadata(), nil
	case 93: // Play.Clientbound[{93}] = generator.packetData{Name:"AttachEntity", ID:93, Hex:"0X5D", StructName:"AttachEntity", ProtoTypeName:"packet_attach_entity", AltName:"ClientboundSetEntityLink"}
		return play_clientbound.NewAttachEntity(), nil
	case 94: // Play.Clientbound[{94}] = generator.packetData{Name:"EntityVelocity", ID:94, Hex:"0X5E", StructName:"EntityVelocity", ProtoTypeName:"packet_entity_velocity", AltName:"ClientboundSetEntityMotion"}
		return play_clientbound.NewEntityVelocity(), nil
	case 95: // Play.Clientbound[{95}] = generator.packetData{Name:"EntityEquipment", ID:95, Hex:"0X5F", StructName:"EntityEquipment", ProtoTypeName:"packet_entity_equipment", AltName:"ClientboundSetEquipment"}
		return play_clientbound.NewEntityEquipment(), nil
	case 96: // Play.Clientbound[{96}] = generator.packetData{Name:"Experience", ID:96, Hex:"0X60", StructName:"Experience", ProtoTypeName:"packet_experience", AltName:"ClientboundSetExperience"}
		return play_clientbound.NewExperience(), nil
	case 97: // Play.Clientbound[{97}] = generator.packetData{Name:"UpdateHealth", ID:97, Hex:"0X61", StructName:"UpdateHealth", ProtoTypeName:"packet_update_health", AltName:"ClientboundSetHealth"}
		return play_clientbound.NewUpdateHealth(), nil
	case 98: // Play.Clientbound[{98}] = generator.packetData{Name:"HeldItemSlot", ID:98, Hex:"0X62", StructName:"", ProtoTypeName:"packet_held_item_slot", AltName:"ClientboundSetHeldSlot"}
		return play_clientbound.NewHeldItemSlot(), nil
	case 99: // Play.Clientbound[{99}] = generator.packetData{Name:"ScoreboardObjective", ID:99, Hex:"0X63", StructName:"ScoreboardObjective", ProtoTypeName:"packet_scoreboard_objective", AltName:"ClientboundSetObjective"}
		return play_clientbound.NewScoreboardObjective(), nil
	case 100: // Play.Clientbound[{100}] = generator.packetData{Name:"SetPassengers", ID:100, Hex:"0X64", StructName:"SetPassengers", ProtoTypeName:"packet_set_passengers", AltName:""}
		return play_clientbound.NewSetPassengers(), nil
	case 101: // Play.Clientbound[{101}] = generator.packetData{Name:"SetPlayerInventory", ID:101, Hex:"0X65", StructName:"SetPlayerInventory", ProtoTypeName:"packet_set_player_inventory", AltName:""}
		return play_clientbound.NewSetPlayerInventory(), nil
	case 102: // Play.Clientbound[{102}] = generator.packetData{Name:"Teams", ID:102, Hex:"0X66", StructName:"Teams", ProtoTypeName:"packet_teams", AltName:"ClientboundSetPlayerTeam"}
		return play_clientbound.NewTeams(), nil
	case 103: // Play.Clientbound[{103}] = generator.packetData{Name:"ScoreboardScore", ID:103, Hex:"0X67", StructName:"ScoreboardScore", ProtoTypeName:"packet_scoreboard_score", AltName:"ClientboundSetScore"}
		return play_clientbound.NewScoreboardScore(), nil
	case 104: // Play.Clientbound[{104}] = generator.packetData{Name:"SimulationDistance", ID:104, Hex:"0X68", StructName:"SimulationDistance", ProtoTypeName:"packet_simulation_distance", AltName:"ClientboundSetSimulationDistance"}
		return play_clientbound.NewSimulationDistance(), nil
	case 105: // Play.Clientbound[{105}] = generator.packetData{Name:"SetTitleSubtitle", ID:105, Hex:"0X69", StructName:"SetTitleSubtitle", ProtoTypeName:"packet_set_title_subtitle", AltName:"ClientboundSetSubtitleText"}
		return play_clientbound.NewSetTitleSubtitle(), nil
	case 106: // Play.Clientbound[{106}] = generator.packetData{Name:"UpdateTime", ID:106, Hex:"0X6A", StructName:"UpdateTime", ProtoTypeName:"packet_update_time", AltName:"ClientboundSetTime"}
		return play_clientbound.NewUpdateTime(), nil
	case 107: // Play.Clientbound[{107}] = generator.packetData{Name:"SetTitleText", ID:107, Hex:"0X6B", StructName:"SetTitleText", ProtoTypeName:"packet_set_title_text", AltName:""}
		return play_clientbound.NewSetTitleText(), nil
	case 108: // Play.Clientbound[{108}] = generator.packetData{Name:"SetTitleTime", ID:108, Hex:"0X6C", StructName:"SetTitleTime", ProtoTypeName:"packet_set_title_time", AltName:"ClientboundSetTitlesAnimation"}
		return play_clientbound.NewSetTitleTime(), nil
	case 109: // Play.Clientbound[{109}] = generator.packetData{Name:"EntitySoundEffect", ID:109, Hex:"0X6D", StructName:"EntitySoundEffect", ProtoTypeName:"packet_entity_sound_effect", AltName:"ClientboundSoundEntity"}
		return play_clientbound.NewEntitySoundEffect(), nil
	case 110: // Play.Clientbound[{110}] = generator.packetData{Name:"SoundEffect", ID:110, Hex:"0X6E", StructName:"SoundEffect", ProtoTypeName:"packet_sound_effect", AltName:"ClientboundSound"}
		return play_clientbound.NewSoundEffect(), nil
	case 111: // Play.Clientbound[{111}] = generator.packetData{Name:"StartConfiguration", ID:111, Hex:"0X6F", StructName:"StartConfiguration", ProtoTypeName:"packet_start_configuration", AltName:""}
		return play_clientbound.NewStartConfiguration(), nil
	case 112: // Play.Clientbound[{112}] = generator.packetData{Name:"StopSound", ID:112, Hex:"0X70", StructName:"StopSound", ProtoTypeName:"packet_stop_sound", AltName:""}
		return play_clientbound.NewStopSound(), nil
	case 113: // Play.Clientbound[{113}] = generator.packetData{Name:"CommonStoreCookie", ID:113, Hex:"0X71", StructName:"", ProtoTypeName:"packet_common_store_cookie", AltName:"ClientboundStoreCookie"}
		return basetypes.NewCommonStoreCookie(), nil
	case 114: // Play.Clientbound[{114}] = generator.packetData{Name:"SystemChat", ID:114, Hex:"0X72", StructName:"SystemChat", ProtoTypeName:"packet_system_chat", AltName:""}
		return play_clientbound.NewSystemChat(), nil
	case 115: // Play.Clientbound[{115}] = generator.packetData{Name:"PlayerlistHeader", ID:115, Hex:"0X73", StructName:"PlayerlistHeader", ProtoTypeName:"packet_playerlist_header", AltName:"ClientboundTabList"}
		return play_clientbound.NewPlayerlistHeader(), nil
	case 116: // Play.Clientbound[{116}] = generator.packetData{Name:"NbtQueryResponse", ID:116, Hex:"0X74", StructName:"NbtQueryResponse", ProtoTypeName:"packet_nbt_query_response", AltName:"ClientboundTagQuery"}
		return play_clientbound.NewNbtQueryResponse(), nil
	case 117: // Play.Clientbound[{117}] = generator.packetData{Name:"Collect", ID:117, Hex:"0X75", StructName:"Collect", ProtoTypeName:"packet_collect", AltName:"ClientboundTakeItemEntity"}
		return play_clientbound.NewCollect(), nil
	case 118: // Play.Clientbound[{118}] = generator.packetData{Name:"EntityTeleport", ID:118, Hex:"0X76", StructName:"EntityTeleport", ProtoTypeName:"packet_entity_teleport", AltName:"ClientboundTeleportEntity"}
		return play_clientbound.NewEntityTeleport(), nil
	case 119: // Play.Clientbound[{119}] = generator.packetData{Name:"TestInstanceBlockStatus", ID:119, Hex:"0X77", StructName:"TestInstanceBlockStatus", ProtoTypeName:"packet_test_instance_block_status", AltName:""}
		return play_clientbound.NewTestInstanceBlockStatus(), nil
	case 120: // Play.Clientbound[{120}] = generator.packetData{Name:"SetTickingState", ID:120, Hex:"0X78", StructName:"SetTickingState", ProtoTypeName:"packet_set_ticking_state", AltName:"ClientboundTickingState"}
		return play_clientbound.NewSetTickingState(), nil
	case 121: // Play.Clientbound[{121}] = generator.packetData{Name:"StepTick", ID:121, Hex:"0X79", StructName:"StepTick", ProtoTypeName:"packet_step_tick", AltName:"ClientboundTickingStep"}
		return play_clientbound.NewStepTick(), nil
	case 122: // Play.Clientbound[{122}] = generator.packetData{Name:"CommonTransfer", ID:122, Hex:"0X7A", StructName:"", ProtoTypeName:"packet_common_transfer", AltName:"ClientboundTransfer"}
		return basetypes.NewCommonTransfer(), nil
	case 123: // Play.Clientbound[{123}] = generator.packetData{Name:"Advancements", ID:123, Hex:"0X7B", StructName:"Advancements", ProtoTypeName:"packet_advancements", AltName:"ClientboundUpdateAdvancements"}
		return play_clientbound.NewAdvancements(), nil
	case 124: // Play.Clientbound[{124}] = generator.packetData{Name:"EntityUpdateAttributes", ID:124, Hex:"0X7C", StructName:"EntityUpdateAttributes", ProtoTypeName:"packet_entity_update_attributes", AltName:"ClientboundUpdateAttributes"}
		return play_clientbound.NewEntityUpdateAttributes(), nil
	case 125: // Play.Clientbound[{125}] = generator.packetData{Name:"EntityEffect", ID:125, Hex:"0X7D", StructName:"EntityEffect", ProtoTypeName:"packet_entity_effect", AltName:"ClientboundUpdateMobEffect"}
		return play_clientbound.NewEntityEffect(), nil
	case 126: // Play.Clientbound[{126}] = generator.packetData{Name:"DeclareRecipes", ID:126, Hex:"0X7E", StructName:"DeclareRecipes", ProtoTypeName:"packet_declare_recipes", AltName:"ClientboundUpdateRecipes"}
		return play_clientbound.NewDeclareRecipes(), nil
	case 127: // Play.Clientbound[{127}] = generator.packetData{Name:"Tags", ID:127, Hex:"0X7F", StructName:"Tags", ProtoTypeName:"packet_tags", AltName:"ClientboundUpdateTags"}
		return play_clientbound.NewTags(), nil
	case 128: // Play.Clientbound[{128}] = generator.packetData{Name:"SetProjectilePower", ID:128, Hex:"0X80", StructName:"SetProjectilePower", ProtoTypeName:"packet_set_projectile_power", AltName:"ClientboundProjectilePower"}
		return play_clientbound.NewSetProjectilePower(), nil
	case 129: // Play.Clientbound[{129}] = generator.packetData{Name:"CommonCustomReportDetails", ID:129, Hex:"0X81", StructName:"", ProtoTypeName:"packet_common_custom_report_details", AltName:"ClientboundCustomReportDetails"}
		return basetypes.NewCommonCustomReportDetails(), nil
	case 130: // Play.Clientbound[{130}] = generator.packetData{Name:"CommonServerLinks", ID:130, Hex:"0X82", StructName:"", ProtoTypeName:"packet_common_server_links", AltName:"ClientboundServerLinks"}
		return basetypes.NewCommonServerLinks(), nil

	default:
		return nil, fmt.Errorf("unknown clientbound play packet ID: %d", id)
	}
}

func (p Packets) GetServerboundLoginPacketByID(id models.ServerboundPacketID) (models.PacketMarshaller, error) {
	switch id {
	case 0:
		return login_serverbound.NewLoginStart(), nil
	case 1:
		return login_serverbound.NewEncryptionBegin(), nil
	case 2:
		return login_serverbound.NewLoginPluginResponse(), nil
	case 3:
		return login_serverbound.NewLoginAcknowledged(), nil
	case 4:
		return basetypes.NewCommonCookieResponse(), nil
	default:
		return nil, fmt.Errorf("unknown serverbound login packet ID: %d", id)
	}
}

func (p Packets) GetServerboundConfigPacketByID(id models.ServerboundPacketID) (models.PacketMarshaller, error) {
	switch id {
	case 0:
		return basetypes.NewCommonSettings(), nil
	case 1:
		return basetypes.NewCommonCookieResponse(), nil
	case 2:
		return config_serverbound.NewCustomPayload(), nil
	case 3:
		return config_serverbound.NewFinishConfiguration(), nil
	case 4:
		return config_serverbound.NewKeepAlive(), nil
	case 5:
		return config_serverbound.NewPong(), nil
	case 6:
		return config_serverbound.NewResourcePackReceive(), nil
	case 7:
		return basetypes.NewCommonSelectKnownPacks(), nil
	case 8:
		return basetypes.NewCommonCustomReportDetails(), nil
	case 9:
		return basetypes.NewCommonServerLinks(), nil
	default:
		return nil, fmt.Errorf("unknown serverbound config packet ID: %d", id)
	}
}

func (p Packets) GetServerboundPacketByID(id models.ServerboundPacketID) (models.PacketMarshaller, error) {
	switch id {
	case 0:
		return play_serverbound.NewTeleportConfirm(), nil
	case 1:
		return play_serverbound.NewQueryBlockNbt(), nil
	case 2:
		return play_serverbound.NewSelectBundleItem(), nil
	case 3:
		return play_serverbound.NewSetDifficulty(), nil
	case 4:
		return play_serverbound.NewMessageAcknowledgement(), nil
	case 5:
		return play_serverbound.NewChatCommand(), nil
	case 6:
		return play_serverbound.NewChatCommandSigned(), nil
	case 7:
		return play_serverbound.NewChatMessage(), nil
	case 8:
		return play_serverbound.NewChatSessionUpdate(), nil
	case 9:
		return play_serverbound.NewChunkBatchReceived(), nil
	case 10:
		return play_serverbound.NewClientCommand(), nil
	case 11:
		return play_serverbound.NewTickEnd(), nil
	case 12:
		return basetypes.NewCommonSettings(), nil
	case 13:
		return play_serverbound.NewTabComplete(), nil
	case 14:
		return play_serverbound.NewConfigurationAcknowledged(), nil
	case 15:
		return play_serverbound.NewEnchantItem(), nil
	case 16:
		return play_serverbound.NewWindowClick(), nil
	case 17:
		return play_serverbound.NewCloseWindow(), nil
	case 18:
		return play_serverbound.NewSetSlotState(), nil
	case 19:
		return basetypes.NewCommonCookieResponse(), nil
	case 20:
		return play_serverbound.NewCustomPayload(), nil
	case 21:
		return play_serverbound.NewDebugSampleSubscription(), nil
	case 22:
		return play_serverbound.NewEditBook(), nil
	case 23:
		return play_serverbound.NewQueryEntityNbt(), nil
	case 24:
		return play_serverbound.NewUseEntity(), nil
	case 25:
		return play_serverbound.NewGenerateStructure(), nil
	case 26:
		return play_serverbound.NewKeepAlive(), nil
	case 27:
		return play_serverbound.NewLockDifficulty(), nil
	case 28:
		return play_serverbound.NewPosition(), nil
	case 29:
		return play_serverbound.NewPositionLook(), nil
	case 30:
		return play_serverbound.NewLook(), nil
	case 31:
		return play_serverbound.NewFlying(), nil
	case 32:
		return play_serverbound.NewVehicleMove(), nil
	case 33:
		return play_serverbound.NewSteerBoat(), nil
	case 34:
		return play_serverbound.NewPickItemFromBlock(), nil
	case 35:
		return play_serverbound.NewPickItemFromEntity(), nil
	case 36:
		return play_serverbound.NewPingRequest(), nil
	case 37:
		return play_serverbound.NewCraftRecipeRequest(), nil
	case 38:
		return play_serverbound.NewAbilities(), nil
	case 39:
		return play_serverbound.NewBlockDig(), nil
	case 40:
		return play_serverbound.NewEntityAction(), nil
	case 41:
		return play_serverbound.NewPlayerInput(), nil
	case 42:
		return play_serverbound.NewPlayerLoaded(), nil
	case 43:
		return play_serverbound.NewPong(), nil
	case 44:
		return play_serverbound.NewRecipeBook(), nil
	case 45:
		return play_serverbound.NewDisplayedRecipe(), nil
	case 46:
		return play_serverbound.NewNameItem(), nil
	case 47:
		return play_serverbound.NewResourcePackReceive(), nil
	case 48:
		return play_serverbound.NewAdvancementTab(), nil
	case 49:
		return play_serverbound.NewSelectTrade(), nil
	case 50:
		return play_serverbound.NewSetBeaconEffect(), nil
	case 51:
		return play_serverbound.NewHeldItemSlot(), nil
	case 52:
		return play_serverbound.NewUpdateCommandBlock(), nil
	case 53:
		return play_serverbound.NewUpdateCommandBlockMinecart(), nil
	case 54:
		return play_serverbound.NewSetCreativeSlot(), nil
	case 55:
		return play_serverbound.NewUpdateJigsawBlock(), nil
	case 56:
		return play_serverbound.NewUpdateStructureBlock(), nil
	case 57:
		return play_serverbound.NewSetTestBlock(), nil
	case 58:
		return play_serverbound.NewUpdateSign(), nil
	case 59:
		return play_serverbound.NewArmAnimation(), nil
	case 60:
		return play_serverbound.NewTestInstanceBlockAction(), nil
	case 61:
		return play_serverbound.NewSpectate(), nil
	case 62:
		return play_serverbound.NewBlockPlace(), nil
	case 63:
		return play_serverbound.NewUseItem(), nil
	default:
		return nil, fmt.Errorf("unknown serverbound play packet ID: %d", id)
	}
}
