package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/reallyoldfogie/mc-protocol-go/data/versions"
	"github.com/reallyoldfogie/mc-protocol-go/internal/generator"
	"github.com/reallyoldfogie/mc-protocol-go/internal/packetlogtest"
)

// Structures matching the ground truth results bundle
type versionBlock struct {
	Version string                            `json:"version"`
	Results []packetlogtest.GroundTruthResult `json:"results"`
	Summary struct {
		Total   int `json:"total"`
		Success int `json:"success"`
		Failed  int `json:"failed"`
	} `json:"summary"`
}

func main() {
	var (
		testFile     string
		testPaths    string
		version      string
		configPath   string
		verbose      bool
		showSuccess  bool
		jsonOut      string
		htmlOut      string
		mdOut        string
		failOnErrors bool
	)

	flag.StringVar(&testFile, "test-file", "", "Path to ground truth test file (JSONL), supports shell globs (e.g., tests/*.jsonl)")
	flag.StringVar(&testPaths, "test-paths", "", "Comma-separated list of files or directories to search for .jsonl test files")
	flag.StringVar(&version, "version", "", "Minecraft version to test (if not specified, tests all versions from config)")
	flag.StringVar(&configPath, "config", "configs/config.yaml", "Path to configuration file (used when --version not specified)")
	flag.BoolVar(&verbose, "verbose", false, "Show detailed output")
	flag.BoolVar(&showSuccess, "show-success", false, "Show successful validations (default: only failures)")
	flag.StringVar(&jsonOut, "json", "", "Write JSON results to specified file (text output still goes to stdout)")
	flag.StringVar(&htmlOut, "html", "", "Write HTML report to specified file (derived from JSON bundle)")
	flag.StringVar(&mdOut, "md", "", "Write Markdown report to specified file (derived from JSON bundle)")
	flag.BoolVar(&failOnErrors, "fail-on-errors", false, "Exit with non-zero status if any validations fail")

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s -test-file <path> [-version <version>]\n\n", os.Args[0])
		fmt.Fprintln(os.Stderr, "Validates Go packet parser against ground truth test cases generated by node-minecraft-protocol.")
		fmt.Fprintln(os.Stderr, "\nOptions:")
		flag.PrintDefaults()
		fmt.Fprintln(os.Stderr, "\nSupported versions:")
		fmt.Fprintln(os.Stderr, "  1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.21.7, 1.21.8")
		fmt.Fprintln(os.Stderr, "\nExamples:")
		fmt.Fprintln(os.Stderr, "  # Test a specific version")
		fmt.Fprintln(os.Stderr, "  go run ./cmd/groundtruth-validation -test-file test.jsonl -version 1.21.5")
		fmt.Fprintln(os.Stderr, "\n  # Test all versions from config")
		fmt.Fprintln(os.Stderr, "  go run ./cmd/groundtruth-validation -test-file test.jsonl")
	}

	flag.Parse()

	if testFile == "" && testPaths == "" {
		fmt.Fprintln(os.Stderr, "Error: one of -test-file or -test-paths is required")
		flag.Usage()
		os.Exit(1)
	}

	// Resolve test files (support globs and directories)
	testFiles := []string{}
	if testFile != "" {
		// Expand glob if present
		if hasGlob(testFile) {
			matches, err := filepath.Glob(testFile)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Invalid glob for -test-file: %v\n", err)
				os.Exit(1)
			}
			testFiles = append(testFiles, matches...)
		} else {
			testFiles = append(testFiles, testFile)
		}
	}
	if testPaths != "" {
		paths := strings.Split(testPaths, ",")
		files, err := collectJSONLFiles(paths)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error collecting test files: %v\n", err)
			os.Exit(1)
		}
		testFiles = append(testFiles, files...)
	}
	// Deduplicate
	if len(testFiles) == 0 {
		fmt.Fprintln(os.Stderr, "No test files found (.jsonl)")
		os.Exit(1)
	}
	testFiles = uniqStrings(testFiles)

	// Determine which versions to test
	var versionsToTest []string
	if version != "" {
		// Single version specified
		versionsToTest = []string{version}
	} else {
		// Load all versions from config
		cfg, err := loadConfig(configPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error loading config: %v\n", err)
			os.Exit(1)
		}
		versionsToTest = cfg.Versions
		fmt.Printf("Testing all versions from config: %v\n\n", versionsToTest)
	}

	// JSON aggregation structures
	var jsonBundle struct {
		Versions []versionBlock `json:"versions"`
		Total    struct {
			Versions int `json:"versions"`
			Tests    int `json:"tests"`
			Success  int `json:"success"`
			Failed   int `json:"failed"`
		} `json:"total"`
	}

	// Run validation for each version
	totalSuccess := 0
	totalFail := 0
	hasFailures := false

	for _, ver := range versionsToTest {
		if len(versionsToTest) > 1 {
			fmt.Printf("=== Testing version %s ===\n", ver)
		}

		// Load packet manager for this version
		packetMgr := versions.GetPacketMgrForVersion(ver)

		// Run validation across all test files
		var results []packetlogtest.GroundTruthResult
		for _, tf := range testFiles {
			r, err := packetlogtest.ValidateGroundTruthForVersion(tf, packetMgr)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", tf, err)
				os.Exit(1)
			}
			results = append(results, r...)
		}

		// Display results
		successCount := 0
		failCount := 0

		for _, result := range results {
			if result.Success {
				successCount++
				if showSuccess {
					fmt.Printf("✓ %s (%s, ID=%d)\n", result.Description, result.PacketName, result.PacketID)
				}
			} else {
				failCount++
				fmt.Printf("✗ %s (%s, ID=%d)\n", result.Description, result.PacketName, result.PacketID)
				for _, err := range result.Errors {
					fmt.Printf("  - %s\n", err)
				}
			}
		}

		// Summary for this version
		fmt.Printf("\n")
		fmt.Printf("Summary for %s:\n", ver)
		total := len(results)
		successPct := 0.0
		failPct := 0.0
		if total > 0 {
			successPct = float64(successCount) / float64(total) * 100
			failPct = float64(failCount) / float64(total) * 100
		}
		fmt.Printf("  Total:   %d\n", total)
		fmt.Printf("  Success: %d (%.1f%%)\n", successCount, successPct)
		fmt.Printf("  Failed:  %d (%.1f%%)\n", failCount, failPct)
		fmt.Printf("\n")

		totalSuccess += successCount
		totalFail += failCount
		if failCount > 0 {
			hasFailures = true
		}

		// Add to JSON bundle
		vb := versionBlock{Version: ver, Results: results}
		vb.Summary.Total = len(results)
		vb.Summary.Success = successCount
		vb.Summary.Failed = failCount
		jsonBundle.Versions = append(jsonBundle.Versions, vb)
	}

	// Overall summary if testing multiple versions
	if len(versionsToTest) > 1 {
		fmt.Printf("=== Overall Summary ===\n")
		fmt.Printf("Versions tested: %d\n", len(versionsToTest))
		fmt.Printf("Total tests:     %d\n", totalSuccess+totalFail)
		fmt.Printf("Total success:   %d\n", totalSuccess)
		fmt.Printf("Total failed:    %d\n", totalFail)
	}

	// Finalize bundle totals once
	jsonBundle.Total.Versions = len(jsonBundle.Versions)
	jsonBundle.Total.Tests = totalSuccess + totalFail
	jsonBundle.Total.Success = totalSuccess
	jsonBundle.Total.Failed = totalFail

	// Sort versions for stable output (also affects report tables)
	sort.Slice(jsonBundle.Versions, func(i, j int) bool { return jsonBundle.Versions[i].Version < jsonBundle.Versions[j].Version })

	// Write JSON if requested
	if jsonOut != "" {
		if err := writeJSON(jsonOut, jsonBundle, verbose); err != nil {
			fmt.Fprintf(os.Stderr, "%v\n", err)
			os.Exit(1)
		}
	}

	// Render HTML/Markdown if requested using templates
	report := buildReportData(jsonBundle)
	if htmlOut != "" {
		out, err := renderHTMLTemplate(report)
		if err != nil {
			fmt.Fprintf(os.Stderr, "render html: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(htmlOut, []byte(out), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write html: %v\n", err)
			os.Exit(1)
		}
		if verbose {
			fmt.Fprintf(os.Stderr, "HTML report written to %s\n", htmlOut)
		}
	}
	if mdOut != "" {
		out, err := renderMDTemplate(report)
		if err != nil {
			fmt.Fprintf(os.Stderr, "render markdown: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(mdOut, []byte(out), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write markdown: %v\n", err)
			os.Exit(1)
		}
		if verbose {
			fmt.Fprintf(os.Stderr, "Markdown report written to %s\n", mdOut)
		}
	}

	// At end of summary, show links to generated reports if any
	if htmlOut != "" || mdOut != "" {
		fmt.Printf("Reports:\n")
		if htmlOut != "" {
			fmt.Printf("  HTML: %s\n", mustAbs(htmlOut))
		}
		if mdOut != "" {
			fmt.Printf("  Markdown: %s\n", mustAbs(mdOut))
		}
	}

	// Optionally fail the process when validations failed
	if failOnErrors && hasFailures {
		os.Exit(1)
	}
}

func writeJSON(path string, bundle interface{}, verbose bool) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create JSON: %w", err)
	}
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(bundle); err != nil {
		f.Close()
		return fmt.Errorf("write JSON: %w", err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("close JSON: %w", err)
	}
	return nil
}

func collectJSONLFiles(paths []string) ([]string, error) {
	var files []string
	seen := map[string]bool{}
	for _, p := range paths {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		// Expand simple globs too
		if hasGlob(p) {
			matches, err := filepath.Glob(p)
			if err != nil {
				return nil, fmt.Errorf("invalid glob %q: %w", p, err)
			}
			for _, m := range matches {
				if addJSONL(&files, seen, m) {
					continue
				}
			}
			continue
		}
		info, err := os.Stat(p)
		if err != nil {
			return nil, fmt.Errorf("stat %s: %w", p, err)
		}
		if info.IsDir() {
			err := filepath.Walk(p, func(fp string, fi os.FileInfo, err error) error {
				if err != nil {
					return err
				}
				if !fi.IsDir() && strings.HasSuffix(fp, ".jsonl") {
					addJSONL(&files, seen, fp)
				}
				return nil
			})
			if err != nil {
				return nil, fmt.Errorf("walk %s: %w", p, err)
			}
		} else {
			addJSONL(&files, seen, p)
		}
	}
	return files, nil
}

func addJSONL(files *[]string, seen map[string]bool, path string) bool {
	if !strings.HasSuffix(path, ".jsonl") {
		return false
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		abs = path
	}
	if !seen[abs] {
		*files = append(*files, abs)
		seen[abs] = true
	}
	return true
}

func hasGlob(s string) bool {
	return strings.ContainsAny(s, "*?[")
}

func uniqStrings(xs []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(xs))
	for _, x := range xs {
		if !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	return out
}

func renderHTML(b struct {
	Versions []versionBlock `json:"versions"`
	Total    struct {
		Versions int `json:"versions"`
		Tests    int `json:"tests"`
		Success  int `json:"success"`
		Failed   int `json:"failed"`
	} `json:"total"`
}) string {
	var sb strings.Builder
	sb.WriteString("<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Ground Truth Report</title>")
	sb.WriteString(`<style>
body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; }
header { padding: 16px 24px; border-bottom: 1px solid #e5e7eb; }
header h1 { margin: 0; font-size: 20px; }
header .meta { color: #555; margin-top: 4px; }
.layout { display: grid; grid-template-columns: 240px 1fr; gap: 24px; }
nav.sidebar { border-right: 1px solid #e5e7eb; padding: 16px; position: sticky; top: 0; align-self: start; height: 100vh; overflow: auto; }
nav.sidebar h2 { margin: 0 0 8px 0; font-size: 16px; }
nav.sidebar ul { list-style: none; padding-left: 0; margin: 0; }
nav.sidebar li { margin: 4px 0; }
nav.sidebar a, nav.sidebar label { text-decoration: none; color: #2563eb; cursor: pointer; display: block; }
main.content { padding: 16px 24px 32px; }
.version { display: none; }
input.ver-sel { display: none; }
.section-header { margin: 0 0 8px 0; }
.section-meta { color: #555; margin: 0 0 16px 0; }
table { border-collapse: collapse; width: 100%; margin-bottom: 32px; }
th, td { border: 1px solid #ddd; padding: 8px; }
th { background: #f7f7f7; text-align: left; }
.ok { color: #0a7a31; font-weight: 600; }
.fail { color: #c62828; font-weight: 600; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 12px; }
.badge-ok { background: #e6f4ea; color: #0a7a31; }
.badge-fail { background: #fdecea; color: #c62828; }
@media (max-width: 900px) { .layout { grid-template-columns: 1fr; } nav.sidebar { position: static; height: auto; border-right: 0; border-bottom: 1px solid #e5e7eb; } }
</style>`)
	sb.WriteString("</head><body>")
	sb.WriteString("<header>")
	sb.WriteString("<h1>Ground Truth Validation Report</h1>")
	sb.WriteString(fmt.Sprintf("<div class=\"meta\">Versions: %d &nbsp;&nbsp; Tests: %d &nbsp;&nbsp; <span class=\"badge badge-ok\">Success: %d</span> &nbsp;&nbsp; <span class=\"badge badge-fail\">Failed: %d</span></div>", b.Total.Versions, b.Total.Tests, b.Total.Success, b.Total.Failed))
	sb.WriteString("</header>")

	// No-JS radio toggles for selecting a version; first version is selected by default
	if len(b.Versions) > 0 {
		sb.WriteString("<div aria-hidden=\"true\">")
		sb.WriteString("<input type=\"radio\" name=\"ver\" id=\"sel-all\" class=\"ver-sel\">")
		for i, v := range b.Versions {
			id := anchorID(v.Version)
			checked := ""
			if i == 0 {
				checked = " checked"
			}
			sb.WriteString(fmt.Sprintf("<input type=\"radio\" name=\"ver\" id=\"sel-%s\" class=\"ver-sel\"%s>", html.EscapeString(id), checked))
		}
		// Dynamic CSS mapping radios to sections
		sb.WriteString("<style>")
		sb.WriteString("#sel-all:checked ~ .layout .content .version { display: block; }")
		for _, v := range b.Versions {
			id := anchorID(v.Version)
			sb.WriteString(fmt.Sprintf("#sel-%s:checked ~ .layout .content #%s { display: block; }", html.EscapeString(id), html.EscapeString(id)))
		}
		sb.WriteString("</style>")
		sb.WriteString("</div>")
	}

	sb.WriteString("<div class=\"layout\">")
	sb.WriteString("<nav class=\"sidebar\"><h2>Versions</h2><ul>")
	// Add All Versions view at top (label toggles radio)
	sb.WriteString("<li><label for=\"sel-all\">All Versions</label></li>")
	for _, v := range b.Versions {
		id := anchorID(v.Version)
		sb.WriteString(fmt.Sprintf("<li><label for=\"sel-%s\">%s</label></li>", html.EscapeString(id), html.EscapeString(v.Version)))
	}
	sb.WriteString("</ul></nav>")

	sb.WriteString("<main class=\"content\">")
	for _, v := range b.Versions {
		id := anchorID(v.Version)
		sb.WriteString(fmt.Sprintf("<section id=\"%s\" class=\"version\">", html.EscapeString(id)))
		sb.WriteString(fmt.Sprintf("<h2 class=\"section-header\">Version %s</h2>", html.EscapeString(v.Version)))
		sb.WriteString(fmt.Sprintf("<div class=\"section-meta\">Total: %d &nbsp;&nbsp; <span class=\"badge badge-ok\">Success: %d</span> &nbsp;&nbsp; <span class=\"badge badge-fail\">Failed: %d</span></div>", v.Summary.Total, v.Summary.Success, v.Summary.Failed))
		sb.WriteString("<table><thead><tr><th>State</th><th>Direction</th><th>Packet Name</th><th>ID</th><th>Status</th><th>Notes / Errors</th></tr></thead><tbody>")
		for _, r := range v.Results {
			status := "<span class=\"ok\">OK</span>"
			if !r.Success {
				status = "<span class=\"fail\">FAILED</span>"
			}
			notes := html.EscapeString(strings.Join(r.Errors, "\n"))
			if r.Success && r.Description != "" {
				notes = html.EscapeString(r.Description)
			}
			sb.WriteString("<tr>")
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.State)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.Direction)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.PacketName)))
			sb.WriteString(fmt.Sprintf("<td>%d</td>", r.PacketID))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", status))
			sb.WriteString(fmt.Sprintf("<td><pre style=\"white-space:pre-wrap; margin:0\">%s</pre></td>", notes))
			sb.WriteString("</tr>")
		}
		sb.WriteString("</tbody></table>")
		sb.WriteString("</section>")
	}
	// All Versions aggregated view
	sb.WriteString("<section id=\"all-versions\" class=\"version\">")
	sb.WriteString("<h2 class=\"section-header\">All Versions</h2>")
	sb.WriteString(fmt.Sprintf("<div class=\"section-meta\">Versions: %d &nbsp;&nbsp; Tests: %d &nbsp;&nbsp; <span class=\"badge badge-ok\">Success: %d</span> &nbsp;&nbsp; <span class=\"badge badge-fail\">Failed: %d</span></div>", b.Total.Versions, b.Total.Tests, b.Total.Success, b.Total.Failed))
	for _, v := range b.Versions {
		sb.WriteString(fmt.Sprintf("<h3>Version %s</h3>", html.EscapeString(v.Version)))
		sb.WriteString(fmt.Sprintf("<div class=\"section-meta\">Total: %d &nbsp;&nbsp; <span class=\"badge badge-ok\">Success: %d</span> &nbsp;&nbsp; <span class=\"badge badge-fail\">Failed: %d</span></div>", v.Summary.Total, v.Summary.Success, v.Summary.Failed))
		sb.WriteString("<table><thead><tr><th>State</th><th>Direction</th><th>Packet Name</th><th>ID</th><th>Status</th><th>Notes / Errors</th></tr></thead><tbody>")
		for _, r := range v.Results {
			status := "<span class=\"ok\">OK</span>"
			if !r.Success {
				status = "<span class=\"fail\">FAILED</span>"
			}
			notes := html.EscapeString(strings.Join(r.Errors, "\n"))
			if r.Success && r.Description != "" {
				notes = html.EscapeString(r.Description)
			}
			sb.WriteString("<tr>")
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.State)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.Direction)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.PacketName)))
			sb.WriteString(fmt.Sprintf("<td>%d</td>", r.PacketID))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", status))
			sb.WriteString(fmt.Sprintf("<td><pre style=\"white-space:pre-wrap; margin:0\">%s</pre></td>", notes))
			sb.WriteString("</tr>")
		}
		sb.WriteString("</tbody></table>")
	}
	sb.WriteString("</section>")
	sb.WriteString("</main></div>")
	sb.WriteString("</body></html>")
	return sb.String()
}

func renderMarkdown(b struct {
	Versions []versionBlock `json:"versions"`
	Total    struct {
		Versions int `json:"versions"`
		Tests    int `json:"tests"`
		Success  int `json:"success"`
		Failed   int `json:"failed"`
	} `json:"total"`
}) string {
	// Use embedded HTML to enable a no-JS sidebar layout in Markdown renderers
	var sb strings.Builder
	sb.WriteString("<style>\n")
	sb.WriteString("body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; }\n")
	sb.WriteString(".layout { display: grid; grid-template-columns: 240px 1fr; gap: 24px; }\n")
	sb.WriteString("nav.sidebar { border-right: 1px solid #e5e7eb; padding: 16px; position: sticky; top: 0; align-self: start; height: 100vh; overflow: auto; }\n")
	sb.WriteString("nav.sidebar ul { list-style: none; padding-left: 0; margin: 0; }\n")
	sb.WriteString("nav.sidebar li { margin: 4px 0; }\n")
	sb.WriteString("nav.sidebar a, nav.sidebar label { text-decoration: none; color: #2563eb; cursor: pointer; display: block; }\n")
	sb.WriteString(".version { display: none; }\n")
	sb.WriteString("input.ver-sel { display: none; }\n")
	sb.WriteString("table { border-collapse: collapse; width: 100%; }\n")
	sb.WriteString("th, td { border: 1px solid #ddd; padding: 8px; }\n")
	sb.WriteString("th { background: #f7f7f7; text-align: left; }\n")
	sb.WriteString(".ok { color: #0a7a31; font-weight: 600; } .fail { color: #c62828; font-weight: 600; }\n")
	sb.WriteString("@media (max-width: 900px) { .layout { grid-template-columns: 1fr; } nav.sidebar { position: static; height: auto; border-right: 0; border-bottom: 1px solid #e5e7eb; } }\n")
	sb.WriteString("</style>\n")

	sb.WriteString("<div><h1>Ground Truth Validation Report</h1>")
	sb.WriteString(fmt.Sprintf("<div>Versions: %d &nbsp;&nbsp; Tests: %d &nbsp;&nbsp; Success: %d &nbsp;&nbsp; Failed: %d</div>", b.Total.Versions, b.Total.Tests, b.Total.Success, b.Total.Failed))
	sb.WriteString("</div>")

	// No-JS radio toggles for selecting a version
	if len(b.Versions) > 0 {
		sb.WriteString("<div aria-hidden=\"true\">")
		sb.WriteString("<input type=\"radio\" name=\"ver\" id=\"sel-all\" class=\"ver-sel\">")
		for i, v := range b.Versions {
			id := anchorID(v.Version)
			checked := ""
			if i == 0 {
				checked = " checked"
			}
			sb.WriteString(fmt.Sprintf("<input type=\"radio\" name=\"ver\" id=\"sel-%s\" class=\"ver-sel\"%s>", html.EscapeString(id), checked))
		}
		sb.WriteString("<style>")
		sb.WriteString("#sel-all:checked ~ .layout .content .version { display: block; }")
		for _, v := range b.Versions {
			id := anchorID(v.Version)
			sb.WriteString(fmt.Sprintf("#sel-%s:checked ~ .layout .content #%s { display: block; }", html.EscapeString(id), html.EscapeString(id)))
		}
		sb.WriteString("</style>")
		sb.WriteString("</div>")
	}

	sb.WriteString("<div class=\"layout\">")
	sb.WriteString("<nav class=\"sidebar\"><h2>Versions</h2><ul>")
	sb.WriteString("<li><label for=\"sel-all\">All Versions</label></li>")
	for _, v := range b.Versions {
		id := anchorID(v.Version)
		sb.WriteString(fmt.Sprintf("<li><label for=\"sel-%s\">%s</label></li>", html.EscapeString(id), html.EscapeString(v.Version)))
	}
	sb.WriteString("</ul></nav>")

	sb.WriteString("<main class=\"content\">")
	for _, v := range b.Versions {
		id := anchorID(v.Version)
		sb.WriteString(fmt.Sprintf("<section id=\"%s\" class=\"version\">", html.EscapeString(id)))
		sb.WriteString(fmt.Sprintf("<h2>Version %s</h2>", html.EscapeString(v.Version)))
		sb.WriteString(fmt.Sprintf("<div>Total: %d &nbsp;&nbsp; Success: %d &nbsp;&nbsp; Failed: %d</div>", v.Summary.Total, v.Summary.Success, v.Summary.Failed))
		sb.WriteString("<table><thead><tr><th>State</th><th>Direction</th><th>Packet Name</th><th>ID</th><th>Status</th><th>Notes / Errors</th></tr></thead><tbody>")
		for _, r := range v.Results {
			status := "<span class=\"ok\">OK</span>"
			if !r.Success {
				status = "<span class=\"fail\">FAILED</span>"
			}
			notes := html.EscapeString(strings.Join(r.Errors, "\n"))
			if r.Success && r.Description != "" {
				notes = html.EscapeString(r.Description)
			}
			sb.WriteString("<tr>")
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.State)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.Direction)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.PacketName)))
			sb.WriteString(fmt.Sprintf("<td>%d</td>", r.PacketID))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", status))
			sb.WriteString(fmt.Sprintf("<td><pre style=\"white-space:pre-wrap; margin:0\">%s</pre></td>", notes))
			sb.WriteString("</tr>")
		}
		sb.WriteString("</tbody></table>")
		sb.WriteString("</section>")
	}
	// All Versions aggregated section
	sb.WriteString("<section id=\"all-versions\" class=\"version\">")
	sb.WriteString("<h2>All Versions</h2>")
	sb.WriteString(fmt.Sprintf("<div>Versions: %d &nbsp;&nbsp; Tests: %d &nbsp;&nbsp; Success: %d &nbsp;&nbsp; Failed: %d</div>", b.Total.Versions, b.Total.Tests, b.Total.Success, b.Total.Failed))
	for _, v := range b.Versions {
		sb.WriteString(fmt.Sprintf("<h3>Version %s</h3>", html.EscapeString(v.Version)))
		sb.WriteString(fmt.Sprintf("<div>Total: %d &nbsp;&nbsp; Success: %d &nbsp;&nbsp; Failed: %d</div>", v.Summary.Total, v.Summary.Success, v.Summary.Failed))
		sb.WriteString("<table><thead><tr><th>State</th><th>Direction</th><th>Packet Name</th><th>ID</th><th>Status</th><th>Notes / Errors</th></tr></thead><tbody>")
		for _, r := range v.Results {
			status := "<span class=\"ok\">OK</span>"
			if !r.Success {
				status = "<span class=\"fail\">FAILED</span>"
			}
			notes := html.EscapeString(strings.Join(r.Errors, "\n"))
			if r.Success && r.Description != "" {
				notes = html.EscapeString(r.Description)
			}
			sb.WriteString("<tr>")
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.State)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.Direction)))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", html.EscapeString(r.PacketName)))
			sb.WriteString(fmt.Sprintf("<td>%d</td>", r.PacketID))
			sb.WriteString(fmt.Sprintf("<td>%s</td>", status))
			sb.WriteString(fmt.Sprintf("<td><pre style=\"white-space:pre-wrap; margin:0\">%s</pre></td>", notes))
			sb.WriteString("</tr>")
		}
		sb.WriteString("</tbody></table>")
	}
	sb.WriteString("</section>")
	sb.WriteString("</main></div>")
	return sb.String()
}

// anchorID converts a version string to a safe HTML id
func anchorID(ver string) string {
	ver = strings.ToLower(ver)
	var b strings.Builder
	b.WriteString("v-")
	prevDash := false
	for _, r := range ver {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			prevDash = false
		} else {
			if !prevDash {
				b.WriteByte('-')
				prevDash = true
			}
		}
	}
	return b.String()
}

func mustAbs(p string) string {
	if p == "" {
		return p
	}
	if abs, err := filepath.Abs(p); err == nil {
		return abs
	}
	return p
}

func loadConfig(path string) (*generator.Config, error) {
	cfg, err := generator.LoadConfig(path)
	if err != nil {
		if os.IsNotExist(err) {
			fmt.Printf("Config file not found at %s, using default configuration\n", path)
			return generator.DefaultConfig(), nil
		}
		return nil, err
	}
	return cfg, nil
}
