// Generated by gen_protocol (baseTypesHeader). DO NOT EDIT
package basetypes

import (
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/reallyoldfogie/mc-protocol-go/models"
)

type U64 = models.UInt64

type I32 = pk.Int

type ByteArray = pk.ByteArray

type GameProfilePropertiesArrayTypeSignature = models.Option[pk.String]

type bool = pk.Boolean

type I8 = pk.Byte

type Varint = pk.VarInt

type F32 = pk.Float

type ChatSession = models.Option[models.Void]

type PreviousMessages = models.Array[pk.VarInt, PreviousMessagesPreviousMessagesElement]

type I16 = pk.Short

type ContainerID = pk.VarInt

type SlotComponentDataBlocksAttacksDamageReductionsArrayTypeType = models.Option[IDSet]

type SlotComponentDataBlocksAttacksBypassedBy = models.Option[pk.String]

type SlotComponentDataBlocksAttacksBlockSound = models.Option[ItemSoundHolder]

type SlotComponentDataBlocksAttacksDisableSound = models.Option[ItemSoundHolder]

type SlotComponentDataUseCooldownCooldownGroup = models.Option[pk.String]

type SlotComponentDataPotionContentsPotionId = models.Option[pk.VarInt]

type SlotComponentDataPotionContentsCustomColor = models.Option[pk.Int]

type SlotComponentDataPotionContentsCustomName = models.Option[pk.String]

type SlotComponentDataWrittenBookContentFilteredTitle = models.Option[pk.String]

type SlotComponentDataProfileName = models.Option[pk.String]

type SlotComponentDataProfileUuid = models.Option[pk.UUID]

type SlotComponentDataProfilePropertiesArrayTypeSignature = models.Option[pk.String]

type SlotComponentDataToolRulesArrayTypeSpeed = models.Option[pk.Float]

type SlotComponentDataToolRulesArrayTypeCorrectDropForBlocks = models.Option[pk.Boolean]

type SlotComponentDataEquippableModel = models.Option[pk.String]

type SlotComponentDataEquippableCameraOverlay = models.Option[pk.String]

type SlotComponentDataEquippableAllowedEntities = models.Option[IDSet]

type ExactComponentMatcher = models.Array[pk.VarInt, SlotComponent]

type Optvarint = pk.VarInt

type F64 = pk.Double

type Ingredient = models.Array[pk.VarInt, Slot]

type U16 = pk.UnsignedShort

type U32 = models.UInt32

type I64 = pk.Long
