// Generated by gen_protocol (baseTypesHeader). DO NOT EDIT
package basetypes

import (
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/models"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "key",
//	      "type": "string"
//	    },
//	    {
//	      "name": "value",
//	      "type": "string"
//	    }
//	  ]
//	]
type ArmorTrimMaterialOverrideArmorAssetsArrayType struct {
	// "string"
	Key pk.String
	// "string"
	Value pk.String
}

func (t *ArmorTrimMaterialOverrideArmorAssetsArrayType) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Key.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Key")
	}
	bytesRead, err = t.Value.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Value")
	}

	return totalBytes, nil
}

func (t ArmorTrimMaterialOverrideArmorAssetsArrayType) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[ArmorTrimMaterialOverrideArmorAssetsArrayType.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Key.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Value.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "assetBase",
//	      "type": "string"
//	    },
//	    {
//	      "name": "overrideArmorAssets",
//	      "type": [
//	        "array",
//	        {
//	          "countType": "varint",
//	          "type": [
//	            "container",
//	            [
//	              {
//	                "name": "key",
//	                "type": "string"
//	              },
//	              {
//	                "name": "value",
//	                "type": "string"
//	              }
//	            ]
//	          ]
//	        }
//	      ]
//	    },
//	    {
//	      "name": "description",
//	      "type": "anonymousNbt"
//	    }
//	  ]
//	]
type ArmorTrimMaterial struct {
	// "string"
	AssetBase pk.String
	// [
	//             "array",
	//             {
	//               "countType": "varint",
	//               "type": [
	//                 "container",
	//                 [
	//                   {
	//                     "name": "key",
	//                     "type": "string"
	//                   },
	//                   {
	//                     "name": "value",
	//                     "type": "string"
	//                   }
	//                 ]
	//               ]
	//             }
	//           ]
	OverrideArmorAssets models.Array[pk.VarInt, ArmorTrimMaterialOverrideArmorAssetsArrayType]
	// "anonymousNbt"
	Description models.AnonymousNBT
}

func (t *ArmorTrimMaterial) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.AssetBase.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field AssetBase")
	}
	bytesRead, err = t.OverrideArmorAssets.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field OverrideArmorAssets")
	}
	bytesRead, err = t.Description.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Description")
	}

	return totalBytes, nil
}

func (t ArmorTrimMaterial) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[ArmorTrimMaterial.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.AssetBase.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.OverrideArmorAssets.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Description.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "assetId",
//	      "type": "string"
//	    },
//	    {
//	      "name": "description",
//	      "type": "anonymousNbt"
//	    },
//	    {
//	      "name": "decal",
//	      "type": "bool"
//	    }
//	  ]
//	]
type ArmorTrimPattern struct {
	// "string"
	AssetId pk.String
	// "anonymousNbt"
	Description models.AnonymousNBT
	// "bool"
	Decal pk.Boolean
}

func (t *ArmorTrimPattern) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.AssetId.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field AssetId")
	}
	bytesRead, err = t.Description.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Description")
	}
	bytesRead, err = t.Decal.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Decal")
	}

	return totalBytes, nil
}

func (t ArmorTrimPattern) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[ArmorTrimPattern.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.AssetId.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Description.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Decal.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
