// Generated by gen_protocol (baseTypesHeader). DO NOT EDIT
package basetypes

import (
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/reallyoldfogie/mc-protocol-go/models"
)

type SlotComponentDataUseCooldownCooldownGroup = models.Option[pk.String]

type SlotComponentDataToolRulesArrayTypeSpeed = models.Option[pk.Float]

type SlotComponentDataToolRulesArrayTypeCorrectDropForBlocks = models.Option[pk.Boolean]

type SlotComponentDataProfileName = models.Option[pk.String]

type SlotComponentDataProfileUuid = models.Option[pk.UUID]

type SlotComponentDataProfilePropertiesArrayTypeSignature = models.Option[pk.String]

type SlotComponentDataEquippableModel = models.Option[pk.String]

type SlotComponentDataEquippableCameraOverlay = models.Option[pk.String]

type SlotComponentDataEquippableAllowedEntities = models.Option[IDSet]

type SlotComponentDataWrittenBookContentFilteredTitle = models.Option[pk.String]

type SlotComponentDataPotionContentsPotionId = models.Option[pk.VarInt]

type SlotComponentDataPotionContentsCustomColor = models.Option[pk.Int]

type SlotComponentDataPotionContentsCustomName = models.Option[pk.String]

type SlotComponentDataLore = models.Array[pk.VarInt, models.AnonymousNBT]

type ChatSession = models.Option[ChatSessionData]

type I16 = pk.Short

type F32 = pk.Float

type ByteArray = pk.ByteArray

type I8 = pk.Byte

type PreviousMessages = models.Array[pk.VarInt, PreviousMessagesPreviousMessagesElement]

type GameProfilePropertiesArrayTypeSignature = models.Option[pk.String]

type ContainerID = pk.VarInt

type U32 = models.UInt32

type Ingredient = models.Array[pk.VarInt, Slot]

type U16 = pk.UnsignedShort

type U64 = models.UInt64

type F64 = pk.Double

type bool = pk.Boolean

type Varint = pk.VarInt

type I32 = pk.Int

type Optvarint = pk.VarInt

type I64 = pk.Long
