// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"bytes"
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"github.com/reallyoldfogie/mc-protocol-go/models"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "feet_eyes",
//	      "type": "varint"
//	    },
//	    {
//	      "name": "x",
//	      "type": "f64"
//	    },
//	    {
//	      "name": "y",
//	      "type": "f64"
//	    },
//	    {
//	      "name": "z",
//	      "type": "f64"
//	    },
//	    {
//	      "name": "isEntity",
//	      "type": "bool"
//	    },
//	    {
//	      "name": "entityId",
//	      "type": [
//	        "switch",
//	        {
//	          "compareTo": "isEntity",
//	          "fields": {
//	            "true": "varint"
//	          },
//	          "default": "void"
//	        }
//	      ]
//	    },
//	    {
//	      "name": "entity_feet_eyes",
//	      "type": [
//	        "switch",
//	        {
//	          "compareTo": "isEntity",
//	          "fields": {
//	            "true": "varint"
//	          },
//	          "default": "void"
//	        }
//	      ]
//	    }
//	  ]
//	]
type FacePlayer struct {
	packetID int32
	// "varint"
	FeetEyes pk.VarInt
	// "f64"
	X pk.Double
	// "f64"
	Y pk.Double
	// "f64"
	Z pk.Double
	// "bool"
	IsEntity pk.Boolean
	// [
	//                 "switch",
	//                 {
	//                   "compareTo": "isEntity",
	//                   "fields": {
	//                     "true": "varint"
	//                   },
	//                   "default": "void"
	//                 }
	//               ]
	EntityId pk.Field
	// [
	//                 "switch",
	//                 {
	//                   "compareTo": "isEntity",
	//                   "fields": {
	//                     "true": "varint"
	//                   },
	//                   "default": "void"
	//                 }
	//               ]
	EntityFeetEyes pk.Field
}

// NewFacePlayer creates a new FacePlayer packet with the correct packet ID.
func NewFacePlayer() *FacePlayer {
	return &FacePlayer{packetID: 64}
}

// PacketID returns the protocol ID for this packet type.
func (p *FacePlayer) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *FacePlayer) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *FacePlayer) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.FeetEyes,
		&p.X,
		&p.Y,
		&p.Z,
		&p.IsEntity,
		p.EntityId,
		p.EntityFeetEyes)
}

// Scan deserializes a wire-format packet into this struct.
func (p *FacePlayer) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	// This packet has switch fields, so we read fields individually
	r := bytes.NewReader(packet.Data)
	var totalBytes int64
	var bytesRead int64
	var err error
	bytesRead, err = p.FeetEyes.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return fmt.Errorf("scanning packet field[FeetEyes] error: %w", err)
	}
	bytesRead, err = p.X.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return fmt.Errorf("scanning packet field[X] error: %w", err)
	}
	bytesRead, err = p.Y.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return fmt.Errorf("scanning packet field[Y] error: %w", err)
	}
	bytesRead, err = p.Z.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return fmt.Errorf("scanning packet field[Z] error: %w", err)
	}
	bytesRead, err = p.IsEntity.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return fmt.Errorf("scanning packet field[IsEntity] error: %w", err)
	}
	// Switch field EntityId based on isEntity
	// Convert compareTo value to string for matching
	compareValueEntityId := fmt.Sprintf("%v", p.IsEntity)

	switch compareValueEntityId {
	case "true":
		var val pk.VarInt
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "scanning packet field[EntityId] case true")
		}
		p.EntityId = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "failed to read void switch field EntityId default case")
		}
		p.EntityId = &__void
	}

	// Switch field EntityFeetEyes based on isEntity
	// Convert compareTo value to string for matching
	compareValueEntityFeetEyes := fmt.Sprintf("%v", p.IsEntity)

	switch compareValueEntityFeetEyes {
	case "true":
		var val pk.VarInt
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "scanning packet field[EntityFeetEyes] case true")
		}
		p.EntityFeetEyes = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return errors.Wrap(err, "failed to read void switch field EntityFeetEyes default case")
		}
		p.EntityFeetEyes = &__void
	}

	_ = totalBytes // Unused in Scan()
	return nil
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *FacePlayer) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["FeetEyes"] = &p.FeetEyes
	fields["X"] = &p.X
	fields["Y"] = &p.Y
	fields["Z"] = &p.Z
	fields["IsEntity"] = &p.IsEntity
	fields["EntityId"] = p.EntityId
	fields["EntityFeetEyes"] = p.EntityFeetEyes
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *FacePlayer) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["FeetEyes"]; ok {
		p.FeetEyes = *val.(*pk.VarInt)
	}
	if val, ok := fields["X"]; ok {
		p.X = *val.(*pk.Double)
	}
	if val, ok := fields["Y"]; ok {
		p.Y = *val.(*pk.Double)
	}
	if val, ok := fields["Z"]; ok {
		p.Z = *val.(*pk.Double)
	}
	if val, ok := fields["IsEntity"]; ok {
		p.IsEntity = *val.(*pk.Boolean)
	}
	if val, ok := fields["EntityId"]; ok {
		p.EntityId = val.(pk.Field)
	}
	if val, ok := fields["EntityFeetEyes"]; ok {
		p.EntityFeetEyes = val.(pk.Field)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetFeetEyes returns the FeetEyes field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *FacePlayer) GetFeetEyes() pk.VarInt {
	return p.FeetEyes
}

// SetFeetEyes sets the FeetEyes field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *FacePlayer) SetFeetEyes(val pk.VarInt) {
	p.FeetEyes = val
}

// GetX returns the X field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *FacePlayer) GetX() pk.Double {
	return p.X
}

// SetX sets the X field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *FacePlayer) SetX(val pk.Double) {
	p.X = val
}

// GetY returns the Y field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *FacePlayer) GetY() pk.Double {
	return p.Y
}

// SetY sets the Y field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *FacePlayer) SetY(val pk.Double) {
	p.Y = val
}

// GetZ returns the Z field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *FacePlayer) GetZ() pk.Double {
	return p.Z
}

// SetZ sets the Z field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *FacePlayer) SetZ(val pk.Double) {
	p.Z = val
}

// GetIsEntity returns the IsEntity field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *FacePlayer) GetIsEntity() pk.Boolean {
	return p.IsEntity
}

// SetIsEntity sets the IsEntity field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *FacePlayer) SetIsEntity(val pk.Boolean) {
	p.IsEntity = val
}

// GetEntityId returns the EntityId field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *FacePlayer) GetEntityId() pk.Field {
	return p.EntityId
}

// SetEntityId sets the EntityId field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *FacePlayer) SetEntityId(val pk.Field) {
	p.EntityId = val
}

// GetEntityFeetEyes returns the EntityFeetEyes field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *FacePlayer) GetEntityFeetEyes() pk.Field {
	return p.EntityFeetEyes
}

// SetEntityFeetEyes sets the EntityFeetEyes field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *FacePlayer) SetEntityFeetEyes(val pk.Field) {
	p.EntityFeetEyes = val
}

func (t *FacePlayer) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.FeetEyes.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field FeetEyes")
	}
	bytesRead, err = t.X.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field X")
	}
	bytesRead, err = t.Y.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Y")
	}
	bytesRead, err = t.Z.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Z")
	}
	bytesRead, err = t.IsEntity.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field IsEntity")
	}
	// Switch field EntityId based on isEntity
	// Convert compareTo value to string for matching
	compareValueEntityId := fmt.Sprintf("%v", t.IsEntity)

	switch compareValueEntityId {
	case "true":
		var val pk.VarInt
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read switch field EntityId case true")
		}
		t.EntityId = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read void switch field EntityId default case")
		}
		t.EntityId = &__void
	}

	// Switch field EntityFeetEyes based on isEntity
	// Convert compareTo value to string for matching
	compareValueEntityFeetEyes := fmt.Sprintf("%v", t.IsEntity)

	switch compareValueEntityFeetEyes {
	case "true":
		var val pk.VarInt
		bytesRead, err = val.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read switch field EntityFeetEyes case true")
		}
		t.EntityFeetEyes = &val
	default:
		// Void case - no data to read
		var __void models.Void
		bytesRead, err = __void.ReadFrom(r)
		totalBytes += bytesRead
		if err != nil {
			return totalBytes, errors.Wrap(err, "failed to read void switch field EntityFeetEyes default case")
		}
		t.EntityFeetEyes = &__void
	}

	return totalBytes, nil
}

func (t FacePlayer) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[FacePlayer.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.FeetEyes.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.X.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Y.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Z.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.IsEntity.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	// Switch field EntityId based on isEntity
	if t.EntityId != nil {
		// Write switch field value if it implements WriteTo
		if writer, ok := t.EntityId.(interface {
			WriteTo(io.Writer) (int64, error)
		}); ok {
			bytesWritten, err = writer.WriteTo(w)
			totalBytes += bytesWritten
			if err != nil {
				return totalBytes, err
			}
		} else {
			// Not a void case and doesn't implement WriteTo
			return totalBytes, fmt.Errorf("switch field EntityId value does not implement WriteTo: %T", t.EntityId)
		}
	}
	// Switch field EntityFeetEyes based on isEntity
	if t.EntityFeetEyes != nil {
		// Write switch field value if it implements WriteTo
		if writer, ok := t.EntityFeetEyes.(interface {
			WriteTo(io.Writer) (int64, error)
		}); ok {
			bytesWritten, err = writer.WriteTo(w)
			totalBytes += bytesWritten
			if err != nil {
				return totalBytes, err
			}
		} else {
			// Not a void case and doesn't implement WriteTo
			return totalBytes, fmt.Errorf("switch field EntityFeetEyes value does not implement WriteTo: %T", t.EntityFeetEyes)
		}
	}
	return totalBytes, nil
}
