// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
)

type PacketName struct {
	Value string
}

var PacketNameMappings = map[int64]string{
	0x00: "teleport_confirm",
	0x01: "query_block_nbt",
	0x02: "set_difficulty",
	0x03: "message_acknowledgement",
	0x04: "chat_command",
	0x05: "chat_command_signed",
	0x06: "chat_message",
	0x07: "chat_session_update",
	0x08: "chunk_batch_received",
	0x09: "client_command",
	0x0a: "settings",
	0x0b: "tab_complete",
	0x0c: "configuration_acknowledged",
	0x0d: "enchant_item",
	0x0e: "window_click",
	0x0f: "close_window",
	0x10: "set_slot_state",
	0x11: "cookie_response",
	0x12: "custom_payload",
	0x13: "debug_sample_subscription",
	0x14: "edit_book",
	0x15: "query_entity_nbt",
	0x16: "use_entity",
	0x17: "generate_structure",
	0x18: "keep_alive",
	0x19: "lock_difficulty",
	0x1a: "position",
	0x1b: "position_look",
	0x1c: "look",
	0x1d: "flying",
	0x1e: "vehicle_move",
	0x1f: "steer_boat",
	0x20: "pick_item",
	0x21: "ping_request",
	0x22: "craft_recipe_request",
	0x23: "abilities",
	0x24: "block_dig",
	0x25: "entity_action",
	0x26: "steer_vehicle",
	0x27: "pong",
	0x28: "recipe_book",
	0x29: "displayed_recipe",
	0x2a: "name_item",
	0x2b: "resource_pack_receive",
	0x2c: "advancement_tab",
	0x2d: "select_trade",
	0x2e: "set_beacon_effect",
	0x2f: "held_item_slot",
	0x30: "update_command_block",
	0x31: "update_command_block_minecart",
	0x32: "set_creative_slot",
	0x33: "update_jigsaw_block",
	0x34: "update_structure_block",
	0x35: "update_sign",
	0x36: "arm_animation",
	0x37: "spectate",
	0x38: "block_place",
	0x39: "use_item",
}

func (m *PacketName) ReadFrom(r io.Reader) (int64, error) {
	var key pk.VarInt
	n, err := key.ReadFrom(r)
	if err != nil {
		return n, errors.Wrap(err, "failed to read PacketName key")
	}

	value, ok := PacketNameMappings[int64(key)]
	if !ok {
		// Use numeric key as fallback for unknown/undocumented values
		m.Value = fmt.Sprintf("unknown_%d", key)
		return n, nil
	}
	m.Value = value
	return n, nil
}

func (m PacketName) WriteTo(w io.Writer) (int64, error) {
	for k, v := range PacketNameMappings {
		if v == m.Value {
			key := pk.VarInt(k)
			return key.WriteTo(w)
		}
	}
	return 0, errors.Errorf("unknown PacketName value: %s", m.Value)
}
