// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "sideways",
//	      "type": "f32"
//	    },
//	    {
//	      "name": "forward",
//	      "type": "f32"
//	    },
//	    {
//	      "name": "jump",
//	      "type": "u8"
//	    }
//	  ]
//	]
type SteerVehicle struct {
	packetID int32
	// "f32"
	Sideways pk.Float
	// "f32"
	Forward pk.Float
	// "u8"
	Jump pk.UnsignedByte
}

// NewSteerVehicle creates a new SteerVehicle packet with the correct packet ID.
func NewSteerVehicle() *SteerVehicle {
	return &SteerVehicle{packetID: 38}
}

// PacketID returns the protocol ID for this packet type.
func (p *SteerVehicle) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *SteerVehicle) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *SteerVehicle) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.Sideways,
		&p.Forward,
		&p.Jump)
}

// Scan deserializes a wire-format packet into this struct.
func (p *SteerVehicle) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.Sideways,
		&p.Forward,
		&p.Jump)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *SteerVehicle) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["Sideways"] = &p.Sideways
	fields["Forward"] = &p.Forward
	fields["Jump"] = &p.Jump
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *SteerVehicle) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["Sideways"]; ok {
		p.Sideways = *val.(*pk.Float)
	}
	if val, ok := fields["Forward"]; ok {
		p.Forward = *val.(*pk.Float)
	}
	if val, ok := fields["Jump"]; ok {
		p.Jump = *val.(*pk.UnsignedByte)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetSideways returns the Sideways field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SteerVehicle) GetSideways() pk.Float {
	return p.Sideways
}

// SetSideways sets the Sideways field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SteerVehicle) SetSideways(val pk.Float) {
	p.Sideways = val
}

// GetForward returns the Forward field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SteerVehicle) GetForward() pk.Float {
	return p.Forward
}

// SetForward sets the Forward field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SteerVehicle) SetForward(val pk.Float) {
	p.Forward = val
}

// GetJump returns the Jump field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *SteerVehicle) GetJump() pk.UnsignedByte {
	return p.Jump
}

// SetJump sets the Jump field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *SteerVehicle) SetJump(val pk.UnsignedByte) {
	p.Jump = val
}

func (t *SteerVehicle) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.Sideways.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Sideways")
	}
	bytesRead, err = t.Forward.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Forward")
	}
	bytesRead, err = t.Jump.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field Jump")
	}

	return totalBytes, nil
}

func (t SteerVehicle) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[SteerVehicle.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.Sideways.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Forward.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.Jump.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
