// Generated by gen_protocol. DO NOT EDIT
package serverbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "bookId",
//	      "type": "varint"
//	    },
//	    {
//	      "name": "bookOpen",
//	      "type": "bool"
//	    },
//	    {
//	      "name": "filterActive",
//	      "type": "bool"
//	    }
//	  ]
//	]
type RecipeBook struct {
	packetID int32
	// "varint"
	BookId pk.VarInt
	// "bool"
	BookOpen pk.Boolean
	// "bool"
	FilterActive pk.Boolean
}

// NewRecipeBook creates a new RecipeBook packet with the correct packet ID.
func NewRecipeBook() *RecipeBook {
	return &RecipeBook{packetID: 40}
}

// PacketID returns the protocol ID for this packet type.
func (p *RecipeBook) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *RecipeBook) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *RecipeBook) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.BookId,
		&p.BookOpen,
		&p.FilterActive)
}

// Scan deserializes a wire-format packet into this struct.
func (p *RecipeBook) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.BookId,
		&p.BookOpen,
		&p.FilterActive)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *RecipeBook) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["BookId"] = p.BookId
	fields["BookOpen"] = p.BookOpen
	fields["FilterActive"] = p.FilterActive
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *RecipeBook) SetFields(fields map[string]pk.FieldEncoder) {
	fmt.Printf("<no value>\n")
	if val, ok := fields["BookId"]; ok {
		p.BookId = val.(pk.VarInt)
	}
	if val, ok := fields["BookOpen"]; ok {
		p.BookOpen = val.(pk.Boolean)
	}
	if val, ok := fields["FilterActive"]; ok {
		p.FilterActive = val.(pk.Boolean)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetBookId returns the BookId field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *RecipeBook) GetBookId() pk.VarInt {
	return p.BookId
}

// SetBookId sets the BookId field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *RecipeBook) SetBookId(val pk.VarInt) {
	p.BookId = val
}

// GetBookOpen returns the BookOpen field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *RecipeBook) GetBookOpen() pk.Boolean {
	return p.BookOpen
}

// SetBookOpen sets the BookOpen field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *RecipeBook) SetBookOpen(val pk.Boolean) {
	p.BookOpen = val
}

// GetFilterActive returns the FilterActive field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *RecipeBook) GetFilterActive() pk.Boolean {
	return p.FilterActive
}

// SetFilterActive sets the FilterActive field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *RecipeBook) SetFilterActive(val pk.Boolean) {
	p.FilterActive = val
}

func (t *RecipeBook) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.BookId.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field BookId")
	}
	bytesRead, err = t.BookOpen.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field BookOpen")
	}
	bytesRead, err = t.FilterActive.ReadFrom(r)
	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field FilterActive")
	}

	return totalBytes, nil
}

func (t RecipeBook) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[RecipeBook.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.BookId.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.BookOpen.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.FilterActive.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
