// Generated by gen_protocol. DO NOT EDIT
package clientbound

import (
	"fmt"
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/pkg/errors"
	"io"
	"log"
)

// Protodef: [
//
//	  "container",
//	  [
//	    {
//	      "name": "chunkZ",
//	      "type": "i32"
//	    },
//	    {
//	      "name": "chunkX",
//	      "type": "i32"
//	    }
//	  ]
//	]
type UnloadChunk struct {
	packetID int32
	// "i32"
	ChunkZ pk.Int
	// "i32"
	ChunkX pk.Int
}

// NewUnloadChunk creates a new UnloadChunk packet with the correct packet ID.
func NewUnloadChunk() *UnloadChunk {
	return &UnloadChunk{packetID: 37}
}

// PacketID returns the protocol ID for this packet type.
func (p *UnloadChunk) PacketID() int32 {
	return p.packetID
}

// SetPacketID sets the protocol ID for this packet type.
// This is used when the same packet structure is reused across multiple stages with different IDs.
func (p *UnloadChunk) SetPacketID(id int32) {
	p.packetID = id
}

// Marshal serializes the packet into wire format.
func (p *UnloadChunk) Marshal() pk.Packet {
	return pk.Marshal(
		p.packetID,
		&p.ChunkZ,
		&p.ChunkX)
}

// Scan deserializes a wire-format packet into this struct.
func (p *UnloadChunk) Scan(packet pk.Packet) error {
	if packet.ID != p.packetID {
		return fmt.Errorf("packet ID mismatch: expected %d, got %d", p.packetID, packet.ID)
	}
	return packet.Scan(
		&p.ChunkZ,
		&p.ChunkX)
}

// GetFields returns a map of all packet fields for version-agnostic access.
// Use this when you need to access fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed getter methods (e.g., GetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountGetter).
func (p *UnloadChunk) GetFields() map[string]pk.FieldEncoder {
	fields := map[string]pk.FieldEncoder{}
	fields["ChunkZ"] = &p.ChunkZ
	fields["ChunkX"] = &p.ChunkX
	return fields
}

// SetFields updates packet fields from a map for version-agnostic access.
// Use this when you need to set fields dynamically or when working with version-specific types
// that don't have stable cross-version interfaces.
//
// For version-specific code with type safety, use the typed setter methods (e.g., SetCount()).
// For semi-agnostic code with fields that have stable types, use the typed interfaces (e.g., CountSetter).
func (p *UnloadChunk) SetFields(fields map[string]pk.FieldEncoder) {
	if val, ok := fields["ChunkZ"]; ok {
		p.ChunkZ = *val.(*pk.Int)
	}
	if val, ok := fields["ChunkX"]; ok {
		p.ChunkX = *val.(*pk.Int)
	}
}

// Typed field accessor methods for version-specific type-safe access
// GetChunkZ returns the ChunkZ field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *UnloadChunk) GetChunkZ() pk.Int {
	return p.ChunkZ
}

// SetChunkZ sets the ChunkZ field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *UnloadChunk) SetChunkZ(val pk.Int) {
	p.ChunkZ = val
}

// GetChunkX returns the ChunkX field value.
// Note: This method returns the actual field type, which may be version-specific.
// For version-agnostic access, use GetFields() or check for typed interfaces.
func (p *UnloadChunk) GetChunkX() pk.Int {
	return p.ChunkX
}

// SetChunkX sets the ChunkX field value.
// Note: This method accepts the actual field type, which may be version-specific.
// For version-agnostic access, use SetFields() or check for typed interfaces.
func (p *UnloadChunk) SetChunkX(val pk.Int) {
	p.ChunkX = val
}

func (t *UnloadChunk) ReadFrom(r io.Reader) (totalBytes int64, err error) {
	var bytesRead int64
	bytesRead, err = t.ChunkZ.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field ChunkZ")
	}
	bytesRead, err = t.ChunkX.ReadFrom(r)

	totalBytes += bytesRead
	if err != nil {
		return totalBytes, errors.Wrap(err, "failed to read field ChunkX")
	}

	return totalBytes, nil
}

func (t UnloadChunk) WriteTo(w io.Writer) (totalBytes int64, err error) {
	var bytesWritten int64

	defer func() {
		log.Printf("[UnloadChunk.WriteTo] totalBytes: %d err: %#v", totalBytes, err)
	}()
	bytesWritten, err = t.ChunkZ.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	bytesWritten, err = t.ChunkX.WriteTo(w)
	totalBytes += bytesWritten
	if err != nil {
		return totalBytes, err
	}
	return totalBytes, nil
}
