// Generated by gen_protocol (baseTypesHeader). DO NOT EDIT
package basetypes

import (
	pk "github.com/Tnze/go-mc/net/packet"
	"github.com/reallyoldfogie/mc-protocol-go/models"
)

type I32 = pk.Int

type bool = pk.Boolean

type ContainerID = pk.VarInt

type GameProfilePropertySignature = models.Option[pk.String]

type ExactComponentMatcher = models.Array[pk.VarInt, SlotComponent]

type PartialResolvableProfileName = models.Option[pk.String]

type PartialResolvableProfileUuid = models.Option[pk.UUID]

type Varint = pk.VarInt

type I8 = pk.Byte

type I16 = pk.Short

type Ingredient = models.Array[pk.VarInt, Slot]

type U16 = pk.UnsignedShort

type U64 = models.UInt64

type ChatSession = models.Option[models.Void]

type I64 = pk.Long

type SlotComponentDataEquippableModel = models.Option[pk.String]

type SlotComponentDataEquippableCameraOverlay = models.Option[pk.String]

type SlotComponentDataEquippableAllowedEntities = models.Option[IDSet]

type SlotComponentDataLodestoneTrackerGlobalPosition = models.Option[GlobalPos]

type SlotComponentDataUseCooldownCooldownGroup = models.Option[pk.String]

type SlotComponentDataPotionContentsPotionId = models.Option[pk.VarInt]

type SlotComponentDataPotionContentsCustomColor = models.Option[pk.Int]

type SlotComponentDataPotionContentsCustomName = models.Option[pk.String]

type SlotComponentDataWrittenBookContentFilteredTitle = models.Option[pk.String]

type SlotComponentDataBlocksAttacksDamageReductionsArrayTypeType = models.Option[IDSet]

type SlotComponentDataBlocksAttacksBypassedBy = models.Option[pk.String]

type SlotComponentDataBlocksAttacksBlockSound = models.Option[ItemSoundHolder]

type SlotComponentDataBlocksAttacksDisableSound = models.Option[ItemSoundHolder]

type SlotComponentDataToolRulesArrayTypeSpeed = models.Option[pk.Float]

type SlotComponentDataToolRulesArrayTypeCorrectDropForBlocks = models.Option[pk.Boolean]

type ByteArray = pk.ByteArray

type DebugSubscriptionEventValueBreezesAttackTarget = models.Option[pk.VarInt]

type DebugSubscriptionEventValueBreezesJumpTarget = models.Option[Position]

type DebugSubscriptionEventValueBeesHivePos = models.Option[Position]

type DebugSubscriptionEventValueBeesFlowerPos = models.Option[Position]

type PreviousMessages = models.Array[pk.VarInt, PreviousMessagesPreviousMessagesElement]

type PlayerSkinPatchBody = models.Option[pk.String]

type PlayerSkinPatchCape = models.Option[pk.String]

type PlayerSkinPatchElytra = models.Option[pk.String]

type F64 = pk.Double

type Optvarint = pk.VarInt

type U32 = models.UInt32

type F32 = pk.Float
